# translation of new_ja.po to Japanese
# translation of anaconda.master.po to
# anaconda/ja.po
# Copyright (C) 2001 Red Hat, Inc.
# SATO Satoru <ssato@redhat.com>
#
# James Hashida <khashida@redhat.com>, 2002,2003.
# Noriko Mizumoto <noriko@redhat.com>, 2003, 2004, 2006, 2008, 2009.
# Yoshinari Takaoka <mumumu@mx.edit.ne.jp>, 2004.
# Tadashi Jokagi <fedora@elf.no-ip.org>, 2004, 2005.
# Naoki Shigematsu <sigematu@linuxml.net>, 2004.
# Hirofumi Saito <hi_saito@yk.rim.or.jp>, 2004, 2005, 2006.
# Kiyoto James Hashida <khashida@redhat.com>, 2006, 2007.
# Hyu_gabaru Ryu_ichi <hyu_gabaru@yahoo.co.jp>, 2007, 2009.
# Kiyoto Hashida <khashida@redhat.com>, 2007, 2008, 2009, 2010.
# Makoto Mizukami <mmk9060@aol.com>, 2008.
# Hajime Taira <htaira@redhat.com>, 2010.
msgid ""
msgstr ""
"Project-Id-Version: new_ja\n"
"Report-Msgid-Bugs-To: anaconda-devel-list@redhat.com\n"
"POT-Creation-Date: 2010-10-19 17:55-0700\n"
"PO-Revision-Date: 2010-09-19 22:05+0900\n"
"Last-Translator: Hajime Taira <htaira@redhat.com>\n"
"Language-Team: Japanese <jp@li.org>\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 1.11.4\n"
"Plural-Forms: Plural-Forms: nplurals=2; plural=(n!=1);\n"

#: anaconda:313
msgid "Press <enter> for a shell"
msgstr "シェルには、<enter> を押します。"

#: anaconda:336
msgid "Not enough RAM"
msgstr "RAM が足りません"

#: anaconda:337
msgid ""
" Try the text mode installer by running:\n"
"\n"
"'/usr/bin/liveinst -T'\n"
"\n"
" from a root terminal."
msgstr ""
"root ユーザーのターミナルから以下を実行してテキストモードインストーラをお試し"
"ください。\n"
"\n"
"'/usr/bin/liveinst -T'\n"
"\n"
" "

#: anaconda:340
msgid " Starting text mode."
msgstr "テキストモードで開始します。"

#: anaconda:364 pyanaconda/rescue.py:353 pyanaconda/rescue.py:379
#: pyanaconda/rescue.py:392 pyanaconda/rescue.py:475 pyanaconda/rescue.py:488
#: pyanaconda/rescue.py:499 pyanaconda/text.py:534 loader/windows.h:31
#: loader/cdinstall.c:229 loader/cdinstall.c:233 loader/cdinstall.c:249
#: loader/cdinstall.c:252 loader/cdinstall.c:428 loader/cdinstall.c:432
#: loader/cdinstall.c:505 loader/dirbrowser.c:129 loader/driverdisk.c:228
#: loader/driverdisk.c:408 loader/driverdisk.c:440 loader/driverdisk.c:471
#: loader/driverdisk.c:506 loader/driverdisk.c:522 loader/driverdisk.c:534
#: loader/driverdisk.c:542 loader/driverdisk.c:709 loader/driverdisk.c:748
#: loader/driverselect.c:79 loader/driverselect.c:179 loader/hdinstall.c:115
#: loader/hdinstall.c:266 loader/hdinstall.c:325 loader/hdinstall.c:360
#: loader/hdinstall.c:440 loader/hdinstall.c:483 loader/hdinstall.c:496
#: loader/kbd.c:119 loader/kickstart.c:135 loader/kickstart.c:145
#: loader/kickstart.c:187 loader/kickstart.c:192 loader/kickstart.c:299
#: loader/kickstart.c:339 loader/kickstart.c:355 loader/kickstart.c:382
#: loader/kickstart.c:571 loader/lang.c:114 loader/lang.c:373
#: loader/loader.c:433 loader/loader.c:469 loader/loader.c:509
#: loader/loader.c:527 loader/loader.c:544 loader/loader.c:581
#: loader/loader.c:1212 loader/loader.c:1399 loader/mediacheck.c:47
#: loader/mediacheck.c:86 loader/mediacheck.c:93 loader/mediacheck.c:97
#: loader/mediacheck.c:106 loader/method.c:286 loader/method.c:360
#: loader/net.c:621 loader/net.c:1001 loader/net.c:1654 loader/net.c:1675
#: loader/net.c:1981 loader/net.c:2000 loader/net.c:2012
#: loader/nfsinstall.c:116 loader/nfsinstall.c:309 loader/nfsinstall.c:326
#: loader/nfsinstall.c:414 loader/urlinstall.c:137 loader/urlinstall.c:159
#: loader/urlinstall.c:221 loader/urlinstall.c:374 loader/urlinstall.c:385
#: loader/urlinstall.c:392 loader/urls.c:269 loader/urls.c:340
#: loader/urls.c:346 loader/urls.c:355 pyanaconda/textw/constants_text.py:44
msgid "OK"
msgstr "OK"

#: anaconda:727
msgid "Would you like to use VNC?"
msgstr "VNC を使用しますか ?"

#: anaconda:728
msgid ""
"Text mode provides a limited set of installation options.  It does not allow "
"you to specify your own partitioning layout or package selections.  Would "
"you like to use VNC mode instead?"
msgstr ""
"テキストモードは限定的なインストールオプションのセットを提供します。好みの "
"パーティション設定やパッケージ選択の指定がありません。代わりに VNC モードを "
"使用しますか？"

#: anaconda:754
msgid "Graphical installation is not available. Starting text mode."
msgstr "グラフィカルインストールは使用できません。テキストモードを起動します。"

#: anaconda:762
msgid "DISPLAY variable not set. Starting text mode."
msgstr "DISPLAY 変数がセットされていません。テキストモードで起動します。"

#: pyanaconda/backend.py:135
#, python-format
msgid "Upgrading %s\n"
msgstr "%s のアップグレード\n"

#: pyanaconda/backend.py:137
#, python-format
msgid "Installing %s\n"
msgstr "%s のインストール\n"

#: pyanaconda/backend.py:150
msgid "Copying File"
msgstr "ファイルをコピー中"

#: pyanaconda/backend.py:151
msgid "Transferring install image to hard drive"
msgstr "インストールイメージをハードディスクに転送中"

#: pyanaconda/backend.py:161
msgid ""
"An error occurred transferring the install image to your hard drive.  This "
"is often cause by damaged or low quality media."
msgstr ""
"インストールイメージをハードディスクへ転送している際にエラーが発生しました。"
"これは傷んだ、または品質の悪い媒体が原因でよく発生します。"

#: pyanaconda/backend.py:165
msgid ""
"An error occurred transferring the install image to your hard drive. You are "
"probably out of disk space."
msgstr ""
"インストールイメージをハードディスクへ転送中にエラーが発生しました。おそらく"
"ディスク容量が不足しています。"

#: pyanaconda/backend.py:169 pyanaconda/image.py:286 pyanaconda/livecd.py:198
#: pyanaconda/livecd.py:440 pyanaconda/partIntfHelpers.py:233
#: pyanaconda/text.py:355 pyanaconda/text.py:359 pyanaconda/yuminstall.py:466
#: pyanaconda/yuminstall.py:838 pyanaconda/yuminstall.py:956
#: pyanaconda/yuminstall.py:961 pyanaconda/yuminstall.py:1225
#: pyanaconda/yuminstall.py:1285 pyanaconda/yuminstall.py:1476
#: pyanaconda/yuminstall.py:1498 pyanaconda/iw/advanced_storage.py:86
#: pyanaconda/iw/advanced_storage.py:96 pyanaconda/iw/advanced_storage.py:170
#: pyanaconda/iw/advanced_storage.py:173 pyanaconda/iw/advanced_storage.py:201
#: pyanaconda/iw/autopart_type.py:95 pyanaconda/iw/cleardisks_gui.py:44
#: pyanaconda/iw/cleardisks_gui.py:54 pyanaconda/iw/filter_gui.py:431
#: pyanaconda/iw/osbootwidget.py:211 pyanaconda/iw/osbootwidget.py:220
#: pyanaconda/iw/raid_dialog_gui.py:223 pyanaconda/iw/task_gui.py:54
#: pyanaconda/iw/task_gui.py:152 pyanaconda/iw/task_gui.py:305
#: pyanaconda/iw/task_gui.py:469 loader/windows.h:31 loader/cdinstall.c:229
#: loader/cdinstall.c:505 loader/driverdisk.c:228 loader/driverdisk.c:471
#: loader/driverdisk.c:506 loader/driverdisk.c:534 loader/driverdisk.c:542
#: loader/driverdisk.c:609 loader/hdinstall.c:115 loader/hdinstall.c:325
#: loader/hdinstall.c:440 loader/hdinstall.c:483 loader/hdinstall.c:496
#: loader/kickstart.c:299 loader/lang.c:114 loader/loader.c:433
#: loader/loader.c:544 loader/loader.c:1212 loader/mediacheck.c:47
#: loader/mediacheck.c:86 loader/mediacheck.c:93 loader/mediacheck.c:97
#: loader/method.c:286 loader/method.c:360 loader/nfsinstall.c:309
#: loader/nfsinstall.c:326 loader/urlinstall.c:137 loader/urlinstall.c:159
#: loader/urlinstall.c:221 loader/urls.c:340 loader/urls.c:346
#: loader/urls.c:355 pyanaconda/storage/__init__.py:230
#: pyanaconda/storage/__init__.py:1818 pyanaconda/storage/__init__.py:1905
#: pyanaconda/storage/zfcp.py:375 pyanaconda/textw/upgrade_text.py:181
#: pyanaconda/textw/upgrade_text.py:188
msgid "Error"
msgstr "エラー"

#: pyanaconda/bootloader.py:55 pyanaconda/bootloader.py:221
#: pyanaconda/bootloader.py:227 pyanaconda/gui.py:1081 pyanaconda/image.py:80
#: pyanaconda/installinterfacebase.py:51 pyanaconda/installinterfacebase.py:82
#: pyanaconda/installinterfacebase.py:142 pyanaconda/packages.py:314
#: pyanaconda/text.py:411 pyanaconda/yuminstall.py:1454
#: pyanaconda/yuminstall.py:1662 pyanaconda/yuminstall.py:1697
#: pyanaconda/iw/blpasswidget.py:148 pyanaconda/iw/upgrade_swap_gui.py:190
#: pyanaconda/iw/upgrade_swap_gui.py:198 pyanaconda/iw/upgrade_swap_gui.py:205
#: pyanaconda/textw/upgrade_text.py:193
msgid "Warning"
msgstr "警告"

#: pyanaconda/bootloader.py:56
msgid ""
"Filesystems have already been activated.  You cannot go back past this "
"point.\n"
"\n"
"Would you like to continue with the installation?"
msgstr ""
"ファイルシステムは既に活性化しています。ここから元に戻ることはできません。\n"
"\n"
"インストールを続けますか?"

#: pyanaconda/bootloader.py:60 pyanaconda/gui.py:1104 pyanaconda/gui.py:1141
#: pyanaconda/gui.py:1342 pyanaconda/image.py:89 pyanaconda/kickstart.py:156
#: pyanaconda/livecd.py:205 pyanaconda/livecd.py:447
#: pyanaconda/packages.py:131 pyanaconda/upgrade.py:58
#: pyanaconda/upgrade.py:98 pyanaconda/upgrade.py:254
#: pyanaconda/yuminstall.py:257 pyanaconda/yuminstall.py:756
#: pyanaconda/yuminstall.py:958 pyanaconda/yuminstall.py:963
#: pyanaconda/yuminstall.py:1043 pyanaconda/yuminstall.py:1049
#: pyanaconda/yuminstall.py:1204 pyanaconda/yuminstall.py:1221
#: pyanaconda/yuminstall.py:1275 pyanaconda/yuminstall.py:1463
#: pyanaconda/yuminstall.py:1482 pyanaconda/yuminstall.py:1505
#: pyanaconda/storage/__init__.py:114 pyanaconda/storage/__init__.py:123
#: pyanaconda/storage/__init__.py:234 pyanaconda/storage/__init__.py:1999
msgid "_Exit installer"
msgstr "インストーラを終了する(_E)"

#: pyanaconda/bootloader.py:60 pyanaconda/image.py:90 pyanaconda/image.py:249
#: pyanaconda/kickstart.py:1383 pyanaconda/kickstart.py:1422
#: pyanaconda/upgrade.py:58 pyanaconda/upgrade.py:98
#: pyanaconda/yuminstall.py:1280 pyanaconda/yuminstall.py:1464
#: pyanaconda/iw/partition_gui.py:1599 pyanaconda/storage/__init__.py:2000
msgid "_Continue"
msgstr "続行(_C)"

#: pyanaconda/bootloader.py:158
msgid "Bootloader"
msgstr "ブートローダー"

#: pyanaconda/bootloader.py:158
msgid "Installing bootloader."
msgstr "ブートローダーをインストール中です。"

#: pyanaconda/bootloader.py:222
msgid ""
"There was an error installing the bootloader.  The system may not be "
"bootable."
msgstr ""
"ブートローダーのインストールでエラーが発生しました。システムは起動できないか"
"もしれません。"

#: pyanaconda/bootloader.py:228
msgid ""
"No kernel packages were installed on the system.  Bootloader configuration "
"will not be changed."
msgstr ""
"システムにカーネルパッケージはインストールされませんでした。ブートローダー設"
"定は変更されません。"

#: pyanaconda/cmdline.py:56
msgid "Completed"
msgstr "完了"

#: pyanaconda/cmdline.py:64
msgid "In progress"
msgstr "進行中"

#: pyanaconda/cmdline.py:89 pyanaconda/gui.py:1136
#: pyanaconda/kickstart.py:1167 pyanaconda/kickstart.py:1247
#: pyanaconda/kickstart.py:1255 pyanaconda/kickstart.py:1293
#: pyanaconda/kickstart.py:1301 pyanaconda/text.py:392
#, python-format
msgid ""
"The following error was found while parsing the kickstart configuration "
"file:\n"
"\n"
"%s"
msgstr ""
"キックスタート設定ファイルの解析中に次のエラーが見つかりました。\n"
"\n"
"%s"

#: pyanaconda/cmdline.py:101
msgid ""
"Command line mode requires all choices to be specified in a kickstart "
"configuration file."
msgstr ""
"コマンドラインモードでは kickstart 設定ファイルに全ての選択が設定されている必"
"要があります。"

#: pyanaconda/cmdline.py:120 pyanaconda/cmdline.py:127
#: pyanaconda/cmdline.py:134 pyanaconda/cmdline.py:141
msgid "Can't have a question in command line mode!"
msgstr "コマンドラインモードでは質問は置けません!"

#: pyanaconda/constants.py:74
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report"
msgstr ""
"未処理の例外が発生しました。バグの可能性が考えられます。全てのメッセージをコ"
"ピーし、バグとして報告してください。"

#: pyanaconda/constants.py:80
msgid " with the provider of this software."
msgstr "このソフトウェアの供給者と共に"

#: pyanaconda/constants.py:84
#, python-format
msgid " against anaconda at %s"
msgstr "anaconda の %s に対して"

#: pyanaconda/gui.py:108
msgid "An error occurred saving screenshots to disk."
msgstr "スクリーンショットをディスクに保存中にエラーが発生しました。"

#: pyanaconda/gui.py:125
msgid "Screenshots Copied"
msgstr "スクリーンショットがコピーされました"

#: pyanaconda/gui.py:126
msgid ""
"The screenshots have been saved in the directory:\n"
"\n"
"\t/root/anaconda-screenshots/\n"
"\n"
"You can access these when you reboot and login as root."
msgstr ""
"スクリーンショットは次のディレクトリーに保存されました:\n"
"\n"
"\t/root/anaconda-screenshots/\n"
"\n"
"再起動して root でログインするとアクセスできます。"

#: pyanaconda/gui.py:165
msgid "Saving Screenshot"
msgstr "スクリーンショットを保存中"

#: pyanaconda/gui.py:166
#, python-format
msgid "A screenshot named '%s' has been saved."
msgstr "「%s」 と言う名前のスクリーンショットが保存されました。"

#: pyanaconda/gui.py:169
msgid "Error Saving Screenshot"
msgstr "スクリーンショット保存中にエラー発生"

#: pyanaconda/gui.py:170
msgid ""
"An error occurred while saving the screenshot.  If this occurred during "
"package installation, you may need to try several times for it to succeed."
msgstr ""
"スクリーンショット保存中にエラーが発生しました。パッケージインストール中に発"
"生した場合、完了するには数回試行する必要があるかもしれません。"

#: pyanaconda/gui.py:525 pyanaconda/text.py:150
msgid ""
"Choose a passphrase for the encrypted devices. You will be prompted for this "
"passphrase during system boot."
msgstr ""
"暗号化されたデバイス用のパスフレーズを選択してください。システムをブートする"
"時にそのパスフレーズを求められます。"

#: pyanaconda/gui.py:544 pyanaconda/gui.py:552 pyanaconda/text.py:188
#: pyanaconda/text.py:198
msgid "Error with passphrase"
msgstr "パスフレーズが違います。"

#: pyanaconda/gui.py:545 pyanaconda/text.py:189
msgid "The passphrases you entered were different.  Please try again."
msgstr "入力したパスフレーズが異ります。やり直してください。"

#: pyanaconda/gui.py:553
msgid "The passphrase must be at least eight characters long."
msgstr "パスフレーズは最低 6 文字以上でなければなりません。"

#: pyanaconda/gui.py:587 pyanaconda/text.py:226
#, python-format
msgid ""
"Device %s is encrypted. In order to access the device's contents during "
"installation you must enter the device's passphrase below."
msgstr ""
"デバイス %s は暗号化されています。インストール中にこのデバイスの内容にアクセ"
"スするには、以下にデバイスのパスフレーズを入力する必要があります。"

#: pyanaconda/gui.py:678 pyanaconda/gui.py:1342
#: pyanaconda/partIntfHelpers.py:153 pyanaconda/partIntfHelpers.py:338
#: pyanaconda/text.py:101 pyanaconda/text.py:102
#: pyanaconda/iw/account_gui.py:131 loader/dirbrowser.c:129
#: loader/driverdisk.c:409 loader/kickstart.c:382 loader/loader.c:469
#: loader/loader.c:581 pyanaconda/textw/constants_text.py:48
msgid "Cancel"
msgstr "取り消し"

#: pyanaconda/gui.py:690 pyanaconda/gui.py:691 pyanaconda/gui.py:809
#: pyanaconda/gui.py:810 data/ui/anaconda.glade.h:3
msgid "_Debug"
msgstr "デバッグ(_D)"

#: pyanaconda/gui.py:933
msgid "Wireless setup"
msgstr "無線のセットアップ"

#: pyanaconda/gui.py:934
msgid "Scanning access points for wireless devices"
msgstr "無線デバイス用のアクセスポイントをスキャンしています"

#: pyanaconda/gui.py:960 pyanaconda/textw/netconfig_text.py:399
msgid "Waiting for NetworkManager"
msgstr "NetworkManager を待っています。"

#: pyanaconda/gui.py:961
#, python-format
msgid "Waiting for NetworkManager to activate these devices: %s"
msgstr "NetworkManager がこれらのデバイスを開始するのを待っています: %s"

#: pyanaconda/gui.py:982
#, python-format
msgid "Failed to activate these network interfaces: %s"
msgstr "これらのネットワークインターフェースの開始に失敗しました: %s"

#: pyanaconda/gui.py:985
msgid "Network Configuration"
msgstr "ネットワークの設定"

#: pyanaconda/gui.py:994 pyanaconda/iw/netconfig_dialog.py:213
#, python-format
msgid "An error occurred trying to bring up the %s network interface."
msgstr "%s ネットワークインターフェイスを起動中にエラーが発生しました。"

#: pyanaconda/gui.py:996
msgid "Error Enabling Network"
msgstr "ネットワークの有効化でエラー"

#: pyanaconda/gui.py:1082 pyanaconda/text.py:412
msgid ""
"You do not have an active network connection.  This is required by some "
"exception saving methods.  Would you like to configure your network now?"
msgstr ""

#: pyanaconda/gui.py:1088 pyanaconda/kickstart.py:150 pyanaconda/rescue.py:262
#: pyanaconda/text.py:418 pyanaconda/yuminstall.py:751
#: pyanaconda/yuminstall.py:1199 pyanaconda/iw/task_gui.py:311
msgid "No Network Available"
msgstr "ネットワークは使用できません。"

#: pyanaconda/gui.py:1089 pyanaconda/text.py:419
msgid "Remote exception saving methods will not work."
msgstr ""

#: pyanaconda/gui.py:1138 pyanaconda/text.py:394
msgid "Error Parsing Kickstart Config"
msgstr "キックスタート設定ファイル解析エラー"

#: pyanaconda/gui.py:1166
msgid "default:LTR"
msgstr "デフォルト:LTR"

#: pyanaconda/gui.py:1246 pyanaconda/text.py:511
msgid "Error!"
msgstr "エラー!"

#: pyanaconda/gui.py:1247 pyanaconda/text.py:512
#, python-format
msgid ""
"An error occurred when attempting to load an installer interface component.\n"
"\n"
"className = %s"
msgstr ""
"インストーラーインターフェースコンポーネントを読み込もうとしてエラーが発生し"
"ました。\n"
"\n"
"className = %s"

#: pyanaconda/gui.py:1252 pyanaconda/image.py:163 pyanaconda/image.py:192
#: pyanaconda/packages.py:331 pyanaconda/storage/__init__.py:1817
msgid "_Exit"
msgstr "終了(_E)"

#: pyanaconda/gui.py:1253 pyanaconda/image.py:163 pyanaconda/image.py:192
#: pyanaconda/livecd.py:205 pyanaconda/yuminstall.py:835
#: pyanaconda/yuminstall.py:1221 pyanaconda/yuminstall.py:1275
#: pyanaconda/yuminstall.py:1482
msgid "_Retry"
msgstr "再試行(_R)"

#: pyanaconda/gui.py:1255 pyanaconda/storage/partitioning.py:283
msgid "The system will now reboot."
msgstr "システムが再起動します。"

#: pyanaconda/gui.py:1256 pyanaconda/image.py:249 pyanaconda/packages.py:335
#: pyanaconda/yuminstall.py:1523
msgid "_Reboot"
msgstr "再起動(_R)"

#: pyanaconda/gui.py:1258
msgid "Exiting"
msgstr "終了"

#: pyanaconda/gui.py:1339 pyanaconda/livecd.py:126 pyanaconda/text.py:271
#: pyanaconda/upgrade.py:245
msgid "Exit installer"
msgstr "インストーラーを終了する"

#: pyanaconda/gui.py:1340
msgid "Are you sure you wish to exit the installer?"
msgstr "本当にインストーラーを終了しますか?"

#: pyanaconda/gui.py:1349
#, python-format
msgid "%s Installer"
msgstr "%s インストーラー"

#: pyanaconda/gui.py:1355
msgid "Unable to load title bar"
msgstr "タイトルバーを読み込めません"

#: pyanaconda/gui.py:1433
msgid "Install Window"
msgstr "インストールウィンドウ"

#: pyanaconda/image.py:81
#, python-format
msgid ""
"The ISO image %s has a size which is not a multiple of 2048 bytes.  This may "
"mean it was corrupted on transfer to this computer.\n"
"\n"
"It is recommended that you exit and abort your installation, but you can "
"choose to continue if you think this is in error."
msgstr ""
"この ISO イメージ %s のサイズは、2048 バイトの倍数ではありません。これは、こ"
"のコンピューターへの転送の際に、それが破壊されたことを意味します。\n"
"\n"
"終了して、インストールを中止することをお勧めしますが、もしこれが間違いだと思"
"う場合は、続行することができます。 "

#: pyanaconda/image.py:155
msgid "Couldn't Mount ISO Source"
msgstr "ISO ソースをマウントできない"

#: pyanaconda/image.py:156
#, python-format
msgid ""
"An error occurred mounting the source device %s.  This may happen if your "
"ISO images are located on an advanced storage device like LVM or RAID, or if "
"there was a problem mounting a partition.  Click exit to abort the "
"installation."
msgstr ""
"ソースデバイス %s のマウントでエラーが起きました。LVM や RAID のような進化し"
"たストレージデバイスに ISO イメージが置かれたときや、パーティションのマウント"
"に問題がある場合に発生します。「終了」をクリックしてインストールを中止してく"
"ださい。"

#: pyanaconda/image.py:183
msgid "Missing ISO 9660 Image"
msgstr "ISO 9660 イメージがありません"

#: pyanaconda/image.py:184
#, python-format
msgid ""
"The installer has tried to mount image #%s, but cannot find it on the hard "
"drive.\n"
"\n"
"Please copy this image to the drive and click Retry.  Click Exit to abort "
"the installation."
msgstr ""
"インストーラーはイメージ #%s のマウントを試行しましたが、ハードディスク上に見"
"つかりませんでした。\n"
"\n"
"このイメージをドライブにコピーしてから「再試行」をクリックしてください。「終"
"了」をクリックするとインストールを中止します。"

#: pyanaconda/image.py:239
msgid "Required Install Media"
msgstr "必要なインストールメディア"

#: pyanaconda/image.py:240
#, python-format
msgid ""
"The software you have selected to install will require the following "
"%(productName)s %(productVersion)s discs:\n"
"\n"
"%(reqcdstr)s\n"
"Please have these ready before proceeding with the installation.  If you "
"need to abort the installation and exit please select \"Reboot\"."
msgstr ""
"インストール用に選択したソフトウェアには次の %(productName)s  "
"%(productVersion)s ディスクが 必要です:\n"
"\n"
"%(reqcdstr)s\n"
"インストールを続行する前にこれらのディスクを用意してください。インストールを"
"中止して操作を終了する必要がある場合は「再起動」を選択します。"

#: pyanaconda/image.py:249 pyanaconda/livecd.py:446 pyanaconda/packages.py:335
#: pyanaconda/upgrade.py:253 pyanaconda/yuminstall.py:963
#: pyanaconda/yuminstall.py:1049 pyanaconda/yuminstall.py:1463
#: pyanaconda/yuminstall.py:1505 pyanaconda/yuminstall.py:1523
#: data/ui/anaconda.glade.h:2
msgid "_Back"
msgstr "戻る(_B)"

#: pyanaconda/image.py:287
#, python-format
msgid ""
"An error occurred unmounting the disc.  Please make sure you're not "
"accessing %s from the shell on tty2 and then click OK to retry."
msgstr ""
"ディスクをアンマウント中にエラーが発生しました。tty2 のシェルから %s にアクセ"
"スしていないことを確認してから [OK] をクリックして再試行してください。"

#: pyanaconda/installclass.py:67
msgid "Install on System"
msgstr "システム上にインストール"

#: pyanaconda/installinterfacebase.py:52
#, python-format
msgid ""
"Disk %s contains BIOS RAID metadata, but is not part of any recognized BIOS "
"RAID sets. Ignoring disk %s."
msgid_plural ""
"Disks %s contain BIOS RAID metadata, but are not part of any recognized BIOS "
"RAID sets. Ignoring disks %s."
msgstr[0] ""
"ディスク %s には、BIOS RAID メタデータが含まれていますが、認識された BIOS "
"RAID セットの一部ではありません。ディスク %s を無視します。"
msgstr[1] ""
"ディスク %s には、BIOS RAID メタデータが含まれていますが、認識された BIOS "
"RAID セットの一部ではありません。ディスク %s を無視します。"

#: pyanaconda/installinterfacebase.py:83
#, python-format
msgid ""
"Error processing drive:\n"
"\n"
"%(path)s\n"
"%(size)-0.fMB\n"
"%(description)s\n"
"\n"
"This device may need to be reinitialized.\n"
"\n"
"REINITIALIZING WILL CAUSE ALL DATA TO BE LOST!\n"
"\n"
"This action may also be applied to all other disks needing reinitialization."
"%(details)s"
msgstr ""
"ドライブの処理中にエラー発生:\n"
"\n"
"%(path)s\n"
"%(size)-0.fMB\n"
"%(description)s\n"
"\n"
"このデバイスは再初期化が必要かも知れません。\n"
"\n"
"再初期化すると全てのデータが消失します!\n"
"\n"
"このアクションは再初期化を必要とする全ての他のディスクにも適用できるかも知れ"
"ません。%(details)s"

#: pyanaconda/installinterfacebase.py:92
#: pyanaconda/installinterfacebase.py:150
#: pyanaconda/installinterfacebase.py:184
msgid "_Ignore"
msgstr "無視 (_I)"

#: pyanaconda/installinterfacebase.py:93
#: pyanaconda/installinterfacebase.py:151
msgid "Ignore _all"
msgstr "全てを無視 (_A)"

#: pyanaconda/installinterfacebase.py:94
#: pyanaconda/installinterfacebase.py:152
msgid "_Re-initialize"
msgstr "再初期化 (_R)"

#: pyanaconda/installinterfacebase.py:95
#: pyanaconda/installinterfacebase.py:153
msgid "Re-ini_tialize all"
msgstr "全てを再初期化 (_T)"

#: pyanaconda/installinterfacebase.py:143
#, python-format
msgid ""
"Error processing LVM.\n"
"There is inconsistent LVM data on %(msg)s.  You can reinitialize all related "
"PVs (%(pvs)s) which will erase the LVM metadata, or ignore which will "
"preserve the contents.  This action may also be applied to all other PVs "
"with inconsistent metadata."
msgstr ""
"LVM をプロセス中にエラー発生。\n"
"%(msg)s 上に一貫性のない LVM データが存在します。LVM メタデータが消失すること"
"になる、全ての関連した PV (%(pvs)s) を再初期化するか、又は、コンテンツを保存"
"することになる無視をすることができます。このアクションは一貫性のないメタデー"
"タを持つ 全ての他の PV にも適用できるかも知れません。"

#: pyanaconda/installinterfacebase.py:171
msgid "Unformatted DASD Device Found"
msgid_plural "Unformatted DASD Devices Found"
msgstr[0] "フォーマットしていない DASD デバイスを発見しました"
msgstr[1] "フォーマットしていない DASD デバイスを発見しました"

#: pyanaconda/installinterfacebase.py:173
#, python-format
msgid ""
"Format uninitialized DASD device?\n"
"\n"
"There is %d uninitialized DASD device on this system.  To continue "
"installation, the device must be formatted.  Formatting will remove any data "
"on this device."
msgid_plural ""
"Format uninitialized DASD devices?\n"
"\n"
"There are %d uninitialized DASD devices on this system.  To continue "
"installation, the devices must be formatted.  Formatting will remove any "
"data on these devices."
msgstr[0] ""
"初期化をしていない DASD デバイスをフォーマットしますか? \n"
"\n"
"このシステムに %d 個の初期化していない DASD デバイスがあります。 インストール"
"を継続するには、デバイスをフォーマットする必要があります。 フォーマットをする"
"とデバイス上のデータはすべて消滅します。"
msgstr[1] ""
"初期化をしていない DASD デバイスをフォーマットしますか? \n"
"\n"
"このシステムに %d 個の初期化していない DASD デバイスがあります。 インストール"
"を継続するには、デバイスをフォーマットする必要があります。 フォーマットをする"
"とデバイス上のデータはすべて消滅します。"

#: pyanaconda/installinterfacebase.py:184 pyanaconda/iw/partition_gui.py:898
msgid "_Format"
msgstr "フォーマット(_F)"

#: pyanaconda/iutil.py:867
#, python-format
msgid ""
"Error: On open, cannot set reIPL method to %(reipl_type)s (%(filename)s: "
"%(e)s)"
msgstr ""
"エラー: 開く時に、reIPL メソッドを %(reipl_type)s (%(filename)s: %(e)s) に"
"セットできません"

#: pyanaconda/iutil.py:878
#, python-format
msgid ""
"Error: On write, cannot set reIPL method to %(reipl_type)s (%(filename)s: "
"%(e)s)"
msgstr ""
"エラー: 書き込みで、reIPL メソッドを %(reipl_type)s (%(filename)s: %(e)s) に"
"セットできません"

#: pyanaconda/iutil.py:887
#, python-format
msgid ""
"Error: On close, cannot set reIPL method to %(reipl_type)s (%(filename)s: "
"%(e)s)"
msgstr ""
"エラー: 閉じる時、reIPL メソッドを %(reipl_type)s (%(filename)s: %(e)s) に"
"セットできません"

#: pyanaconda/iutil.py:906
#, python-format
msgid "Error: Could not set %(device)s as reIPL device (%(e)s)"
msgstr ""
"エラー: %(device)s を reIPL デバイス (%(e)s) としてセットできませんでした"

#: pyanaconda/iutil.py:916
#, python-format
msgid "Error: Could not reset loadparm (%s)"
msgstr "エラー: loadparm (%s) をリセットできません"

#: pyanaconda/iutil.py:925
#, python-format
msgid "Warning: Could not reset parm (%s)"
msgstr "警告: parm (%s) をリセットできません"

#: pyanaconda/iutil.py:938
#, python-format
msgid ""
"After shutdown, please perform a manual IPL from DASD device %s to continue "
"installation"
msgstr ""
"シャットダウンの後に、DASD デバイス %s から手動で IPL を実行してインストール"
"を 継続してください"

#: pyanaconda/iutil.py:960
#, python-format
msgid "Error: reading FCP property %(syspath_property)s for reIPL (%(e)s)"
msgstr "エラー: reIPL (%(e)s) の FCP プロパティ %(syspath_property)s 読み込み"

#: pyanaconda/iutil.py:975
#, python-format
msgid "Error: writing FCP property %(reipl_property)s for reIPL (%(e)s)"
msgstr "エラー: reIPL (%(e)s) の FCP プロパティ %(reipl_property)s の書き込み"

#: pyanaconda/iutil.py:990
#, python-format
msgid ""
"Error: writing default FCP property %(reipl_property)s for reIPL (%(e)s)"
msgstr ""
"エラー: reIPL (%(e)s) のデフォルト FCP プロパティ %(reipl_property)s の書き込"
"み"

#: pyanaconda/iutil.py:1005
#, python-format
msgid ""
"After shutdown, please perform a manual IPL from FCP %(device)s with WWPN "
"%(wwpn)s and LUN %(lun)s to continue installation"
msgstr ""
"シャットダウンの後に、WWPN %(wwpn)s と LUN %(lun)sを使用して FCP %(device)s "
"から手動で IPL を実行して、インストールを継続して下さい"

#: pyanaconda/iutil.py:1022
msgid ""
"After shutdown, please perform a manual IPL from the device now containing /"
"boot to continue installation"
msgstr ""
"シャットダウンの後に、今 /boot を収納しているデバイスから手動で IPL を実行し"
"て、 インストールを継続して下さい"

#: pyanaconda/iutil.py:1033
msgid "Error determining boot device's disk name"
msgstr "ブートデバイスのディスク名の決定でエラー"

#: pyanaconda/iutil.py:1037
msgid "The mount point /boot or / is on a disk that we are not familiar with"
msgstr "マウントポイント /boot 又は / が熟知していないディスク上にあります"

#: pyanaconda/kickstart.py:115
#, python-format
msgid ""
"There was an error running the kickstart script at line %(lineno)s.  You may "
"examine the output in %(msgs)s.  This is a fatal error and installation will "
"be aborted.  Press the OK button to exit the installer."
msgstr ""
"キックスタートスクリプトの %(lineno)s 行目の実行中にエラーが発生しまし"
"た。%(msgs)s 内の出力を調査した方が良いでしょう。これは致命的なエラーであり、"
"インストールは中止されます。OK ボタンを押すとインストーラーを終了します。"

#: pyanaconda/kickstart.py:123 pyanaconda/kickstart.py:125
msgid "Scriptlet Failure"
msgstr "Scriptlet の失敗"

#: pyanaconda/kickstart.py:151
msgid ""
"Encryption key escrow requires networking, but there was an error enabling "
"the network on your system."
msgstr ""
"暗号化キー escrow は はネットワークを必要とします。しかし使用中のシステムで"
"ネットワークの有効化にエラーが発生しました。"

#: pyanaconda/kickstart.py:165
#, python-format
msgid ""
"The following error was encountered while downloading the escrow "
"certificate:\n"
"\n"
"%s"
msgstr ""
"escrow 証明書のダウンロード中に次のエラーに 遭遇しました:\n"
"\n"
"%s"

#: pyanaconda/kickstart.py:1266
#, python-format
msgid "Error processing %%ksappend lines: %s"
msgstr "%%ksappend 行目を処理中にエラーが発生しました: %s"

#: pyanaconda/kickstart.py:1269
#, python-format
msgid "Unknown error processing %%ksappend lines: %s"
msgstr "%%ksappend 行目を処理中に不明なエラーが発生しました: %s"

#: pyanaconda/kickstart.py:1324 pyanaconda/livecd.py:228
msgid "Post-Installation"
msgstr "インストール後"

#: pyanaconda/kickstart.py:1325
msgid "Running post-installation scripts"
msgstr "インストール後スクリプトを実行中"

#: pyanaconda/kickstart.py:1341
msgid "Pre-Installation"
msgstr "インストール前"

#: pyanaconda/kickstart.py:1342
msgid "Running pre-installation scripts"
msgstr "インストール前スクリプトを実行中"

#: pyanaconda/kickstart.py:1374
msgid "Missing Package"
msgstr "見つからないパッケージ"

#: pyanaconda/kickstart.py:1375
#, python-format
msgid ""
"You have specified that the package '%s' should be installed.  This package "
"does not exist. Would you like to continue or abort this installation?"
msgstr ""
"パッケージ '%s'をインストールするように指定しています。このパッケージは存在し"
"ません。インストールを続行しますか、中止しますか?"

#: pyanaconda/kickstart.py:1381 pyanaconda/kickstart.py:1420
msgid "_Abort"
msgstr "中止(_A)"

#: pyanaconda/kickstart.py:1382 pyanaconda/kickstart.py:1421
msgid "_Ignore All"
msgstr "全てを無視 (_I)"

#: pyanaconda/kickstart.py:1412
msgid "Missing Group"
msgstr "見つからないグループ"

#: pyanaconda/kickstart.py:1413
#, python-format
msgid ""
"You have specified that the group '%s' should be installed. This group does "
"not exist. Would you like to continue or abort this installation?"
msgstr ""
"グループ '%s'をインストールするように指定しています。このグループは存在しませ"
"ん。インストールを継続しますか、中止しますか?"

#: pyanaconda/kickstart.py:1511
#, python-format
msgid ""
"The kickstart configuration file is missing required information that "
"anaconda cannot prompt for.  Please add the following sections and try "
"again:\n"
"%s"
msgstr ""
"使用中のキックスタートファイルは、アナコンダが催促できない必要情報を欠いてお"
"ります。以下のセクションを追加して再試行して下さい:\n"
"%s"

#: pyanaconda/livecd.py:121
msgid "Unable to find image"
msgstr "イメージを検出できません。"

#: pyanaconda/livecd.py:122
#, python-format
msgid ""
"The given location isn't a valid %s live CD to use as an installation source."
msgstr ""
"与えられた場所は、インストールソースとして使用するための有効な %s ライブ ディ"
"スク ではありません。"

#: pyanaconda/livecd.py:180
msgid "Copying live image to hard drive."
msgstr "ライブイメージをハードディスクに転送中。"

#: pyanaconda/livecd.py:199
msgid ""
"There was an error installing the live image to your hard drive.  This could "
"be due to bad media.  Please verify your installation media.\n"
"\n"
"If you exit, your system will be left in an inconsistent state that will "
"require reinstallation."
msgstr ""
"ライブイメージをハードディスクにインストールする時にエラーが発生しました。 不"
"正なメディアが原因かもしれません。インストールメディアを確認して下さい。\n"
"\n"
"終了するとシステムは矛盾した状態となり、再インストールを必要とするように なり"
"ます。"

#: pyanaconda/livecd.py:229
msgid ""
"Performing post-installation filesystem changes.  This may take several "
"minutes."
msgstr ""
"インストール後のファイルシステムの変更を開始しています。これには、数分かかる"
"ことがあります。"

#: pyanaconda/livecd.py:441
#, python-format
msgid ""
"The root filesystem you created is not large enough for this live image "
"(%.2f MB required)."
msgstr ""
"作成した / (root) ファイルシステムのサイズが、このライブイメージが必要として"
"いるサイズより小さすぎます(最低 %.2f MB は必要です)。"

#: pyanaconda/network.py:63
msgid "Hostname must be 255 or fewer characters in length."
msgstr "ホスト名は 255 文字かそれ以下の長さにする必要があります。"

#: pyanaconda/network.py:69
msgid ""
"Hostname must start with a valid character in the ranges 'a-z', 'A-Z', or "
"'0-9'"
msgstr ""
"ホスト名は 「a-z」 又は 「A-Z」又は 「0-9」 の範囲の有効な文字で開始しなけれ"
"ば なりません。"

#: pyanaconda/network.py:74
msgid ""
"Hostnames can only contain the characters 'a-z', 'A-Z', '0-9', '-', or '.'"
msgstr ""
"ホスト名には 「a-z」、 「A-Z」、 「0-9」、「-」、 「.」以外の文字は使用できま"
"せん。"

#: pyanaconda/network.py:118
msgid "IP address is missing."
msgstr "IP アドレスがありません。"

#: pyanaconda/network.py:122
msgid ""
"IPv4 addresses must contain four numbers between 0 and 255, separated by "
"periods."
msgstr ""
"IPv4 アドレスは、ピリオドで区切られた 0 から 255 までの 4 つの数字を含まなけ"
"ればなりません。"

#: pyanaconda/network.py:125
#, python-format
msgid "'%s' is not a valid IPv6 address."
msgstr "%s は有効な IPv6 アドレスではありません。"

#: pyanaconda/network.py:127
#, python-format
msgid "'%s' is an invalid IP address."
msgstr "'%s' は、有効な IP アドレスではありません。"

#: pyanaconda/packages.py:112
msgid "Resizing Failed"
msgstr "リサイズに失敗"

#: pyanaconda/packages.py:113
#, python-format
msgid "There was an error encountered while resizing the device %s."
msgstr "デバイス %s のリサイズ中にエラーが発生しました。"

#: pyanaconda/packages.py:121
msgid "Migration Failed"
msgstr "移行に失敗しました。"

#: pyanaconda/packages.py:122
#, python-format
msgid "An error was encountered while migrating filesystem on device %s."
msgstr "デバイス %s 上のファイルシステムを移行中にエラーが発生しました。"

#: pyanaconda/packages.py:131
msgid "_File Bug"
msgstr "バグを記録する (_F)"

#: pyanaconda/packages.py:315
#, python-format
msgid ""
"Warning!  This is pre-release software!\n"
"\n"
"Thank you for downloading this pre-release of %(productName)s.\n"
"\n"
"This is not a final release and is not intended for use on production "
"systems.  The purpose of this release is to collect feedback from testers, "
"and it is not suitable for day to day usage.\n"
"\n"
"To report feedback, please visit:\n"
"\n"
"   %(bugzillaUrl)s\n"
"\n"
"and file a report against '%(fileagainst)s'.\n"
msgstr ""
"警告!  プレ-リリースのソフトウェアです!\n"
"\n"
"%(productName)s のプレリリースをダウンロードして頂きありがとうございます。\n"
"\n"
"これは最終リリースではありません。また実稼働用システムでの使用を目的としたも"
"のではありません。このリリースの目的は、テスターからのフィードバックを収集す"
"ることであり、日常の使用には適しません。\n"
"\n"
"フィードバックの報告には以下を開いて下さい:\n"
"\n"
"    %(bugzillaUrl)s\n"
"\n"
"そして %(fileagainst)s に対して報告を提出してください。\n"

#: pyanaconda/packages.py:331
msgid "_Install Anyway"
msgstr "とにかくインストールする (_I)"

#: pyanaconda/packages.py:334
msgid "Your system will now be rebooted..."
msgstr "システムが再起動します..."

#: pyanaconda/packages.py:336
msgid "Warning! This is pre-release software!"
msgstr "警告! これはベータ版のソフトウェアです!"

#: pyanaconda/partIntfHelpers.py:41
msgid "Please enter a volume group name."
msgstr "ボリュームグループ名を入力してください。"

#: pyanaconda/partIntfHelpers.py:45
msgid "Volume Group Names must be less than 128 characters"
msgstr "ボリュームグループ名は 128 文字以下にしてください"

#: pyanaconda/partIntfHelpers.py:48
#, python-format
msgid "Error - the volume group name %s is not valid."
msgstr "エラー - ボリュームグループ名 %s は有効ではありません。"

#: pyanaconda/partIntfHelpers.py:53
msgid ""
"Error - the volume group name contains illegal characters or spaces.  "
"Acceptable characters are letters, digits, '.' or '_'."
msgstr ""
"エラー - ボリュームグループ名に不適切な文字または空白が含まれています。ボ"
"リュームグループ名として使用できる符号は文字、数字、「.」、「_」になります。"

#: pyanaconda/partIntfHelpers.py:63
msgid "Please enter a logical volume name."
msgstr "論理ボリューム名を入力してください。"

#: pyanaconda/partIntfHelpers.py:67
msgid "Logical Volume Names must be less than 128 characters"
msgstr "論理ボリューム名は 128 文字以下にしてください"

#: pyanaconda/partIntfHelpers.py:71
#, python-format
msgid "Error - the logical volume name %s is not valid."
msgstr "エラー - 論理ボリューム名 %s は有効ではありません。"

#: pyanaconda/partIntfHelpers.py:77
msgid ""
"Error - the logical volume name contains illegal characters or spaces.  "
"Acceptable characters are letters, digits, '.' or '_'."
msgstr ""
"エラー - 論理ボリューム名に不適切な文字または空白が含まれています。論理ボ"
"リューム名に使用できる符号は文字、数字、「.」、「_」になります。"

#: pyanaconda/partIntfHelpers.py:105
#, python-format
msgid ""
"The mount point %s is invalid.  Mount points must start with '/' and cannot "
"end with '/', and must contain printable characters and no spaces."
msgstr ""
"マウントポイント %s は無効です。マウントポイントは 「/」 で始まらなければなら"
"ず、「/」 で終ることはできません。また、空白がなく表示可能な文字で構成されて"
"いなければなりません。"

#: pyanaconda/partIntfHelpers.py:117 pyanaconda/partIntfHelpers.py:124
msgid "Unable To Delete"
msgstr "削除できません"

#: pyanaconda/partIntfHelpers.py:118
msgid "You must first select a partition to delete."
msgstr "まず削除するパーティションを選択してください。"

#: pyanaconda/partIntfHelpers.py:149 pyanaconda/partIntfHelpers.py:337
#: pyanaconda/iw/lvm_dialog_gui.py:877
msgid "Confirm Delete"
msgstr "削除の確認"

#: pyanaconda/partIntfHelpers.py:150
#, python-format
msgid "You are about to delete all partitions on the device '%s'."
msgstr "デバイス %s 上のすべてのパーティションを削除しようとしています。"

#: pyanaconda/partIntfHelpers.py:153 pyanaconda/partIntfHelpers.py:338
#: pyanaconda/iw/lvm_dialog_gui.py:880 pyanaconda/iw/lvm_dialog_gui.py:1450
#: pyanaconda/iw/osbootwidget.py:104 pyanaconda/iw/partition_gui.py:1812
#: pyanaconda/iw/partition_gui.py:1824
msgid "_Delete"
msgstr "削除(_D)"

#: pyanaconda/partIntfHelpers.py:200
msgid "Notice"
msgstr "通知"

#: pyanaconda/partIntfHelpers.py:201
#, python-format
msgid ""
"The following partitions were not deleted because they are in use:\n"
"\n"
"%s"
msgstr ""
"次のパーティションは使用中のため削除されませんでした。\n"
"\n"
"%s"

#: pyanaconda/partIntfHelpers.py:216
msgid "Format as Swap?"
msgstr "swap としてフォーマットしますか?"

#: pyanaconda/partIntfHelpers.py:217
#, python-format
msgid ""
"%s has a partition type of 0x82 (Linux swap) but does not appear to be "
"formatted as a Linux swap partition.\n"
"\n"
"Would you like to format this partition as a swap partition?"
msgstr ""
"%s にはタイプ 0x82 (Linux swap) のパーティションがありますが、Linux swap パー"
"ティションとしてフォーマットされるようには表示されていません。\n"
"\n"
"このパーティションを swap パーティションとしてフォーマットしますか?"

#: pyanaconda/partIntfHelpers.py:232
#, python-format
msgid "You need to select at least one hard drive to install %s."
msgstr ""
"%s をインストールするには、少なくともハードディスクを 1 つ選択しなければなり"
"ません。"

#: pyanaconda/partIntfHelpers.py:237
msgid ""
"You have chosen to use a pre-existing partition for this installation "
"without formatting it. We recommend that you format this partition to make "
"sure files from a previous operating system installation do not cause "
"problems with this installation of Linux. However, if this partition "
"contains files that you need to keep, such as home directories, then "
"continue without formatting this partition."
msgstr ""
"既存のパーティションをフォーマットせずに、インストールに使用するよう選択して"
"います。前のオペレーティングシステムのファイル群が原因でこの Linux のインス"
"トールに支障をきたさないよう、パーティションのフォーマットを行うことを推奨し"
"ます。尚、ユーザーのホームディレクトリーなど保持しておく必要があるファイルを"
"ある場合は、パーティションのフォーマットを行わずに続行します。"

#: pyanaconda/partIntfHelpers.py:245
msgid "Format?"
msgstr "フォーマットしますか?"

#: pyanaconda/partIntfHelpers.py:245 pyanaconda/iw/partition_gui.py:1597
msgid "_Modify Partition"
msgstr "パーティションの変更(_M)"

#: pyanaconda/partIntfHelpers.py:245
msgid "Do _Not Format"
msgstr "フォーマットをしない(_N)"

#: pyanaconda/partIntfHelpers.py:253
msgid "Error with Partitioning"
msgstr "パーティション設定エラー"

#: pyanaconda/partIntfHelpers.py:254
#, python-format
msgid ""
"The following critical errors exist with your requested partitioning scheme. "
"These errors must be corrected prior to continuing with your install of "
"%(productName)s.\n"
"\n"
"%(errorstr)s"
msgstr ""
"要求されたパーティション設定に次のような致命的なエラーが存在していま"
"す。%(productName)s のインストールを続行する前に、これらのエラーを修正する必"
"要があります。\n"
"\n"
"%(errorstr)s"

#: pyanaconda/partIntfHelpers.py:270
msgid "Partitioning Warning"
msgstr "パーティション設定の警告"

#: pyanaconda/partIntfHelpers.py:271
#, python-format
msgid ""
"The following warnings exist with your requested partition scheme.\n"
"\n"
"%s\n"
"\n"
"Would you like to continue with your requested partitioning scheme?"
msgstr ""
"要求されたパーティション設定について次のような警告があります。\n"
"\n"
"%s\n"
"\n"
"このパーティション設定のまま続行しますか?"

#: pyanaconda/partIntfHelpers.py:285
msgid ""
"The following pre-existing partitions have been selected to be formatted, "
"destroying all data."
msgstr ""
"次の既存のパーティションをフォーマットするよう選択されています。これによりす"
"べてのデータが消去されます。"

#: pyanaconda/partIntfHelpers.py:288
msgid ""
"Select 'Yes' to continue and format these partitions, or 'No' to go back and "
"change these settings."
msgstr ""
"処理を続行してこれらのパーティションをフォーマットするには、「はい」を選択し"
"ます。前に戻り設定を変更するには「いいえ」を選択します。"

#: pyanaconda/partIntfHelpers.py:294
msgid "Format Warning"
msgstr "フォーマット警告"

#: pyanaconda/partIntfHelpers.py:321
#, python-format
msgid ""
"You are about to delete the volume group \"%s\".\n"
"\n"
"ALL logical volumes in this volume group will be lost!"
msgstr ""
"ボリュームグループ \"%s\" を削除しようとしています。\n"
" \n"
"このボリュームグループ内のすべての論理ボリュームが消去されます!"

#: pyanaconda/partIntfHelpers.py:325
#, python-format
msgid "You are about to delete the logical volume \"%s\"."
msgstr "論理ボリューム \"%s\" を削除しようとしています。"

#: pyanaconda/partIntfHelpers.py:328
msgid "You are about to delete a RAID device."
msgstr "RAID デバイスを削除しようとしています。"

#: pyanaconda/partIntfHelpers.py:330
#, python-format
msgid "You are about to delete the %s partition."
msgstr "%s パーティションを削除しようとしています。"

#: pyanaconda/partIntfHelpers.py:334
#, python-format
msgid "You are about to delete the %(type)s %(name)s"
msgstr "%(type)s %(name)s を削除しようとしています。"

#: pyanaconda/partIntfHelpers.py:345
msgid "Confirm Reset"
msgstr "リセットの確認"

#: pyanaconda/partIntfHelpers.py:346
msgid ""
"Are you sure you want to reset the partition table to its original state?"
msgstr "本当に、パーティションテーブル設定をリセットして元の状態に戻しますか?"

#: pyanaconda/platform.py:98 pyanaconda/platform.py:344
#: pyanaconda/platform.py:412 pyanaconda/platform.py:520
#: data/ui/create-storage.glade.h:15
msgid "RAID Device"
msgstr "RAID デバイス"

#: pyanaconda/platform.py:99 pyanaconda/platform.py:102
#: pyanaconda/platform.py:345 pyanaconda/platform.py:413
#: pyanaconda/platform.py:521 pyanaconda/platform.py:524
msgid "Master Boot Record (MBR)"
msgstr "マスタブートレコード(MBR)"

#: pyanaconda/platform.py:101 pyanaconda/platform.py:523
msgid "First sector of boot partition"
msgstr "ブートパーティションの最初のセクタ"

#: pyanaconda/platform.py:113
msgid "You have not created a bootable partition."
msgstr "ブート可能なパーティションが作成されていません。"

#: pyanaconda/platform.py:118
msgid "Bootable partitions cannot be on a RAID device."
msgstr "起動可能なパーティションを RAID デバイス上に作成することはできません。"

#: pyanaconda/platform.py:120
msgid "Bootable partitions can only be on RAID1 devices."
msgstr "RAID1 デバイス上にしか起動可能なパーティションは存在できません。"

#: pyanaconda/platform.py:124
msgid "Bootable RAID1 set members must be partitions."
msgstr ""
"ブート可能な RAID1 セットのメンバーはパーティションでなければなりません。"

#: pyanaconda/platform.py:129
msgid "Bootable partitions cannot be on a logical volume."
msgstr "起動可能なパーティションは論理ボリューム上には存在できません。"

#: pyanaconda/platform.py:136
#, python-format
msgid "Bootable partitions cannot be on an %s filesystem."
msgstr ""
"起動可能なパーティションを、ファイルシステム %s に作成することはできません。"

#: pyanaconda/platform.py:140 pyanaconda/platform.py:145
msgid "Bootable partitions cannot be on an encrypted block device"
msgstr ""
"起動可能なパーティションを暗号化されたブロックデバイス上に作成することはでき"
"ません。"

#: pyanaconda/platform.py:217
msgid "EFI System Partition"
msgstr "EFI システムパーティション"

#: pyanaconda/platform.py:229
msgid "You have not created a /boot/efi partition."
msgstr "/boot/efi パーティションが作成されていません。"

#: pyanaconda/platform.py:235
msgid "/boot/efi is not EFI."
msgstr "/boot/efi は EFI ではありません。"

#: pyanaconda/platform.py:251
#, python-format
msgid "%s must have a %s disk label."
msgstr "%s は %s ディスクラベルを持っている必要があります。"

#: pyanaconda/platform.py:289
#, python-format
msgid "%s must have a bsd disk label."
msgstr "%s は bsd ディスクラベルを持っている必要があります。"

#: pyanaconda/platform.py:301
#, python-format
msgid "The disk %s requires at least 1MB of free space at the beginning."
msgstr "ディスク %s には最初に少なくとも 1MB の空き領域が必要です。"

#: pyanaconda/platform.py:347
msgid "PPC PReP Boot"
msgstr "PPC PReP ブート"

#: pyanaconda/platform.py:363
msgid "The boot partition must be within the first 4MB of the disk."
msgstr "ブートパーティションはディスクの最初の 4MB 以内にある必要があります。"

#: pyanaconda/platform.py:415 pyanaconda/platform.py:418
msgid "Apple Bootstrap"
msgstr "Apple ブートストラップ"

#: pyanaconda/platform.py:432
#, python-format
msgid "%s must have a mac disk label."
msgstr "%s には mac ディスクラベルを持っている必要があります。"

#: pyanaconda/rescue.py:221
msgid "When finished please exit from the shell and your system will reboot."
msgstr "完了したらシェルを終了してください。システムが再起動します。"

#: pyanaconda/rescue.py:235
msgid "Unable to find /bin/sh to execute!  Not starting shell"
msgstr "実行するための /bin/sh が見付かりません。シェルを 開始していません。"

#: pyanaconda/rescue.py:254
msgid "Setup Networking"
msgstr "ネットワークの設定"

#: pyanaconda/rescue.py:255
msgid "Do you want to start the network interfaces on this system?"
msgstr "このシステムでネットワークインターフェースを開始しますか?"

#: pyanaconda/rescue.py:256 loader/driverdisk.c:649 loader/driverdisk.c:659
#: loader/hdinstall.c:212 pyanaconda/textw/constants_text.py:56
msgid "Yes"
msgstr "はい"

#: pyanaconda/rescue.py:256 pyanaconda/rescue.py:258 loader/driverdisk.c:649
#: loader/driverdisk.c:659 pyanaconda/textw/constants_text.py:60
msgid "No"
msgstr "いいえ"

#: pyanaconda/rescue.py:263
msgid ""
"Unable to activate a networking device.  Networking will not be available in "
"rescue mode."
msgstr ""
"ネットワーキングデバイスを始動できません。ネットワーキングはレスキューモード"
"では 使用できません。"

#: pyanaconda/rescue.py:299 pyanaconda/rescue.py:374 pyanaconda/rescue.py:385
#: pyanaconda/rescue.py:470 pyanaconda/rescue.py:499
msgid "Rescue"
msgstr "レスキュー"

#: pyanaconda/rescue.py:300
#, python-format
msgid ""
"The rescue environment will now attempt to find your Linux installation and "
"mount it under the directory %s.  You can then make any changes required to "
"your system.  If you want to proceed with this step choose 'Continue'.  You "
"can also choose to mount your file systems read-only instead of read-write "
"by choosing 'Read-Only'.  If you need to activate SAN devices choose "
"'Advanced'.\n"
"\n"
"If for some reason this process fails you can choose 'Skip' and this step "
"will be skipped and you will go directly to a command shell.\n"
"\n"
msgstr ""
"レスキュー環境はこれから Linux インストールを探し、ディレクトリー %s の下にマ"
"ウントしようと試みます。その後にご使用のシステムに必要な変更を行うことができ"
"ます。このプロセスを続ける場合、「続行」を選択してください。また「読み取り専"
"用」を選択すると、「読み取りと書き込み」ではなく「読み取り専用」でのファイル"
"システムのマウントを選択することもできます。SAN デバイスをアクティベート する"
"必要がある場合は、「高度な設定」を選択して下さい。\n"
"\n"
"何らかの原因でこのプロセスが失敗する場合は「スキップする」を選択し、このプロ"
"セスをとばして直接コマンドシェルに行くことができます。\n"
"\n"

#: pyanaconda/rescue.py:311 pyanaconda/iw/partition_gui.py:785
#: loader/cdinstall.c:207 loader/cdinstall.c:215 loader/driverdisk.c:610
#: pyanaconda/storage/__init__.py:169 pyanaconda/storage/devicetree.py:90
msgid "Continue"
msgstr "続行"

#: pyanaconda/rescue.py:311 pyanaconda/rescue.py:320
msgid "Read-Only"
msgstr "読み取り専用"

#: pyanaconda/rescue.py:311 pyanaconda/rescue.py:313 loader/cdinstall.c:249
#: loader/cdinstall.c:252 loader/method.c:333
#: pyanaconda/storage/__init__.py:1817 pyanaconda/textw/upgrade_text.py:139
msgid "Skip"
msgstr "スキップする"

#: pyanaconda/rescue.py:311 pyanaconda/rescue.py:316
msgid "Advanced"
msgstr "高度な設定"

#: pyanaconda/rescue.py:350
msgid "System to Rescue"
msgstr "レスキュー対象システム"

#: pyanaconda/rescue.py:351
msgid "Which device holds the root partition of your installation?"
msgstr "どのデバイスにインストールの root パーティションを置きますか？"

#: pyanaconda/rescue.py:353 pyanaconda/rescue.py:357 pyanaconda/text.py:516
#: pyanaconda/text.py:518
msgid "Exit"
msgstr "終了"

#: pyanaconda/rescue.py:375
msgid ""
"Your system had dirty file systems which you chose not to mount.  Press "
"return to get a shell from which you can fsck and mount your partitions.  "
"The system will reboot automatically when you exit from the shell."
msgstr ""
"システムに損傷のあるファイルシステムがありマウントしないことを選択していま"
"す。[Enter] を押すとシェルが起動され、そこで fsck やパーティションのマウント"
"ができます。シェルを終了するとシステムは自動的に再起動します。"

#: pyanaconda/rescue.py:386
#, python-format
msgid ""
"Your system has been mounted under %(rootPath)s.\n"
"\n"
"Press <return> to get a shell. If you would like to make your system the "
"root environment, run the command:\n"
"\n"
"\tchroot %(rootPath)s\n"
"\n"
"The system will reboot automatically when you exit from the shell."
msgstr ""
"システムを %(rootPath)s 下にマウントしています。\n"
"\n"
"シェルを起動するには <return> を押してください。そのシステムを root 環境とし"
"て利用するには次のコマンドを実行します:\n"
"\n"
"\tchroot %(rootPath)s\n"
"\n"
"シェルを終了するとシステムは自動的に再起動します。"

#: pyanaconda/rescue.py:471
#, python-format
msgid ""
"An error occurred trying to mount some or all of your system. Some of it may "
"be mounted under %s.\n"
"\n"
"Press <return> to get a shell. The system will reboot automatically when you "
"exit from the shell."
msgstr ""
"システムのいくつか、あるいはすべてをマウントしようと試みている間にエラーが発"
"生しました。いくつかのパーティションは %s の下にマウントされています。\n"
"\n"
"シェルを起動するには [Enter] を押してください。シェルを終了するとシステムは自"
"動的に再起動します。"

#: pyanaconda/rescue.py:481
msgid "You don't have any Linux partitions.  Rebooting.\n"
msgstr "Linux パーティションがありません。再起動します。\n"

#: pyanaconda/rescue.py:484
msgid "Rescue Mode"
msgstr "レスキューモード"

#: pyanaconda/rescue.py:485
msgid ""
"You don't have any Linux partitions. Press return to get a shell. The system "
"will reboot automatically when you exit from the shell."
msgstr ""
"Linux パーティションがありません。シェルを起動するには [Enter] を押してくださ"
"い。シェルを終了するとシステムは自動的に再起動します。"

#: pyanaconda/rescue.py:498
#, python-format
msgid "Your system is mounted under the %s directory."
msgstr "システムは %s ディレクトリー配下にマウントされます。"

#: pyanaconda/text.py:155
msgid "Passphrase for encrypted device"
msgstr "暗号化されたデバイス用のパスフレーズ"

#: pyanaconda/text.py:168
msgid "Also add this passphrase to all existing encrypted devices"
msgstr "全ての暗号化された既存デバイスにもこのパスフレーズを追加します。"

#: pyanaconda/text.py:199
#, python-format
msgid "The passphrase must be at least %d character long."
msgid_plural "The passphrase must be at least %d characters long."
msgstr[0] "パスフレーズは最低 %d 文字以上でなければなりません。"
msgstr[1] "パスフレーズは最低 %d 文字以上でなければなりません。"

#: pyanaconda/text.py:233 data/ui/lukspassphrase.glade.h:6
msgid "Passphrase"
msgstr "パスフレーズ"

#: pyanaconda/text.py:241 data/ui/lukspassphrase.glade.h:7
msgid "This is a global passphrase"
msgstr "これはグローバルパスフレーズです。"

#: pyanaconda/text.py:356 pyanaconda/text.py:360
msgid "Repository editing is not available in text mode."
msgstr "リポジトリーの編集は、テキストモードではできません。"

#: pyanaconda/text.py:437
#, python-format
msgid "Welcome to %(productName)s for %(productArch)s"
msgstr "%(productArch)s の %(productName)s へようこそ"

#: pyanaconda/text.py:439
#, python-format
msgid "Welcome to %s"
msgstr "%s へようこそ"

#: pyanaconda/text.py:441
msgid ""
"  <Tab>/<Alt-Tab> between elements   |  <Space> selects   |  <F12> next "
"screen"
msgstr "  <Tab>/<Alt-Tab> 項目間の移動   |  <Space> 選択   |  <F12> 次の画面"

#: pyanaconda/text.py:516 loader/net.c:110 loader/net.c:513 loader/net.c:568
#: loader/net.c:710 loader/net.c:718 loader/net.c:1148 loader/net.c:1156
msgid "Retry"
msgstr "再試行"

#: pyanaconda/text.py:530
msgid "Cancelled"
msgstr "取り消されました"

#: pyanaconda/text.py:531
msgid "I can't go to the previous step from here. You will have to try again."
msgstr "直前のステップに戻ることはできません。もう一度やり直してください。"

#: pyanaconda/upgrade.py:51
msgid "Proceed with upgrade?"
msgstr "アップグレードしますか?"

#: pyanaconda/upgrade.py:52
msgid ""
"The file systems of the Linux installation you have chosen to upgrade have "
"already been mounted. You cannot go back past this point. \n"
"\n"
msgstr ""
"アップグレードの選択をした Linux インストールのファイルシステムは既にマウント"
"されています。ここから元に戻ることはできません。\n"
"\n"

#: pyanaconda/upgrade.py:56
msgid "Would you like to continue with the upgrade?"
msgstr "アップグレードを続行しますか?"

#: pyanaconda/upgrade.py:91
msgid "Cannot Upgrade"
msgstr "アップグレードできません"

#: pyanaconda/upgrade.py:92
#, python-format
msgid ""
"Your current installation cannot be upgraded. This is likely due to it being "
"too old. Only the previous two release may be upgraded. To upgrade older "
"releases you must first upgrade through all intermediate releases.\n"
"\n"
"%s"
msgstr ""
"現在のインストールはアップグレードができません。これは多分古すぎることが 原因"
"だと思われます。直前の２つのリリースのみがアップグレード可能です。古い リリー"
"スをアップグレードするには、順番に中間リリースへのアップグレードから \n"
"始めてください。\n"
"%s"

#: pyanaconda/upgrade.py:232
msgid "Mount failed"
msgstr "マウントに失敗しました"

#: pyanaconda/upgrade.py:233
#, python-format
msgid ""
"The following error occurred when mounting the file systems listed in /etc/"
"fstab.  Please fix this problem and try to upgrade again.\n"
"%s"
msgstr ""
"/etc/fstab に一覧表示されたファイルシステムをマウント中に以下のエラーが 発生"
"しました。この問題を解決してから再度アップグレードをして下さい\n"
"%s"

#: pyanaconda/upgrade.py:241 pyanaconda/upgrade.py:248
msgid "Upgrade root not found"
msgstr "アップグレード root が見付かりません"

#: pyanaconda/upgrade.py:242
msgid "The root for the previously installed system was not found."
msgstr "以前のインストールされたシステムに root が見つかりませんでした。"

#: pyanaconda/upgrade.py:249
msgid ""
"The root for the previously installed system was not found.  You can exit "
"installer or backtrack to choose installation instead of upgrade."
msgstr ""
"以前にインストールされたシステムの root が見付かりません。インストーラを 終了"
"するか、又はアップグレードの代わりにインストールを選択するために戻る ことが出"
"来ます。"

#: pyanaconda/upgrade.py:272
msgid ""
"The following files are absolute symbolic links, which we do not support "
"during an upgrade. Please change them to relative symbolic links and restart "
"the upgrade.\n"
"\n"
msgstr ""
"次のファイルはアップグレード中にはサポートしていない絶対シンボリックリンクで"
"す。相対シンボリックリンクに変更してからアップグレードを再開してください。\n"
"\n"

#: pyanaconda/upgrade.py:278
msgid "Absolute Symlinks"
msgstr "絶対 Symlink"

#: pyanaconda/upgrade.py:289
msgid ""
"The following are directories which should instead be symbolic links, which "
"will cause problems with the upgrade.  Please return them to their original "
"state as symbolic links and restart the upgrade.\n"
"\n"
msgstr ""
"これらは、シンボリックリンクであるべきディレクトリーであり、アップグレード時"
"に起きる問題の原因となります。シンボリックリンクとして本来の状態に戻してから"
"アップグレードを再開してください。\n"
"\n"

#: pyanaconda/upgrade.py:295
msgid "Invalid Directories"
msgstr "無効なディレクトリー"

#: pyanaconda/vnc.py:140
#, python-format
msgid "%(productName)s %(productVersion)s installation on host %(name)s"
msgstr "ホスト %(name)s 上の %(productName)s %(productVersion)s インストール"

#: pyanaconda/vnc.py:146
#, python-format
msgid "%(productName)s %(productVersion)s installation"
msgstr "%(productName)s %(productVersion)s のインストール"

#: pyanaconda/vnc.py:175
#, python-format
msgid "Attempting to connect to vnc client on host %s..."
msgstr "ホスト %s 上の vnc クライアントに接続を試行中..."

#: pyanaconda/vnc.py:189
msgid "Connected!"
msgstr "接続しました!"

#: pyanaconda/vnc.py:192
msgid "Will try to connect again in 15 seconds..."
msgstr "15 秒後に再接続を試みます..."

#: pyanaconda/vnc.py:198
#, python-format
msgid "Giving up attempting to connect after %d try!\n"
msgid_plural "Giving up attempting to connect after %d tries!\n"
msgstr[0] "%d 回の試行の後で接続試行をあきらめます!\n"
msgstr[1] "%d 回の試行の後で接続試行をあきらめます!\n"

#: pyanaconda/vnc.py:209
#, python-format
msgid "Please manually connect your vnc client to %s to begin the install."
msgstr ""
"インストールを開始するには、ご使用の vnc クライアントを %s に手動で接続してく"
"ださい。"

#: pyanaconda/vnc.py:211
msgid "Please manually connect your vnc client to begin the install."
msgstr ""
"インストールを開始するには、ご使用の vnc クライアントを手動で接続してくださ"
"い。"

#: pyanaconda/vnc.py:214
msgid "Starting VNC..."
msgstr "VNC を起動中..."

#: pyanaconda/vnc.py:239
msgid "The VNC server is now running."
msgstr "VNC サーバーが稼動しています。"

#: pyanaconda/vnc.py:252
msgid ""
"\n"
"\n"
"You chose to connect to a listening vncviewer. \n"
"This does not require a password to be set.  If you \n"
"set a password, it will be used in case the connection \n"
"to the vncviewer is unsuccessful\n"
"\n"
msgstr ""
"\n"
"\n"
"Listen モードの VNC Viewer に接続するよう選択しました。\n"
"これは、パスワードを必要としません。もしパスワードを設定すると、\n"
"VNC Viewew への接続失敗の原因になります。\n"
"\n"

#: pyanaconda/vnc.py:257
msgid ""
"\n"
"\n"
"WARNING!!! VNC server running with NO PASSWORD!\n"
"You can use the vncpassword=<password> boot option\n"
"if you would like to secure the server.\n"
"\n"
msgstr ""
"\n"
"\n"
"警告!!! VNC サーバーがパスワードなしで実行されています!\n"
"サーバーの安全性を確保するには、vncpassword=<password>\n"
"ブートオプションを使うことができます。\n"
"\n"

#: pyanaconda/vnc.py:261
msgid ""
"\n"
"\n"
"You chose to execute vnc with a password. \n"
"\n"
msgstr ""
"\n"
"\n"
"パスワードを使って VNC を実行するように選択しました。\n"
"\n"

#: pyanaconda/vnc.py:263
msgid ""
"\n"
"\n"
"Unknown Error.  Aborting. \n"
"\n"
msgstr ""
"\n"
"\n"
"不明なエラーが発生しました。作業を中断します。\n"

#: pyanaconda/vnc.py:285 pyanaconda/vnc.py:378
msgid "VNC Configuration"
msgstr "VNC の設定"

#: pyanaconda/vnc.py:288 pyanaconda/vnc.py:382
msgid "No password"
msgstr "パスワードなし"

#: pyanaconda/vnc.py:290 pyanaconda/vnc.py:385
msgid ""
"A password will prevent unauthorized listeners connecting and monitoring "
"your installation progress.  Please enter a password to be used for the "
"installation"
msgstr ""
"パスワードによって許可のないリスナーが接続してインストールの進捗を傍受するの"
"を防ぎます。インストールに使用するパスワードを入力してください。"

#: pyanaconda/vnc.py:298 pyanaconda/vnc.py:393
#: pyanaconda/textw/userauth_text.py:47
msgid "Password:"
msgstr "パスワード:"

#: pyanaconda/vnc.py:299 pyanaconda/vnc.py:394
#: pyanaconda/textw/userauth_text.py:49
msgid "Password (confirm):"
msgstr "パスワード (確認):"

#: pyanaconda/vnc.py:317 pyanaconda/vnc.py:416
#: pyanaconda/textw/userauth_text.py:70
msgid "Password Mismatch"
msgstr "パスワードが一致しません"

#: pyanaconda/vnc.py:318 pyanaconda/vnc.py:417
#: pyanaconda/textw/userauth_text.py:71
msgid "The passwords you entered were different. Please try again."
msgstr "入力したパスワードが異なっています。再度やり直してください。"

#: pyanaconda/vnc.py:323 pyanaconda/vnc.py:422
#: pyanaconda/textw/userauth_text.py:66
msgid "Password Length"
msgstr "パスワードの長さ"

#: pyanaconda/vnc.py:324 pyanaconda/vnc.py:423
msgid "The password must be at least six characters long."
msgstr "パスワードは最低 6 文字以上でなければなりません。"

#: pyanaconda/vnc.py:346
msgid "Unable to Start X"
msgstr "X を起動できません"

#: pyanaconda/vnc.py:348
msgid ""
"X was unable to start on your machine.  Would you like to start VNC to "
"connect to this computer from another computer and perform a graphical "
"install or continue with a text mode install?"
msgstr ""
"ご使用のマシンで X を起動できませんでした。VNC を起動して別のコンピューターか"
"らこのコンピューターに接続しグラフィカルインストールを行ないますか、あるいは"
"テキストモードのインストールで続行しますか?"

#: pyanaconda/vnc.py:367
msgid "Start VNC"
msgstr "VNC を起動する"

#: pyanaconda/vnc.py:368 pyanaconda/vnc.py:370
msgid "Use text mode"
msgstr "テキストモードを使用する"

#: pyanaconda/yuminstall.py:85
#, python-format
msgid "%s MB"
msgstr "%s MB"

#: pyanaconda/yuminstall.py:88
#, python-format
msgid "%s KB"
msgstr "%s KB"

#: pyanaconda/yuminstall.py:90
#, python-format
msgid "%s Byte"
msgid_plural "%s Bytes"
msgstr[0] "%s バイト"
msgstr[1] "%s バイト"

#: pyanaconda/yuminstall.py:134
msgid "Preparing to install"
msgstr "インストールの準備中"

#: pyanaconda/yuminstall.py:135
msgid "Preparing transaction from installation source"
msgstr "インストールソースからのトランザクションを準備中。"

#: pyanaconda/yuminstall.py:163
#, python-format
msgid "<b>Installing %(pkgStr)s</b> (%(size)s)\n"
msgstr "<b>%(pkgStr)s のインストール</b> (%(size)s)\n"

#: pyanaconda/yuminstall.py:212
#, python-format
msgid "Packages completed: %(donepkgs)d of %(numpkgs)d"
msgid_plural "Packages completed: %(donepkgs)d of %(numpkgs)d"
msgstr[0] "完了したパッケージ: %(numpkgs)d 個中 %(donepkgs)d 個が完了"
msgstr[1] "完了したパッケージ: %(numpkgs)d 個中 %(donepkgs)d 個が完了"

#: pyanaconda/yuminstall.py:227
msgid "Finishing upgrade"
msgstr "アップグレードを終了中..."

#: pyanaconda/yuminstall.py:228
msgid "Finishing upgrade process.  This may take a little while."
msgstr "アップグレードプロセスを終了しています。数分かかることがあります。"

#: pyanaconda/yuminstall.py:251
msgid "Error Installing Package"
msgstr "パッケージのインストールでエラー"

#: pyanaconda/yuminstall.py:252
#, python-format
msgid ""
"A fatal error occurred when installing the %s package.  This could indicate "
"errors when reading the installation media.  Installation cannot continue."
msgstr ""
"%s パッケージをインストールしている時に致命的なエラーが発生しました。これはイ"
"ンストール媒体を読み込む時のエラーを示しているのかもしれません。インストール"
"を継続できません。"

#: pyanaconda/yuminstall.py:402 pyanaconda/iw/task_gui.py:324
msgid "Error Setting Up Repository"
msgstr "リポジトリーの設定中にエラー"

#: pyanaconda/yuminstall.py:403
#, python-format
msgid ""
"The following error occurred while setting up the installation repository:\n"
"\n"
"%(e)s\n"
"\n"
"Please provide the correct information for installing %(productName)s."
msgstr ""
"インストールリポジトリー設定中に次のエラーが発生しました:\n"
"\n"
"%(e)s\n"
"\n"
"%(productName)s のインストールについての正しい情報を提示して下さい。"

#: pyanaconda/yuminstall.py:448
msgid "Change Disc"
msgstr "ディスクの変更"

#: pyanaconda/yuminstall.py:449
#, python-format
msgid "Please insert %(productName)s disc %(discnum)d to continue."
msgstr "%(productName)s ディスク %(discnum)d を挿入して続行して下さい。"

#: pyanaconda/yuminstall.py:459
msgid "Wrong Disc"
msgstr "不適切なディスクです"

#: pyanaconda/yuminstall.py:460
#, python-format
msgid "That's not the correct %s disc."
msgstr "正しい %s ディスクではありません。"

#: pyanaconda/yuminstall.py:467
msgid "Unable to access the disc."
msgstr "ディスクにアクセスできません。"

#: pyanaconda/yuminstall.py:631
#, python-format
msgid "Repository %r is missing name in configuration, using id"
msgstr "リポジトリー %r は設定内で名前がありません。id を使用します。"

#: pyanaconda/yuminstall.py:752 pyanaconda/yuminstall.py:1200
#: pyanaconda/iw/task_gui.py:312
msgid ""
"Some of your software repositories require networking, but there was an "
"error enabling the network on your system."
msgstr ""
"ソフトウェアリポジトリーの一部はネットワークを必要とします。しかし、使用中の"
"システムでネットワークの有効化にエラーが発生しました。"

#: pyanaconda/yuminstall.py:833 pyanaconda/yuminstall.py:835
msgid "Re_boot"
msgstr "再起動(_B)"

#: pyanaconda/yuminstall.py:833
msgid "_Eject"
msgstr "ディスクを取り出す (_E)"

#: pyanaconda/yuminstall.py:839
#, python-format
msgid ""
"The file %s cannot be opened.  This is due to a missing file, a corrupt "
"package or corrupt media.  Please verify your installation source.\n"
"\n"
"If you exit, your system will be left in an inconsistent state that will "
"likely require reinstallation.\n"
"\n"
msgstr ""
"ファイル %s を開けません。ファイルが見つからないか、パッケージやメディアが破"
"損している可能性があります。インストール元を検証してください。\n"
"\n"
"終了するとシステムは矛盾した状態となり、再インストールを必要とする可能性が高"
"くなります。\n"
"\n"

#: pyanaconda/yuminstall.py:887
msgid "Retrying"
msgstr "再試行中"

#: pyanaconda/yuminstall.py:887
msgid "Retrying download."
msgstr "ダウンロードの再試行中。"

#: pyanaconda/yuminstall.py:952
#, python-format
msgid ""
"There was an error running your transaction for the following reason: %s\n"
msgstr "トランザクションの実行中に次のような理由でエラーが発生しました。%s\n"

#: pyanaconda/yuminstall.py:995 pyanaconda/yuminstall.py:996
msgid "file conflicts"
msgstr "ファイル競合"

#: pyanaconda/yuminstall.py:997
msgid "older package(s)"
msgstr "旧パッケージ"

#: pyanaconda/yuminstall.py:998
msgid "insufficient disk space"
msgstr "ディスク容量の不足"

#: pyanaconda/yuminstall.py:999
msgid "insufficient disk inodes"
msgstr "ディスク inode の不足"

#: pyanaconda/yuminstall.py:1000
msgid "package conflicts"
msgstr "パッケージ競合"

#: pyanaconda/yuminstall.py:1001
msgid "package already installed"
msgstr "パッケージは既にインストールされています"

#: pyanaconda/yuminstall.py:1002
msgid "required package"
msgstr "必要なパッケージ"

#: pyanaconda/yuminstall.py:1003
msgid "package for incorrect arch"
msgstr "不適切なアーキテクチャ用のパッケージ"

#: pyanaconda/yuminstall.py:1004
msgid "package for incorrect os"
msgstr "不適切な OS 用のパッケージ"

#: pyanaconda/yuminstall.py:1018
msgid "You need more space on the following file systems:\n"
msgstr "以下のファイルシステムは容量を増やす必要があります。\n"

#: pyanaconda/yuminstall.py:1031
#, python-format
msgid ""
"There were file conflicts when checking the packages to be installed:\n"
"%s\n"
msgstr ""
"インストールするパッケージに、競合するファイルがみつかりました:\n"
"%s\n"

#: pyanaconda/yuminstall.py:1034
#, python-format
msgid ""
"There was an error running your transaction for the following reason(s): "
"%s.\n"
msgstr "トランザクションの実行中に次のような理由でエラーが発生しました: %s\n"

#: pyanaconda/yuminstall.py:1041 pyanaconda/yuminstall.py:1046
msgid "Error Running Transaction"
msgstr "トランザクション実行中にエラーが発生しました。"

#: pyanaconda/yuminstall.py:1226
msgid ""
"Unable to read group information from repositories.  This is a problem with "
"the generation of your install tree."
msgstr ""
"リポジトリーからグループ情報を読み取ることはできません。これは、インストール"
"ツリーの生成の問題です。"

#: pyanaconda/yuminstall.py:1275 pyanaconda/textw/constants_text.py:64
msgid "Edit"
msgstr "編集"

#: pyanaconda/yuminstall.py:1286 pyanaconda/yuminstall.py:1477
#, python-format
msgid ""
"Unable to read package metadata. This may be due to a missing repodata "
"directory.  Please ensure that your install tree has been correctly "
"generated.\n"
"\n"
"%s"
msgstr ""
"パッケージのメタデータを読めません。repodata ディレクトリーが見つからないのが"
"原因かもしれません。インストールツリーが正しく構築されているか確認してくださ"
"い。\n"
"\n"
"%s"

#: pyanaconda/yuminstall.py:1455
msgid ""
"Some of the packages you have selected for install are missing "
"dependencies.  You can exit the installation, go back and change your "
"package selections, or continue installing these packages without their "
"dependencies.  If you continue, these packages may not work correctly due to "
"missing components."
msgstr ""
"インストールするために選択したパッケージの一部は依存関係が欠如しています。 イ"
"ンストールを終了してパッケージ選択に戻るか、又は依存関係のないパッケージの イ"
"ンストールを継続してください。継続する場合、欠如したコンポーネントのために こ"
"れらのパッケージは正常に機能しない可能性があります。"

#: pyanaconda/yuminstall.py:1499
#, python-format
msgid ""
"Your selected packages require %d MB of free space for installation, but you "
"do not have enough available.  You can change your selections or exit the "
"installer."
msgstr ""
"選択したパッケージはインストールに %d MB の空き領域を必要としますが、充分な空"
"きがありません。選択を変更するか、またはインストーラーを終了してください。"

#: pyanaconda/yuminstall.py:1520
msgid "Reboot?"
msgstr "再起動しますか?"

#: pyanaconda/yuminstall.py:1521
msgid "The system will be rebooted now."
msgstr "システムが再起動します。"

#: pyanaconda/yuminstall.py:1663
#, python-format
msgid ""
"You appear to be upgrading from a system which is too old to upgrade to this "
"version of %s.  Are you sure you wish to continue the upgrade process?"
msgstr ""
"%s のこのバージョンにアップグレードを行うには古過ぎるシステムからアップグレー"
"トしているようです。本当にこのアップグレードのプロセスを続行しますか?"

#: pyanaconda/yuminstall.py:1698
#, python-format
msgid ""
"The arch of the release of %(productName)s you are upgrading to appears to "
"be %(myarch)s which does not match your previously installed arch of "
"%(arch)s.  This is likely to not succeed.  Are you sure you wish to continue "
"the upgrade process?"
msgstr ""
"アップグレードしようとしている %(productName)s のリリースパッケージのアーキテ"
"クチャは %(myarch)s で、既にインストールされているパッケージのアーキテク"
"チャ、%(arch)s と一致しません。この状況では、インストールに失敗するかもしれま"
"せん。本当にこのアップグレードプロセスを続行しますか?"

#: pyanaconda/yuminstall.py:1745
msgid "Post Upgrade"
msgstr "アップグレード後"

#: pyanaconda/yuminstall.py:1746
msgid "Performing post-upgrade configuration"
msgstr "アップグレード後の設定を実行中。"

#: pyanaconda/yuminstall.py:1748
msgid "Post Installation"
msgstr "インストール後"

#: pyanaconda/yuminstall.py:1749
msgid "Performing post-installation configuration"
msgstr "インストール後の設定を実行中"

#: pyanaconda/yuminstall.py:1990
msgid "Installation Starting"
msgstr "インストールを開始しています"

#: pyanaconda/yuminstall.py:1991
msgid "Starting installation process"
msgstr "インストール処理の開始"

#: pyanaconda/yuminstall.py:2029
msgid "Dependency Check"
msgstr "依存関係チェック"

#: pyanaconda/yuminstall.py:2030
msgid "Checking dependencies in packages selected for installation"
msgstr "インストール対象パッケージの依存関係をチェック中。"

#: pyanaconda/yuminstall.py:2086 pyanaconda/yuminstall.py:2102
msgid "Retrieving installation information."
msgstr "インストール情報を読み出し中。"

#: pyanaconda/yuminstall.py:2088 pyanaconda/yuminstall.py:2104
#, python-format
msgid "Retrieving installation information for %s."
msgstr "%s に関するインストール情報を読み出し中。"

#: pyanaconda/yuminstall.py:2089 pyanaconda/yuminstall.py:2105
msgid "Installation Progress"
msgstr "インストールの進捗"

#: pyanaconda/installclasses/fedora.py:38
msgid "_Fedora"
msgstr "Fedora(_F)"

#: pyanaconda/installclasses/fedora.py:39
#, python-format
msgid ""
"The default installation of %s includes a set of software applicable for "
"general internet usage. You can optionally select a different set of "
"software now."
msgstr ""
"%s のデフォルトインストールには一般的なネットワーク環境で利用できるソフトウェ"
"アのセットが含まれています。オプションとして異なる組み合わせのソフトウェアを"
"選択することができます。"

#: pyanaconda/installclasses/fedora.py:48
msgid "Graphical Desktop"
msgstr "デスクトップ"

#: pyanaconda/installclasses/fedora.py:53
msgid "Software Development"
msgstr "ソフトウェア開発"

#: pyanaconda/installclasses/fedora.py:59
msgid "Web Server"
msgstr "Web サーバー"

#: pyanaconda/installclasses/fedora.py:63 pyanaconda/installclasses/rhel.py:44
msgid "Minimal"
msgstr "最小限"

#: pyanaconda/installclasses/rhel.py:33
msgid "Red Hat Enterprise Linux"
msgstr "Red Hat Enterprise Linux"

#: pyanaconda/installclasses/rhel.py:34
#, python-format
msgid ""
"The default installation of %s is a minimum install. You can optionally "
"select a different set of software now."
msgstr ""
"%s のデフォルトインストールは最小限インストールです。オプションとして追加のソ"
"フトウェアを選択することができます。"

#: pyanaconda/iw/GroupSelector.py:147
#, python-format
msgid "Packages in %s"
msgstr "%s に含まれるパッケージ"

#: pyanaconda/iw/GroupSelector.py:433
#, python-format
msgid "Optional packages selected: %(inst)d of %(cnt)d"
msgstr "オプションパッケージが選択されました: %(cnt)d 個内の %(inst)d 個 "

#: pyanaconda/iw/GroupSelector.py:435
#, python-format
msgid "<i>%s</i>"
msgstr "<i>%s</i>"

#: pyanaconda/iw/GroupSelector.py:495
msgid "Uncategorized"
msgstr "カテゴリなし"

#: pyanaconda/iw/account_gui.py:52
msgid "Root _Password:"
msgstr "root パスワード(_P):"

#: pyanaconda/iw/account_gui.py:54
msgid "_Confirm:"
msgstr "確認 (_C):"

#: pyanaconda/iw/account_gui.py:92
msgid "Caps Lock is on."
msgstr "Caps Lock がオンになっています。"

#: pyanaconda/iw/account_gui.py:102 pyanaconda/iw/account_gui.py:110
#: pyanaconda/iw/account_gui.py:117 pyanaconda/iw/account_gui.py:138
#: pyanaconda/textw/userauth_text.py:74
msgid "Error with Password"
msgstr "パスワードにエラー"

#: pyanaconda/iw/account_gui.py:103
msgid ""
"You must enter your root password and confirm it by typing it a second time "
"to continue."
msgstr ""
"続行するには、 root パスワードを入力してから、もう一度同じパスワードを入力し"
"て確認しなければなりません。"

#: pyanaconda/iw/account_gui.py:111
msgid "The passwords you entered were different.  Please try again."
msgstr "入力したパスワードが異ります。やり直してください。"

#: pyanaconda/iw/account_gui.py:118
msgid "The root password must be at least six characters long."
msgstr "root パスワードは最低 6 文字以上でなければなりません。"

#: pyanaconda/iw/account_gui.py:127 pyanaconda/textw/userauth_text.py:83
msgid "Weak Password"
msgstr "パスワードが弱すぎます。"

#: pyanaconda/iw/account_gui.py:128
#, python-format
msgid "You have provided a weak password: %s"
msgstr "あなたは弱いパスワードを与えています: %s"

#: pyanaconda/iw/account_gui.py:131
msgid "_Use Anyway"
msgstr "常に使用する (_U)"

#: pyanaconda/iw/account_gui.py:139 pyanaconda/textw/userauth_text.py:75
msgid ""
"Requested password contains non-ASCII characters, which are not allowed."
msgstr ""
"要求されたパスワードには、パスワードに使用できない非 ASCII 文字が含まれていま"
"す。"

#: pyanaconda/iw/advanced_storage.py:87
msgid "You must select a NIC to use."
msgstr "使用する NIC を選択する必要があります。"

#: pyanaconda/iw/advanced_storage.py:132
msgid "Invalid Initiator Name"
msgstr "無効なイニシエーター名です"

#: pyanaconda/iw/advanced_storage.py:133
msgid "You must provide an initiator name."
msgstr "イニシエーター名を入力しなければなりません。"

#: pyanaconda/iw/advanced_storage.py:162
msgid "Error with Data"
msgstr "データにエラー発生"

#: pyanaconda/iw/autopart_type.py:96
msgid ""
"No partitions are available to resize.  Only physical partitions with "
"specific filesystems can be resized."
msgstr ""
"リサイズできるパーティションがありません。特定のファイルシステムでフォーマッ"
"トされた、物理パーティションのみリサイズできます。"

#: pyanaconda/iw/autopart_type.py:119
msgid "Resize FileSystem Error"
msgstr "ファイルシステムリサイズエラー"

#: pyanaconda/iw/autopart_type.py:120
#, python-format
msgid "%(device)s: %(msg)s"
msgstr "%(device)s: %(msg)s"

#: pyanaconda/iw/autopart_type.py:129
msgid "Resize Device Error"
msgstr "デバイスリサイズエラー"

#: pyanaconda/iw/autopart_type.py:130
#, python-format
msgid "%(name)s: %(msg)s"
msgstr "%(name)s: %(msg)s"

#: pyanaconda/iw/autopart_type.py:250
msgid "Use All Space"
msgstr "すべての領域を使用する"

#: pyanaconda/iw/autopart_type.py:252
msgid ""
"Removes all partitions on the selected device(s).  This includes partitions "
"created by other operating systems.\n"
"\n"
"<b>Tip:</b> This option will remove data from the selected device(s).  Make "
"sure you have backups."
msgstr ""
"選択したデバイス上のすべてのパーティションを削除します。これには、他のオペ"
"レーティングシステムで作成されたパーティションも含まれます。\n"
"\n"
"<b>注意:</b>このオプションは選択したデバイスからデータを削除します。バック"
"アップがあることを確認してください。"

#: pyanaconda/iw/autopart_type.py:258
msgid "Replace Existing Linux System(s)"
msgstr "既存の Linux システムを入れ替える"

#: pyanaconda/iw/autopart_type.py:260
msgid ""
"Removes all Linux partitions on the selected device(s). This does not remove "
"other partitions you may have on your storage device(s) (such as VFAT or "
"FAT32).\n"
"\n"
"<b>Tip:</b> This option will remove data from the selected device(s).  Make "
"sure you have backups."
msgstr ""
"選択したデバイス上の全ての Linux のパーティションを削除します。これは、スト"
"レージデバイス上にすでに存在する他のパーティションは削除しません。\n"
"\n"
"<b>注意:</b> このオプションは、選択したデバイスからデータを削除します。バック"
"アップがあることを確認して下さい。"

#: pyanaconda/iw/autopart_type.py:268
msgid "Shrink Current System"
msgstr "現在のシステムを縮小する"

#: pyanaconda/iw/autopart_type.py:270
msgid ""
"Shrinks existing partitions to create free space for the default layout."
msgstr ""
"現在すでに存在するパーティションを縮小してデフォルトレイアウト用に空き領域を"
"作成します。"

#: pyanaconda/iw/autopart_type.py:272
msgid "Use Free Space"
msgstr "空き領域を使用する"

#: pyanaconda/iw/autopart_type.py:274
msgid ""
"Retains your current data and partitions and uses only the unpartitioned "
"space on the selected device(s), assuming you have enough free space "
"available."
msgstr ""
"現在のデータとパーティションを維持して、選択したデバイスに十分な空き領域があ"
"る場合は、その未設定領域のみを使用します。"

#: pyanaconda/iw/autopart_type.py:278
msgid "Create Custom Layout"
msgstr "カスタムレイアウトを作成する"

#: pyanaconda/iw/autopart_type.py:280
msgid ""
"Manually create your own custom layout on the selected device(s) using our "
"partitioning tool."
msgstr ""
"パーティション設定ツールを使用して選択したデバイス上に手動で個人設定のカスタ"
"ムレイアウトを 作成します。"

#: pyanaconda/iw/blpasswidget.py:44
msgid "_Use a boot loader password"
msgstr "ブートローダーパスワードを使用(_U)"

#: pyanaconda/iw/blpasswidget.py:45
msgid ""
"A boot loader password prevents users from changing kernel options, "
"increasing security."
msgstr ""
"ブートローダーパスワードによって、ユーザがカーネルオプションを変更してしまう"
"のを防ぎ、より高度なシステムセキュリティを確保します。"

#: pyanaconda/iw/blpasswidget.py:76
msgid "Change _password"
msgstr "パスワードを変更(_P)"

#: pyanaconda/iw/blpasswidget.py:99
msgid "Enter Boot Loader Password"
msgstr "ブートローダーパスワードを入力"

#: pyanaconda/iw/blpasswidget.py:105
msgid ""
"Enter a boot loader password and then confirm it.  (Note that your BIOS "
"keymap may be different than the actual keymap you are used to.)"
msgstr ""
"ブートローダーのパスワードを入力してからそのパスワードの確認をしてください。"
"(BIOS のキーマップが実際に使用しているキーマップとは異なっている可能性がある"
"ので注意してください)"

#: pyanaconda/iw/blpasswidget.py:112
msgid "_Password:"
msgstr "パスワード(_P):"

#: pyanaconda/iw/blpasswidget.py:118
msgid "Con_firm:"
msgstr "確認(_F):"

#: pyanaconda/iw/blpasswidget.py:139
msgid "Passwords don't match"
msgstr "パスワードが一致しません"

#: pyanaconda/iw/blpasswidget.py:140
msgid "Passwords do not match"
msgstr "パスワードが一致しません"

#: pyanaconda/iw/blpasswidget.py:149
msgid ""
"Your boot loader password is shorter than six characters.  We recommend a "
"longer boot loader password.\n"
"\n"
"Would you like to continue with this password?"
msgstr ""
"ブートローダーパスワードが 6 文字未満になっています。ブートローダーのパスワー"
"ドはこれより長くすることを推奨します。\n"
"\n"
"このパスワードで続行しますか?"

#: pyanaconda/iw/bootloader_main_gui.py:36
msgid "Boot Loader Configuration"
msgstr "ブートローダーの設定"

#: pyanaconda/iw/bootloader_main_gui.py:180
#: pyanaconda/iw/bootloader_main_gui.py:185
#: pyanaconda/iw/bootloader_main_gui.py:223
#, python-format
msgid "_Install boot loader on /dev/%s."
msgstr "ブートローダーを /dev/%s にインストールする。 (_I)"

#: pyanaconda/iw/bootloader_main_gui.py:229
msgid "_Change device"
msgstr "デバイスの変更 (_C)"

#: pyanaconda/iw/cleardisks_gui.py:34
msgid "Clear Disks Selector"
msgstr "ディスクセレクタを空にする"

#: pyanaconda/iw/cleardisks_gui.py:45 pyanaconda/iw/filter_gui.py:432
msgid "You must select at least one drive to be used for installation."
msgstr ""
"インストール用に少なくともハードディスクを 1 つ選択しなければなりません。"

#: pyanaconda/iw/cleardisks_gui.py:55
msgid "You must select one drive to boot from."
msgstr "ブート元のドライブをを１つ選択する必要があります。"

#: pyanaconda/iw/cleardisks_gui.py:127 pyanaconda/iw/cleardisks_gui.py:147
#: pyanaconda/iw/filter_gui.py:489 pyanaconda/iw/filter_gui.py:500
#: pyanaconda/iw/filter_gui.py:530
msgid "Model"
msgstr "モデル"

#: pyanaconda/iw/cleardisks_gui.py:128 pyanaconda/iw/cleardisks_gui.py:148
#: pyanaconda/iw/filter_gui.py:490 pyanaconda/iw/filter_gui.py:501
#: pyanaconda/iw/filter_gui.py:509 pyanaconda/iw/filter_gui.py:520
#: pyanaconda/iw/filter_gui.py:531
msgid "Capacity"
msgstr "容量"

#: pyanaconda/iw/cleardisks_gui.py:129 pyanaconda/iw/filter_gui.py:491
#: pyanaconda/iw/filter_gui.py:510 pyanaconda/iw/filter_gui.py:521
#: pyanaconda/iw/filter_gui.py:532
msgid "Vendor"
msgstr "ベンダー"

#: pyanaconda/iw/cleardisks_gui.py:130 pyanaconda/iw/cleardisks_gui.py:149
#: pyanaconda/iw/filter_gui.py:508 pyanaconda/iw/filter_gui.py:519
#: pyanaconda/iw/filter_gui.py:535
msgid "Identifier"
msgstr "識別子"

#: pyanaconda/iw/cleardisks_gui.py:131 pyanaconda/iw/filter_gui.py:492
#: pyanaconda/iw/filter_gui.py:511 pyanaconda/iw/filter_gui.py:522
#: pyanaconda/iw/filter_gui.py:533
msgid "Interconnect"
msgstr "相互接続"

#: pyanaconda/iw/cleardisks_gui.py:145
msgid ""
"Boot\n"
"Loader"
msgstr ""
"ブート\n"
" ローダー"

#: pyanaconda/iw/cleardisks_gui.py:196
msgid ""
"<b>Tip:</b> All Linux filesystems on the install target devices will be "
"reformatted and wiped of any data.  Make sure you have backups."
msgstr ""
"<b>ヒント:</b> インストール先のデバイス上にある全ての Linux ファイルシステム"
"は再フォーマットされてデータは抹消されます。バックアップがあることを確認して"
"下さい。"

#: pyanaconda/iw/cleardisks_gui.py:198
msgid ""
"<b>Tip:</b> The install target devices will be reformatted and wiped of any "
"data.  Make sure you have backups."
msgstr ""
"<b>ヒント:</b> インストール先のデバイスは再フォーマットされてデータは抹消され"
"ます。バックアップがあることを確認して下さい。"

#: pyanaconda/iw/cleardisks_gui.py:200
msgid ""
"<b>Tip:</b> Your filesystems on the install target devices will not be "
"reformatted unless you choose to do so during customization."
msgstr ""
"<b>ヒント:</b> インストール先のデバイス上にあるファイルシステムは、カスタマイ"
"ズ中に再フォーマットの選択をしていない限りは再フォーマットされません。"

#: pyanaconda/iw/congrats_gui.py:33
msgid "Congratulations"
msgstr "おめでとうございます"

#: pyanaconda/iw/congrats_gui.py:74 pyanaconda/textw/complete_text.py:39
#, python-format
msgid ""
"Congratulations, your %s installation is complete.\n"
"\n"
msgstr ""
"おめでとうございます。 %s のインストールは完了しました。\n"
"\n"

#: pyanaconda/iw/congrats_gui.py:77 pyanaconda/textw/complete_text.py:42
msgid "Shutdown"
msgstr "シャットダウン"

#: pyanaconda/iw/congrats_gui.py:79 pyanaconda/textw/complete_text.py:44
msgid "Please shutdown to use the installed system.\n"
msgstr "インストールしたシステムを使用するにはシャットダウンして下さい \n"

#: pyanaconda/iw/congrats_gui.py:81 pyanaconda/textw/complete_text.py:46
msgid "Please reboot to use the installed system.\n"
msgstr "インストール済のシステムを使用するには再起動して下さい。\n"

#: pyanaconda/iw/congrats_gui.py:86 pyanaconda/textw/complete_text.py:51
msgid ""
"Note that updates may be available to ensure the proper functioning of your "
"system and installation of these updates is recommended after the reboot."
msgstr ""
"ご使用のシステムの正常な機能を確実にするために更新が利用できる可能性があり、 "
"再起動の後にこの更新が推奨されることに注意して下さい。"

#: pyanaconda/iw/congrats_gui.py:90 pyanaconda/textw/complete_text.py:55
#, python-format
msgid ""
"Congratulations, your %s installation is complete.\n"
"\n"
"Please reboot to use the installed system.  Note that updates may be "
"available to ensure the proper functioning of your system and installation "
"of these updates is recommended after the reboot."
msgstr ""
"おめでとうございます。%s のインストールが完了しました。\n"
"\n"
"インストールしたシステムを使用するために再起動してください。ご使用のシステム"
"の機能が正常な動作を行うために更新パッケージが提供されている可能性がありま"
"す。再起動の後にパッケージのアップデートを行うことが推奨されています。"

#: pyanaconda/iw/examine_gui.py:39
msgid "Upgrade Examine"
msgstr "アップグレードテスト"

#: pyanaconda/iw/examine_gui.py:58
msgid "Fresh Installation"
msgstr "新規インストール"

#: pyanaconda/iw/examine_gui.py:60
#, python-format
msgid ""
"Choose this option to install a fresh copy of %s on your system.  Existing "
"software and data may be overwritten depending on your configuration choices."
msgstr ""
"システムに %s を新規インストールするにはこのオプションを選択します。既存のソ"
"フトウェアやデータは選択した設定によっては上書きされるかもしれません。"

#: pyanaconda/iw/examine_gui.py:65
msgid "Upgrade an Existing Installation"
msgstr "既存インストールのアップグレード"

#: pyanaconda/iw/examine_gui.py:67
#, python-format
msgid ""
"Choose this option if you would like to upgrade your existing %s system.  "
"This option will preserve the existing data on your storage device(s)."
msgstr ""
"既存の %s システムをアップグレードする場合に、このオプションを選択します。 こ"
"のオプションはストレージデバイス上の既存データを保持します。"

#: pyanaconda/iw/examine_gui.py:117
msgid ""
"At least one existing installation has been detected on your system.  What "
"would you like to do?"
msgstr ""
"現在お使いのシステム上には既存のシステムがインストールされています。どのよう"
"になさいますか?"

#: pyanaconda/iw/examine_gui.py:136
#, python-format
msgid "<b>Which %s installation would you like to upgrade?</b>"
msgstr "<b>どちらの %s をアップグレードしますか?</b>"

#: pyanaconda/iw/examine_gui.py:150
msgid "Unknown Linux system"
msgstr "不明な Linux システム"

#: pyanaconda/iw/filter_gui.py:150
#, python-format
msgid "Selected devices: %s (%s MB) out of %s (%s MB)."
msgstr "選択したデバイス: %s (%s MB) の内の %s (%s MB) "

#: pyanaconda/iw/filter_gui.py:400
msgid "Device Filter"
msgstr "デバイスフィルター"

#: pyanaconda/iw/filter_gui.py:493 pyanaconda/iw/filter_gui.py:523
#: pyanaconda/iw/filter_gui.py:534
msgid "Serial Number"
msgstr "シリアル番号"

#: pyanaconda/iw/filter_gui.py:494 pyanaconda/iw/filter_gui.py:502
#: pyanaconda/iw/filter_gui.py:513 pyanaconda/iw/filter_gui.py:524
#: pyanaconda/iw/filter_gui.py:539 pyanaconda/iw/osbootwidget.py:66
#: pyanaconda/iw/partition_gui.py:611
msgid "Device"
msgstr "デバイス"

#: pyanaconda/iw/filter_gui.py:512
msgid "Paths"
msgstr "パス"

#: pyanaconda/iw/filter_gui.py:536
msgid "Port"
msgstr "ポート"

#: pyanaconda/iw/filter_gui.py:537
msgid "Target"
msgstr "ターゲット"

#: pyanaconda/iw/filter_gui.py:538
msgid "LUN"
msgstr "LUN"

#: pyanaconda/iw/filter_type.py:55
msgid "What type of devices will your installation involve?"
msgstr "どちらのタイプのストレージデバイスにインストールしますか?"

#: pyanaconda/iw/filter_type.py:61
msgid "Basic Storage Devices"
msgstr "基本ストレージデバイス"

#: pyanaconda/iw/filter_type.py:62
msgid ""
"Installs or upgrades to typical types of storage devices.  If you're not "
"sure which option is right for you, this is probably it."
msgstr ""
"一般的なストレージデバイスにインストール、またはアップグレードします。 どのオ"
"プションが正しいのか不明な場合は、これが適切でしょう。"

#: pyanaconda/iw/filter_type.py:66
msgid "Specialized Storage Devices"
msgstr "エンタープライズストレージデバイス"

#: pyanaconda/iw/filter_type.py:67
msgid ""
"Installs or upgrades to enterprise devices such as Storage Area Networks "
"(SANs). This option will allow you to add FCoE / iSCSI / zFCP disks and to "
"filter out devices the installer should ignore."
msgstr ""
"SANs (Storage Area Networks) などのエンタープライズストレージデバイスにインス"
"トールするか、 またはアップグレードします。このオプションにより、FCoE / "
"iSCSI / zFCP などのストレージデバイスを追加でき、インストーラが無視すべきデバ"
"イスを選別します。"

#: pyanaconda/iw/language_gui.py:33 pyanaconda/textw/language_text.py:45
msgid "Language Selection"
msgstr "言語の選択"

#: pyanaconda/iw/language_gui.py:81 loader/lang.c:371
#: pyanaconda/textw/language_text.py:46
msgid "What language would you like to use during the installation process?"
msgstr "インストール時に使用する言語を選択してください。"

#: pyanaconda/iw/lvm_dialog_gui.py:126 pyanaconda/iw/lvm_dialog_gui.py:172
#: pyanaconda/iw/lvm_dialog_gui.py:186 pyanaconda/iw/lvm_dialog_gui.py:225
#: pyanaconda/iw/lvm_dialog_gui.py:302 pyanaconda/iw/lvm_dialog_gui.py:697
#: pyanaconda/iw/lvm_dialog_gui.py:718
msgid "Not enough space"
msgstr "容量が足りません"

#: pyanaconda/iw/lvm_dialog_gui.py:127
msgid ""
"The physical extent size cannot be changed because otherwise the space "
"required by the currently defined logical volumes will be increased to more "
"than the available space."
msgstr ""
"物理エクステントサイズは変更できません。変更すると現在定義されている論理ボ"
"リュームが必要とする領域が使用可能な領域以上に増加してしまうためです。"

#: pyanaconda/iw/lvm_dialog_gui.py:136
msgid "Confirm Physical Extent Change"
msgstr "物理エクステントの変更を確認"

#: pyanaconda/iw/lvm_dialog_gui.py:137
msgid ""
"This change in the value of the physical extent will require the sizes of "
"the current logical volume requests to be rounded up in size to an integer "
"multiple of the physical extent.\n"
"\n"
"This change will take effect immediately."
msgstr ""
"この物理エクステントの値の変更により、現在の論理ボリューム要求サイズを物理エ"
"クステントの整数倍に切り上げる必要があります。\n"
"\n"
"この変更は直ちに反映されます。"

#: pyanaconda/iw/lvm_dialog_gui.py:146 pyanaconda/iw/lvm_dialog_gui.py:208
msgid "C_ontinue"
msgstr "続行 (_O)"

#: pyanaconda/iw/lvm_dialog_gui.py:173
#, python-format
msgid ""
"The physical extent size cannot be changed because the value selected "
"(%(curpe)10.2f MB) is larger than the smallest physical volume "
"(%(maxpvsize)10.2f MB) in the volume group."
msgstr ""
"物理エクステントのサイズは変更できません。選択された値 (%(curpe)10.2f MB) が"
"ボリュームグループ内の最小物理ボリューム (%(maxpvsize)10.2f MB) よりも大きい"
"ためです。"

#: pyanaconda/iw/lvm_dialog_gui.py:187
#, python-format
msgid ""
"The physical extent size cannot be changed because the value selected "
"(%(curpe)10.2f MB) is too large compared to the size of the smallest "
"physical volume (%(maxpvsize)10.2f MB) in the volume group."
msgstr ""
"物理エクステントのサイズを変更することはできません。ボリュームグループ内の最"
"小物理ボリューム (%(maxpvsize)10.2f MB) のサイズと比較して、選択された値 "
"(%(curpe)10.2f MB) が大きすぎるためです。"

#: pyanaconda/iw/lvm_dialog_gui.py:201
msgid "Too small"
msgstr "小さすぎます"

#: pyanaconda/iw/lvm_dialog_gui.py:202
msgid ""
"This change in the value of the physical extent will waste substantial space "
"on one or more of the physical volumes in the volume group."
msgstr ""
"物理エクステントの値を変更すると、ボリュームグループ内の1つまたは複数の物理ボ"
"リュームの相当な領域を浪費することになります。"

#: pyanaconda/iw/lvm_dialog_gui.py:226
#, python-format
msgid ""
"The physical extent size cannot be changed because the resulting maximum "
"logical volume size (%10.2f MB) is smaller than one or more of the currently "
"defined logical volumes."
msgstr ""
"物理エクステントのサイズは変更できません。結果としてできる最大論理ボリューム"
"サイズ (%10.2f MB) が現在定義されている 1 つまたは複数の論理ボリュームよりも"
"小さくなるためです。"

#: pyanaconda/iw/lvm_dialog_gui.py:303
msgid ""
"You cannot remove this physical volume because otherwise the volume group "
"will be too small to hold the currently defined logical volumes."
msgstr ""
"この物理ボリュームは削除できません。削除すると現在定義されている論理ボリュー"
"ムを保持するにはボリュームグループが小さくなりすぎるためです。"

#: pyanaconda/iw/lvm_dialog_gui.py:402
msgid "Make Logical Volume"
msgstr "論理ボリュームを作成"

#: pyanaconda/iw/lvm_dialog_gui.py:404
#, python-format
msgid "Edit Logical Volume: %s"
msgstr "論理ボリュームを編集: %s"

#: pyanaconda/iw/lvm_dialog_gui.py:443 pyanaconda/iw/raid_dialog_gui.py:451
msgid "_File System Type:"
msgstr "ファイルシステムタイプ(_F):"

#: pyanaconda/iw/lvm_dialog_gui.py:449
msgid "_Logical Volume Name:"
msgstr "論理ボリューム名(_L):"

#: pyanaconda/iw/lvm_dialog_gui.py:458
#: pyanaconda/iw/partition_dialog_gui.py:492
msgid "_Size (MB):"
msgstr "サイズ (MB)(_S):"

#: pyanaconda/iw/lvm_dialog_gui.py:465
#, python-format
msgid "(Max size is %s MB)"
msgstr "(最大サイズは %s MB)"

#: pyanaconda/iw/lvm_dialog_gui.py:470
#: pyanaconda/iw/partition_dialog_gui.py:544
#: pyanaconda/iw/partition_ui_helpers_gui.py:337
#: pyanaconda/iw/raid_dialog_gui.py:423
msgid "_Encrypt"
msgstr "暗号化 (_E)"

#: pyanaconda/iw/lvm_dialog_gui.py:479
#: pyanaconda/iw/partition_dialog_gui.py:474
#: pyanaconda/iw/raid_dialog_gui.py:461
msgid "Original File System Type:"
msgstr "元のファイルシステムタイプ:"

#: pyanaconda/iw/lvm_dialog_gui.py:484
#: pyanaconda/iw/partition_dialog_gui.py:482
#: pyanaconda/iw/raid_dialog_gui.py:468
msgid "Original File System Label:"
msgstr "元のファイルシステムラベル:"

#: pyanaconda/iw/lvm_dialog_gui.py:489
msgid "Logical Volume Name:"
msgstr "論理ボリューム名:"

#: pyanaconda/iw/lvm_dialog_gui.py:493
msgid "Size (MB):"
msgstr "サイズ (MB):"

#: pyanaconda/iw/lvm_dialog_gui.py:520
#: pyanaconda/iw/partition_dialog_gui.py:430
#: pyanaconda/iw/raid_dialog_gui.py:442
msgid "_Mount Point:"
msgstr "マウントポイント(_M):"

#: pyanaconda/iw/lvm_dialog_gui.py:601
#: pyanaconda/iw/partition_dialog_gui.py:118
#: pyanaconda/iw/raid_dialog_gui.py:176
msgid "Mount Point Error"
msgstr "マウントポイントのエラー"

#: pyanaconda/iw/lvm_dialog_gui.py:611
msgid "Illegal Logical Volume Name"
msgstr "不適切な論理ボリューム名"

#: pyanaconda/iw/lvm_dialog_gui.py:626
msgid "Illegal logical volume name"
msgstr "不適切な論理ボリューム名"

#: pyanaconda/iw/lvm_dialog_gui.py:627
#, python-format
msgid "The logical volume name \"%s\" is already in use. Please pick another."
msgstr ""
"論理ボリューム名 \"%s\" はすでに使用中です。他の名前を選択してください。"

#: pyanaconda/iw/lvm_dialog_gui.py:668
#: pyanaconda/iw/partition_dialog_gui.py:133
#: pyanaconda/iw/raid_dialog_gui.py:191
msgid "Mount point in use"
msgstr "使用中のマウントポイント"

#: pyanaconda/iw/lvm_dialog_gui.py:669
#: pyanaconda/iw/partition_dialog_gui.py:134
#: pyanaconda/iw/raid_dialog_gui.py:192
#, python-format
msgid "The mount point \"%s\" is in use. Please pick another."
msgstr "マウントポイント \"%s\" は使用中です。他を選択してください。"

#: pyanaconda/iw/lvm_dialog_gui.py:684
msgid "Illegal size"
msgstr "不適切なサイズ"

#: pyanaconda/iw/lvm_dialog_gui.py:685
msgid "The requested size as entered is not a valid number greater than 0."
msgstr "入力された要求サイズは 0 より大きい有効な数値ではありません。"

#: pyanaconda/iw/lvm_dialog_gui.py:698
#, python-format
msgid ""
"The current requested size (%(size)10.2f MB) is larger than the maximum "
"logical volume size (%(maxlv)10.2f MB). To increase this limit you can "
"create more Physical Volumes from unpartitioned disk space and add them to "
"this Volume Group."
msgstr ""
"現在の要求サイズ (%(size)10.2f MB) は、最大論理ボリュームサイズ "
"(%(maxlv)10.2f MB) より大きくなります。この上限を増やすには、パーティションが"
"未設定のディスク領域から物理ボリュームを作成し、それをこのボリュームグループ"
"に追加します。"

#: pyanaconda/iw/lvm_dialog_gui.py:719
#, python-format
msgid ""
"The size entered for this logical volume (%(size)d MB) combined with the "
"size of the other logical volume(s) exceeds the size of the volume group "
"(%(tempvgsize)d MB). Please make the volume group larger or make the logical "
"volume smaller."
msgstr ""
"この論理ボリュームに入力されたサイズ (%(size)d MB) は他の論理ボリュームのサイ"
"ズとの合計で ボリュームグループのサイズ (%(tempvgsize)d MB) を超過していま"
"す。ボリュームグループを 拡大するか、又は論理ボリュームを縮小して下さい。"

#: pyanaconda/iw/lvm_dialog_gui.py:829
msgid "No free slots"
msgstr "空きスロットがありません"

#: pyanaconda/iw/lvm_dialog_gui.py:830
#, python-format
msgid "You cannot create more than %d logical volume per volume group."
msgid_plural "You cannot create more than %d logical volumes per volume group."
msgstr[0] "ボリュームグループ毎に %d 以上の論理ボリュームは作成できません。"
msgstr[1] "ボリュームグループ毎に %d 以上の論理ボリュームは作成できません。"

#: pyanaconda/iw/lvm_dialog_gui.py:840
msgid "No free space"
msgstr "空き領域はありません"

#: pyanaconda/iw/lvm_dialog_gui.py:841
msgid ""
"There is no room left in the volume group to create new logical volumes. To "
"add a logical volume you must reduce the size of one or more of the "
"currently existing logical volumes"
msgstr ""
"新規の論理ボリュームを作成する空き領域がボリュームグループには残っていませ"
"ん。論理ボリュームを追加するには、ひとつ以上の既存の論理ボリュームのサイズを"
"縮小する必要があります。"

#: pyanaconda/iw/lvm_dialog_gui.py:878
#, python-format
msgid "Are you sure you want to delete the logical volume \"%s\"?"
msgstr "本当に論理ボリューム 「%s」 を削除しますか?"

#: pyanaconda/iw/lvm_dialog_gui.py:984
msgid "Invalid Volume Group Name"
msgstr "無効なボリュームグループ名"

#: pyanaconda/iw/lvm_dialog_gui.py:993
msgid "Name in use"
msgstr "名前は使用中です"

#: pyanaconda/iw/lvm_dialog_gui.py:994
#, python-format
msgid "The volume group name \"%s\" is already in use. Please pick another."
msgstr ""
"ボリュームグループ名 \"%s\" はすでに使用されています。別の名前を選択してくだ"
"さい。"

#: pyanaconda/iw/lvm_dialog_gui.py:1281
msgid "Not enough physical volumes"
msgstr "物理ボリュームが足りません"

#: pyanaconda/iw/lvm_dialog_gui.py:1282
msgid ""
"At least one unused physical volume partition is needed to create an LVM "
"Volume Group.\n"
"\n"
"Create a partition or RAID array of type \"physical volume (LVM)\" and then "
"select the \"LVM\" option again."
msgstr ""
"LVM ボリュームグループを作成するには、未使用の物理ボリュームパーティションが"
"少なくとも 1 つ必要です。\n"
"\n"
"「物理ボリューム (LVM)」タイプのパーティションまたは RAID アレイを作成してか"
"ら、 「LVM」 オプションを選択し直してください。"

#: pyanaconda/iw/lvm_dialog_gui.py:1293
msgid "Make LVM Volume Group"
msgstr "LVM ボリュームグループの作成"

#: pyanaconda/iw/lvm_dialog_gui.py:1296
#, python-format
msgid "Edit LVM Volume Group: %s"
msgstr "LVM ボリュームグループの編集: %s"

#: pyanaconda/iw/lvm_dialog_gui.py:1298
msgid "Edit LVM Volume Group"
msgstr "LVM ボリュームグループの編集"

#: pyanaconda/iw/lvm_dialog_gui.py:1314
msgid "_Volume Group Name:"
msgstr "ボリュームグループ名(_V):"

#: pyanaconda/iw/lvm_dialog_gui.py:1322
msgid "Volume Group Name:"
msgstr "ボリュームグループ名:"

#: pyanaconda/iw/lvm_dialog_gui.py:1330
msgid "_Physical Extent:"
msgstr "物理エクステント(_P): "

#: pyanaconda/iw/lvm_dialog_gui.py:1345
msgid "Physical Volumes to _Use:"
msgstr "使用する物理ボリューム(_U):"

#: pyanaconda/iw/lvm_dialog_gui.py:1351
msgid "Used Space:"
msgstr "使用中の領域:"

#: pyanaconda/iw/lvm_dialog_gui.py:1368
msgid "Free Space:"
msgstr "空き領域:"

#: pyanaconda/iw/lvm_dialog_gui.py:1386
msgid "Total Space:"
msgstr "合計領域:"

#: pyanaconda/iw/lvm_dialog_gui.py:1424
msgid "Logical Volume Name"
msgstr "論理ボリューム名"

#: pyanaconda/iw/lvm_dialog_gui.py:1427 pyanaconda/iw/partition_gui.py:614
#: pyanaconda/iw/upgrade_swap_gui.py:138 pyanaconda/textw/upgrade_text.py:124
msgid "Mount Point"
msgstr "マウントポイント"

#: pyanaconda/iw/lvm_dialog_gui.py:1430 pyanaconda/iw/partition_gui.py:613
msgid "Size (MB)"
msgstr "サイズ (MB)"

#: pyanaconda/iw/lvm_dialog_gui.py:1444 pyanaconda/iw/osbootwidget.py:96
msgid "_Add"
msgstr "追加(_A)"

#: pyanaconda/iw/lvm_dialog_gui.py:1447 pyanaconda/iw/osbootwidget.py:100
#: pyanaconda/iw/partition_gui.py:1811 pyanaconda/iw/partition_gui.py:1821
msgid "_Edit"
msgstr "編集(_E)"

#: pyanaconda/iw/lvm_dialog_gui.py:1462
msgid "_Logical Volumes"
msgstr "論理ボリューム (_L)"

#: pyanaconda/iw/netconfig_dialog.py:192 pyanaconda/textw/netconfig_text.py:36
#, python-format
msgid ""
"An error occurred converting the value entered for \"%(field)s\":\n"
"%(errmsg)s"
msgstr ""
"\"%(field)s\" に入力された値を変換中にエラーが発生:\n"
"%(errmsg)s"

#: pyanaconda/iw/netconfig_dialog.py:195 pyanaconda/iw/netconfig_dialog.py:204
#: pyanaconda/textw/netconfig_text.py:35 pyanaconda/textw/netconfig_text.py:42
msgid "Error With Data"
msgstr "データにエラーがあります"

#: pyanaconda/iw/netconfig_dialog.py:203
#, python-format
msgid "A value is required for the field %s."
msgstr "フィールド %s には値が必要です。"

#: pyanaconda/iw/netconfig_dialog.py:215
msgid "Error Configuring Network"
msgstr "ネットワーク設定中にエラー発生"

#: pyanaconda/iw/netconfig_dialog.py:241
msgid "Dynamic IP Address"
msgstr "動的 IP アドレス"

#: pyanaconda/iw/netconfig_dialog.py:242
#, python-format
msgid "Sending request for IP address information for %s"
msgstr "%s の IP アドレス情報の要求を送信中"

#: pyanaconda/iw/netconfig_dialog.py:257 pyanaconda/iw/netconfig_dialog.py:260
msgid "IP Address"
msgstr "IP アドレス"

#: pyanaconda/iw/netconfig_dialog.py:267
#: pyanaconda/textw/netconfig_text.py:290
msgid "IPv4 CIDR prefix must be between 0 and 32."
msgstr "IPv4 CIDR の接頭辞は 0 から 32 の間にしてください。"

#: pyanaconda/iw/netconfig_dialog.py:268 pyanaconda/iw/netconfig_dialog.py:274
#: pyanaconda/iw/netconfig_dialog.py:282 pyanaconda/iw/netconfig_dialog.py:285
msgid "IPv4 Network Mask"
msgstr "IPv4 ネットワークマスク"

#: pyanaconda/iw/netconfig_dialog.py:295
msgid "Gateway"
msgstr "ゲートウェイ"

#: pyanaconda/iw/netconfig_dialog.py:305
msgid "Nameserver"
msgstr "ネームサーバー"

#: pyanaconda/iw/netconfig_dialog.py:314
msgid "Error configuring network device:"
msgstr "ネットワークデバイス設定中にエラー発生:"

#: pyanaconda/iw/network_gui.py:83 pyanaconda/iw/network_gui.py:89
msgid "Error with Hostname"
msgstr "ホスト名にエラー発生"

#: pyanaconda/iw/network_gui.py:84
msgid "You must enter a valid hostname for this computer."
msgstr "このコンピュータ用の有効なホスト名を入力して下さい。"

#: pyanaconda/iw/network_gui.py:90
#, python-format
msgid ""
"The hostname \"%(hostname)s\" is not valid for the following reason:\n"
"\n"
"%(herrors)s"
msgstr ""
"ホスト名 \"%(hostname)s\" は、次のような理由で有効ではありません。\n"
"\n"
"%(herrors)s"

#: pyanaconda/iw/network_gui.py:134
msgid "Select network interface"
msgstr "ネットワークインターフェースを選択"

#: pyanaconda/iw/network_gui.py:141 data/ui/netconfig.glade.h:10
msgid ""
"This requires that you have an active network connection during the "
"installation process.  Please configure a network interface."
msgstr ""
"これを行うにはインストール中にアクティブなネットワーク接続が必要になります。"
"ネットワークインターフェースを設定してください。"

#: pyanaconda/iw/network_gui.py:211
msgid "Select APs"
msgstr "AP を選択"

#: pyanaconda/iw/network_gui.py:218
msgid "Select APs for wireless devices"
msgstr "無線デバイス用の AP を選択する"

#: pyanaconda/iw/osbootwidget.py:50
msgid "Boot loader operating system list"
msgstr "ブートローダーのオペレーティングシステムのリスト"

#: pyanaconda/iw/osbootwidget.py:66
msgid "Default"
msgstr "デフォルト"

#: pyanaconda/iw/osbootwidget.py:66 pyanaconda/iw/partition_gui.py:612
msgid "Label"
msgstr "ラベル"

#: pyanaconda/iw/osbootwidget.py:130
msgid "Image"
msgstr "イメージ"

#: pyanaconda/iw/osbootwidget.py:137
msgid ""
"Enter a label for the boot loader menu to display. The device (or hard drive "
"and partition number) is the device from which it boots."
msgstr ""
"ブートローダーメニューに表示されるラベルを入力します。デバイス(または、ハード"
"ドライブとパーティション番号)とは、起動用に使うデバイスのことです。"

#: pyanaconda/iw/osbootwidget.py:145
msgid "_Label"
msgstr "ラベル(_L)"

#: pyanaconda/iw/osbootwidget.py:153
msgid "_Device"
msgstr "デバイス(_D)"

#: pyanaconda/iw/osbootwidget.py:183
msgid "Default Boot _Target"
msgstr "デフォルトのブートターゲット(_T)"

#: pyanaconda/iw/osbootwidget.py:212
msgid "You must specify a label for the entry"
msgstr "ブートエントリのラベルを指定してください"

#: pyanaconda/iw/osbootwidget.py:221
msgid "Boot label contains illegal characters"
msgstr "ブートラベルに不適切な文字があります"

#: pyanaconda/iw/osbootwidget.py:245
msgid "Duplicate Label"
msgstr "ラベルが重複しています"

#: pyanaconda/iw/osbootwidget.py:246
msgid "This label is already in use for another boot entry."
msgstr "このラベルは既に別のブートエントリに使用されています。"

#: pyanaconda/iw/osbootwidget.py:259
msgid "Duplicate Device"
msgstr "デバイスが重複しています"

#: pyanaconda/iw/osbootwidget.py:260
msgid "This device is already being used for another boot entry."
msgstr "このデバイスは既に別のブートエントリに使用されています。"

#: pyanaconda/iw/osbootwidget.py:322
msgid "Cannot Delete"
msgstr "削除できません"

#: pyanaconda/iw/osbootwidget.py:323
#, python-format
msgid ""
"This boot target cannot be deleted because it is for the %s system you are "
"about to install."
msgstr ""
"このブートターゲットは、インストールしようとしている %s システム用になってい"
"るため削除できません。"

#: pyanaconda/iw/partition_dialog_gui.py:58
msgid "Additional Size Options"
msgstr "追加容量オプション"

#: pyanaconda/iw/partition_dialog_gui.py:63
msgid "_Fixed size"
msgstr "固定容量(_F)"

#: pyanaconda/iw/partition_dialog_gui.py:65
msgid "Fill all space _up to (MB):"
msgstr "指定限度まで使用(MB)(_U):"

#: pyanaconda/iw/partition_dialog_gui.py:72
msgid "Fill to maximum _allowable size"
msgstr "最大許容量まで使用(_A)"

#: pyanaconda/iw/partition_dialog_gui.py:191
msgid "Error With Request"
msgstr "要求にエラーがあります"

#: pyanaconda/iw/partition_dialog_gui.py:400
msgid "Add Partition"
msgstr "パーティションの追加"

#: pyanaconda/iw/partition_dialog_gui.py:402
#, python-format
msgid "Edit Partition: %s"
msgstr "パーティションの編集: %s"

#: pyanaconda/iw/partition_dialog_gui.py:439
msgid "File System _Type:"
msgstr "ファイルシステムタイプ(_T):"

#: pyanaconda/iw/partition_dialog_gui.py:455
msgid "Allowable _Drives:"
msgstr "使用可能なドライブ(_D):"

#: pyanaconda/iw/partition_dialog_gui.py:531
msgid "Force to be a _primary partition"
msgstr "基本パーティションにする(_P)"

#: pyanaconda/iw/partition_gui.py:360
#, python-format
msgid "Drive %(drive)s (%(size)-0.f MB) (Model: %(model)s)"
msgstr "ドライブ %(drive)s (%(size)-0.f MB) (モデル: %(model)s)"

#: pyanaconda/iw/partition_gui.py:400 pyanaconda/iw/partition_gui.py:446
#: pyanaconda/iw/partition_gui.py:513 pyanaconda/iw/partition_gui.py:998
#: pyanaconda/iw/partition_gui.py:1070
msgid "Free"
msgstr "空き"

#: pyanaconda/iw/partition_gui.py:478
#, python-format
msgid "LVM Volume Group %s (%-0.f MB)"
msgstr "LVM ボリュームグループ %s (%-0.f MB)"

#: pyanaconda/iw/partition_gui.py:544
#, python-format
msgid "MD RAID ARRAY %s (%-0.f MB)"
msgstr "MD RAID アレイ %s (%-0.f MB)"

#: pyanaconda/iw/partition_gui.py:615
msgid "Type"
msgstr "タイプ"

#: pyanaconda/iw/partition_gui.py:616 pyanaconda/storage/__init__.py:1817
msgid "Format"
msgstr "フォーマットする"

#: pyanaconda/iw/partition_gui.py:653
msgid ""
"Mount Point/\n"
"RAID/Volume"
msgstr ""
"マウントポイント/\n"
"RAID/ボリューム"

#: pyanaconda/iw/partition_gui.py:655
msgid ""
"Size\n"
"(MB)"
msgstr ""
"容量\n"
"(MB)"

#: pyanaconda/iw/partition_gui.py:760
msgid "Partitioning"
msgstr "パーティション設定"

#: pyanaconda/iw/partition_gui.py:850
msgid ""
"The partitioning scheme you requested caused the following critical errors."
msgstr ""
"あなたが要求したパーティション設定案は以下の重大なエラーを起こしました。"

#: pyanaconda/iw/partition_gui.py:852
#, python-format
msgid ""
"You must correct these errors before you continue your installation of %s."
msgstr ""
"%s のインストールを続行する前にこれらのエラーを修正する必要があります。"

#: pyanaconda/iw/partition_gui.py:858
msgid "Partitioning Errors"
msgstr "パーティション設定エラー"

#: pyanaconda/iw/partition_gui.py:865
msgid "The partitioning scheme you requested generated the following warnings."
msgstr "あなたが要求したパーティション設定案には以下の警告があります。"

#: pyanaconda/iw/partition_gui.py:867
msgid "Would you like to continue with your requested partitioning scheme?"
msgstr "このパーティション設定のまま続行しますか?"

#: pyanaconda/iw/partition_gui.py:872
msgid "Partitioning Warnings"
msgstr "パーティション設定の警告"

#: pyanaconda/iw/partition_gui.py:881
msgid ""
"The following pre-existing devices have been selected to be formatted, "
"destroying all data."
msgstr ""
"次の既存のデバイスをフォーマットするよう選択されています。これによりすべての"
"データが消去されます。"

#: pyanaconda/iw/partition_gui.py:893
msgid "Format Warnings"
msgstr "フォーマットの警告"

#: pyanaconda/iw/partition_gui.py:986
msgid "LVM Volume Groups"
msgstr "LVM ボリュームグループ"

#: pyanaconda/iw/partition_gui.py:1008
msgid "RAID Devices"
msgstr "RAID デバイス"

#: pyanaconda/iw/partition_gui.py:1024 loader/hdinstall.c:212
msgid "Hard Drives"
msgstr "ハードディスク"

#: pyanaconda/iw/partition_gui.py:1074
msgid "Extended"
msgstr "拡張領域"

#: pyanaconda/iw/partition_gui.py:1364
msgid "Cannot perform any creation action"
msgstr "作成作業を実行できません"

#: pyanaconda/iw/partition_gui.py:1365
msgid ""
"Note that the creation action requires one of the following:\n"
"\n"
"* Free space in one of the Hard Drives.\n"
"* At least two free Software RAID partitions.\n"
"* At least one free physical volume (LVM) partition.\n"
"* At least one Volume Group with free space."
msgstr ""
"作成作業には以下のいずれかが必要なことに注意して下さい:\n"
"\n"
"* ハードディスクの１つに空き領域。\n"
"* ソフトウェア RAID に最低 2つの空きパーティション。 \n"
"* 物理ボリューム (LVM) に最低１つの空きパーティション。\n"
"* 最低１つの空き領域を持つボリュームグループ。"

#: pyanaconda/iw/partition_gui.py:1468
#, python-format
msgid ""
"Software RAID allows you to combine several disks into a larger RAID "
"device.  A RAID device can be configured to provide additional speed and "
"reliability compared to using an individual drive.  For more information on "
"using RAID devices please consult the %s documentation.\n"
msgstr ""
"ソフトウェア RAID を使用すれば、複数のディスクを結合して 1 つの大きな RAID デ"
"バイスとすることができます。RAID デバイスは、個別のドライブ使用に比べ速度と信"
"頼性を高めるように設定することができます。RAID デバイスの詳細情報については "
"%s ドキュメントを参照してください。\n"

#: pyanaconda/iw/partition_gui.py:1474
msgid ""
"To use RAID you must first create at least two partitions of type 'software "
"RAID'.  Then you can create a RAID device that can be formatted and "
"mounted.\n"
"\n"
msgstr ""
"RAIDを使用するには、まず「ソフトウェア RAID」タイプのパーティションを少くと"
"も 2 つ作成する必要があります。そうすると、フォーマット及びマウントが可能な "
"RAID デバイスが作成できるようになります。\n"
"\n"

#: pyanaconda/iw/partition_gui.py:1478
#, python-format
msgid "You currently have %d software RAID partition free to use."
msgid_plural "You currently have %d software RAID partitions free to use."
msgstr[0] "%d 個のソフトウェア RAID パーティションの空き領域が使用できます。"
msgstr[1] "%d 個のソフトウェア RAID パーティションの空き領域が使用できます。"

#: pyanaconda/iw/partition_gui.py:1482
msgid "About RAID"
msgstr "RAID について"

#: pyanaconda/iw/partition_gui.py:1488
#, python-format
msgid ""
"Logical Volume Manager (LVM) is a 3 level construct. The first level is made "
"up of disks or partitions formatted with LVM metadata called Physical "
"Volumes (PV).  A Volume Group (VG) sits on top of one or more PVs. The VG, "
"in turn, is the base to create one or more Logical Volumes (LV).  Note that "
"a VG can be an aggregate of PVs from multiple physical disks.  For more "
"information on using LVM please consult the %s documentation\n"
msgstr ""
"LVM (Logical Volume Manager) は３レベル構造になっています。最初のレベルは "
"LVM メタデータでフォーマットされた物理ボリューム (PV) と呼ばれるディスク、又"
"はパーティションの集合です。ボリュームグループ (VG) は単数、又は複数の PV か"
"ら構成されます。そして次には VG が単数、又は複数の論理ボリューム (LV) を構成"
"する土台となります。VG は複数の物理ディスクから出来る PV の総合体であることに"
"留意して 下さい。LVM の使用法についての詳細には、%s ドキュメントをご覧下さ"
"い。\n"

#: pyanaconda/iw/partition_gui.py:1496
msgid ""
"To create a PV you need a partition with free space.  To create a VG you "
"need a PV that is not part of any existing VG.  To create an LV you need a "
"VG with free space.\n"
"\n"
msgstr ""
"PV を作成するには、空き領域を持つパーティションが必要です。VG を作成するに"
"は、既存の VG の一部ではない PV が必要です。LV を作成するには、空き領域を持"
"つ VG が必要になります。\n"
"\n"

#: pyanaconda/iw/partition_gui.py:1500
#, python-format
msgid "You currently have %d available PV free to use.\n"
msgid_plural "You currently have %d available PVs free to use.\n"
msgstr[0] "現在、%d 個の PV の空き領域が使用できます。\n"
msgstr[1] "現在、%d 個の PV の空き領域が使用できます。\n"

#: pyanaconda/iw/partition_gui.py:1504
msgid "You currently have free space to create PVs."
msgstr "現在、PV を作成するための空き領域があります。"

#: pyanaconda/iw/partition_gui.py:1507
msgid "About LVM"
msgstr "LVM について"

#: pyanaconda/iw/partition_gui.py:1585 pyanaconda/storage/partitioning.py:203
#: pyanaconda/storage/partitioning.py:246
msgid "Error Partitioning"
msgstr "パーティション設定エラー"

#: pyanaconda/iw/partition_gui.py:1586
#, python-format
msgid "Could not allocate requested partitions: %s."
msgstr "要求されたパーティションを設定できませんでした: %s"

#: pyanaconda/iw/partition_gui.py:1595
#, python-format
msgid "Warning: %s."
msgstr "警告: %s"

#: pyanaconda/iw/partition_gui.py:1626
msgid "Unable To Edit"
msgstr "編集できません"

#: pyanaconda/iw/partition_gui.py:1627
#, python-format
msgid ""
"You cannot edit this device:\n"
"\n"
"%s"
msgstr ""
"このデバイスは編集できません:\n"
"\n"
"%s"

#: pyanaconda/iw/partition_gui.py:1810
msgid "_Create"
msgstr "作成(_C)"

#: pyanaconda/iw/partition_gui.py:1813
msgid "Re_set"
msgstr "リセット(_S)"

#: pyanaconda/iw/partition_gui.py:1836
msgid "Please Select A Device"
msgstr "デバイスを １つ選択してください。"

#: pyanaconda/iw/partition_ui_helpers_gui.py:110
#: pyanaconda/iw/partition_ui_helpers_gui.py:132
#: pyanaconda/iw/partition_ui_helpers_gui.py:134
msgid "<Not Applicable>"
msgstr "<適用外>"

#: pyanaconda/iw/partition_ui_helpers_gui.py:318
msgid "_Format as:"
msgstr "フォーマットする (_F):"

#: pyanaconda/iw/partition_ui_helpers_gui.py:340
msgid "Mi_grate filesystem to:"
msgstr "ファイルシステムを移動する:"

#: pyanaconda/iw/partition_ui_helpers_gui.py:370
msgid "_Resize"
msgstr "サイズを変更 (_R)"

#: pyanaconda/iw/partition_ui_helpers_gui.py:425
#, python-format
msgid ""
"Partitions of type '%s' must be constrained to a single drive.  To do this, "
"select the drive in the 'Allowable Drives' checklist."
msgstr ""
"タイプ '%s' のパーティションは単独ドライブに入れる必要があります。これは行う"
"には、「選択可能なドライブ」のチェックリストからそのドライブを選択します。"

#: pyanaconda/iw/raid_dialog_gui.py:390
msgid ""
"At least two unused software RAID partitions are needed to create a RAID "
"device.\n"
"\n"
"First create at least two partitions of type \"software RAID\", and then "
"select the \"RAID\" option again."
msgstr ""
"RAID デバイスを作成するには、少なくとも 2 つの未使用ソフトウェア RAID パー"
"ティションが必要です。\n"
" \n"
"最初に「ソフトウェア RAID」タイプのパーティションを少なくとも2つ作成してか"
"ら、再度「RAID」オプションを選択してください。"

#: pyanaconda/iw/raid_dialog_gui.py:404
msgid "Make RAID Device"
msgstr "RAID デバイスの作成"

#: pyanaconda/iw/raid_dialog_gui.py:407
#, python-format
msgid "Edit RAID Device: %s"
msgstr "RAID デバイスの編集: %s"

#: pyanaconda/iw/raid_dialog_gui.py:409
msgid "Edit RAID Device"
msgstr "RAID デバイスの編集"

#: pyanaconda/iw/raid_dialog_gui.py:476
msgid "RAID _Device:"
msgstr "RAID デバイス (_D):"

#: pyanaconda/iw/raid_dialog_gui.py:494
msgid "RAID _Level:"
msgstr "RAID レベル(_L):"

#: pyanaconda/iw/raid_dialog_gui.py:536
msgid "_RAID Members:"
msgstr "RAID メンバー(_R):"

#: pyanaconda/iw/raid_dialog_gui.py:553
msgid "Number of _spares:"
msgstr "スペア数(_S):"

#: pyanaconda/iw/raid_dialog_gui.py:563
msgid "_Format partition?"
msgstr "パーティションをフォーマットしますか(_F)?"

#: pyanaconda/iw/task_gui.py:55
#, python-format
msgid ""
"Unable to read package metadata from repository.  This may be due to a "
"missing repodata directory.  Please ensure that your repository has been "
"correctly generated.\n"
"\n"
"%s"
msgstr ""
"リポジトリーからパッケージのメタデータを読み込めません。repodata ディレクト"
"リーがないことが原因の可能性があります。リポジトリーが正しく生成されているか"
"確認してください。\n"
"\n"
"%s"

#: pyanaconda/iw/task_gui.py:129
msgid "Edit Repository"
msgstr "リポジトリーの編集"

#: pyanaconda/iw/task_gui.py:153
#, python-format
msgid ""
"The repository %s has already been added.  Please choose a different "
"repository name and URL."
msgstr ""
"リポジトリー %s はすでに追加されています。別のリポジトリー名と URL を選択して"
"ください。"

#: pyanaconda/iw/task_gui.py:239
msgid "Invalid Proxy URL"
msgstr "無効なプロキシ URL です。"

#: pyanaconda/iw/task_gui.py:240
msgid "You must provide an HTTP, HTTPS, or FTP URL to a proxy."
msgstr "プロキシには、HTTP, HTTPS, または FTP のURLを入力する必要があります。"

#: pyanaconda/iw/task_gui.py:252 pyanaconda/iw/task_gui.py:436
msgid "Invalid Repository URL"
msgstr "無効なリポジトリー URL です。"

#: pyanaconda/iw/task_gui.py:253 pyanaconda/iw/task_gui.py:437
msgid "You must provide an HTTP, HTTPS, or FTP URL to a repository."
msgstr ""
"リポジトリーには、HTTP, HTTPS, または FTP の URL を入力する必要があります。"

#: pyanaconda/iw/task_gui.py:274 pyanaconda/iw/task_gui.py:446
msgid "No Media Found"
msgstr "メディアが見つかりません。"

#: pyanaconda/iw/task_gui.py:275 pyanaconda/iw/task_gui.py:447
msgid ""
"No installation media was found. Please insert a disc into your drive and "
"try again."
msgstr ""
"インストール用メディアが見付かりません。ディスクをドライブに挿入して もう一度"
"試して下さい。"

#: pyanaconda/iw/task_gui.py:306 pyanaconda/iw/task_gui.py:470
msgid "Please enter an NFS server and path."
msgstr "NFS サーバーとパスを入力してください。"

#: pyanaconda/iw/task_gui.py:325
#, python-format
msgid ""
"The following error occurred while setting up the repository:\n"
"\n"
"%s"
msgstr ""
"リポジトリーの設定中に次のエラーが見つかりました。\n"
"\n"
"%s"

#: pyanaconda/iw/task_gui.py:348
msgid "Invalid Repository Name"
msgstr "無効なリポジトリー名です"

#: pyanaconda/iw/task_gui.py:349
msgid "You must provide a repository name."
msgstr "リポジトリー名を入力しなければなりません。"

#: pyanaconda/iw/task_gui.py:502 data/ui/addrepo.glade.h:3
msgid "Add Repository"
msgstr "リポジトリーの追加"

#: pyanaconda/iw/task_gui.py:507
msgid "No Software Repos Enabled"
msgstr "ソフトウェアレポジトリが有効になっていません"

#: pyanaconda/iw/task_gui.py:508
msgid ""
"You must have at least one software repository enabled to continue "
"installation."
msgstr ""
"インストールを続行する為には少なくとも１つのソフトウェアリポジトリーが有効に "
"なっている必要があります。"

#: pyanaconda/iw/timezone_gui.py:63 pyanaconda/textw/timezone_text.py:95
msgid "Time Zone Selection"
msgstr "タイムゾーンの選択"

#: pyanaconda/iw/upgrade_bootloader_gui.py:37
#: pyanaconda/textw/upgrade_bootloader_text.py:129
msgid "Upgrade Boot Loader Configuration"
msgstr "ブートローダー設定のアップグレード"

#: pyanaconda/iw/upgrade_bootloader_gui.py:120
msgid "_Update boot loader configuration"
msgstr "ブートローダー設定の更新(_U)"

#: pyanaconda/iw/upgrade_bootloader_gui.py:121
msgid "This will update your current boot loader."
msgstr "これで現在のブートローダーを更新します。"

#: pyanaconda/iw/upgrade_bootloader_gui.py:125
#: pyanaconda/textw/upgrade_bootloader_text.py:103
msgid ""
"Due to system changes, your boot loader configuration can not be "
"automatically updated."
msgstr "システムが変わったので、ブートローダー設定は自動的には更新されません。"

#: pyanaconda/iw/upgrade_bootloader_gui.py:128
#: pyanaconda/textw/upgrade_bootloader_text.py:107
msgid ""
"The installer is unable to detect the boot loader currently in use on your "
"system."
msgstr "インストーラーは現在システムで使用中のブートローダーを検出できません。"

#: pyanaconda/iw/upgrade_bootloader_gui.py:135
#: pyanaconda/textw/upgrade_bootloader_text.py:116
#, python-format
msgid ""
"The installer has detected the %(type)s boot loader currently installed on "
"%(bootDev)s."
msgstr ""
"インストーラーが現在 %(bootDev)s にインストールされている %(type)s ブートロー"
"ダーを検出しました。"

#: pyanaconda/iw/upgrade_bootloader_gui.py:139
msgid "This is the recommended option."
msgstr "これは推奨されるオプションです。"

#: pyanaconda/iw/upgrade_bootloader_gui.py:144
msgid "_Create new boot loader configuration"
msgstr "新しいブートローダー設定を作成(_C)"

#: pyanaconda/iw/upgrade_bootloader_gui.py:146
msgid ""
"This option creates a new boot loader configuration.  If you wish to switch "
"boot loaders, you should choose this."
msgstr ""
"このオプションは新しいブートローダー設定を作成します。ブートローダーを変更し"
"たい場合は、これを選択してください。"

#: pyanaconda/iw/upgrade_bootloader_gui.py:153
msgid "_Skip boot loader updating"
msgstr "ブートローダーの更新をスキップ(_S)"

#: pyanaconda/iw/upgrade_bootloader_gui.py:154
msgid ""
"This option makes no changes to boot loader configuration.  If you are using "
"a third party boot loader, you should choose this."
msgstr ""
"このオプションはブートローダー設定をまったく変更しません。他社製ブートロー"
"ダーを使用している場合は、これを選択してください。"

#: pyanaconda/iw/upgrade_bootloader_gui.py:165
msgid "What would you like to do?"
msgstr "どうしますか?"

#: pyanaconda/iw/upgrade_migratefs_gui.py:38
#: pyanaconda/textw/upgrade_text.py:42
msgid "Migrate File Systems"
msgstr "ファイルシステムの移行"

#: pyanaconda/iw/upgrade_migratefs_gui.py:69
#: pyanaconda/textw/upgrade_text.py:44
#, python-format
msgid ""
"This release of %(productName)s supports an updated file system, which has "
"several benefits over the file system traditionally shipped in "
"%(productName)s.  This installation program can migrate formatted partitions "
"without data loss.\n"
"\n"
"Which of these partitions would you like to migrate?"
msgstr ""
"%(productName)s のこのリリースでは最新のファイルシステムをサポートしていま"
"す。これらは従来 %(productName)s で配布されていたファイルシステムに比べ優れた"
"点をいくつか備えています。このインストールプログラムは、データを失うことなく"
"フォーマットしたパーティションを移行することができます。\n"
"\n"
"これらのどのパーティションを移行しますか?"

#: pyanaconda/iw/upgrade_swap_gui.py:35
msgid "Upgrade Swap Partition"
msgstr "swap パーティションのアップグレード"

#: pyanaconda/iw/upgrade_swap_gui.py:92 pyanaconda/textw/upgrade_text.py:107
#, python-format
msgid ""
"Recent kernels (2.4 or newer) need significantly more swap than older "
"kernels, up to twice the amount of RAM on the system.  You currently have "
"%dMB of swap configured, but you may create additional swap space on one of "
"your file systems now."
msgstr ""
"最近のカーネル(2.4以降)では旧来のカーネルに比べ、膨大な swap 領域を必要とし、"
"最大でシステムの RAM の 2 倍が必要です。現在、 %dMB の swap 領域を確保してい"
"ますが、ここでファイルシステムのいずれかに追加の swap 領域を作成することがで"
"きます。"

#: pyanaconda/iw/upgrade_swap_gui.py:99
#, python-format
msgid ""
"\n"
"\n"
"The installer has detected %s MB of RAM.\n"
msgstr ""
"\n"
"\n"
"インストーラーは %s MB の RAM を検出しました。\n"

#: pyanaconda/iw/upgrade_swap_gui.py:111
msgid "I _want to create a swap file"
msgstr "swap ファイルを作成します(_W)"

#: pyanaconda/iw/upgrade_swap_gui.py:120
msgid "Select the _partition to put the swap file on:"
msgstr "swap ファイルを配置するパーティションを選択(_P):"

#: pyanaconda/iw/upgrade_swap_gui.py:138 pyanaconda/textw/upgrade_text.py:125
msgid "Partition"
msgstr "パーティション"

#: pyanaconda/iw/upgrade_swap_gui.py:138
msgid "Free Space (MB)"
msgstr "空き領域 (MB)"

#: pyanaconda/iw/upgrade_swap_gui.py:156
#, python-format
msgid ""
"A minimum swap file size of %d MB is recommended.  Please enter a size for "
"the swap file:"
msgstr ""
"最低でも %d MB の swap ファイルにすることを推奨します。swap ファイルの容量を"
"入力してください。"

#: pyanaconda/iw/upgrade_swap_gui.py:171
msgid "Swap file _size (MB):"
msgstr " swap ファイルの容量 (MB)(_S):"

#: pyanaconda/iw/upgrade_swap_gui.py:181
msgid "I _don't want to create a swap file"
msgstr "swap ファイルを作成しません(_D)"

#: pyanaconda/iw/upgrade_swap_gui.py:191
msgid ""
"A swap file is strongly recommended. Failure to create one could cause the "
"installer to abort abnormally.  Are you sure you wish to continue?"
msgstr ""
"swap ファイルの作成を強く推奨します。 swap ファイルを作成しないと、インストー"
"ラーが異常終了する原因となる場合があります。本当に続行しますか?"

#: pyanaconda/iw/upgrade_swap_gui.py:199 pyanaconda/textw/upgrade_text.py:194
msgid "The swap file must be between 1 and 2000 MB in size."
msgstr "swap ファイルは 1 MB から 2000 MB の間の容量にしてください。"

#: pyanaconda/iw/upgrade_swap_gui.py:206 pyanaconda/textw/upgrade_text.py:189
msgid ""
"There is not enough space on the device you selected for the swap partition."
msgstr "swap パーティション用に選択したデバイスには十分な領域がありません。"

#: pyanaconda/iw/welcome_gui.py:56 pyanaconda/textw/welcome_text.py:36
msgid "Network Install Required"
msgstr "ネットワークのインストールが必要"

#: pyanaconda/iw/welcome_gui.py:57 pyanaconda/textw/welcome_text.py:37
msgid ""
"Your installation source is set to a network location, but no network "
"devices were found on your system.  To avoid a network installation, boot "
"with the full DVD, full CD set, or do not pass a repo= parameter that "
"specifies a network source."
msgstr ""
"インストールのソースがネットワークの位置に設定してありますが、システム上に "
"ネットワークデバイスが見当たりません。ネットワークインストールを避けるには、 "
"完全な DVD か完全な CD セットで起動しますが、その場合、ネットワークソースを "
"指定してしまう repo= parameter を渡さないで下さい。"

#: pyanaconda/iw/welcome_gui.py:67
msgid "E_xit Installer"
msgstr "インストーラーを終了(_X)"

#: pyanaconda/iw/zipl_gui.py:37
msgid "z/IPL Boot Loader Configuration"
msgstr "z/IPL ブートローダーの設定"

#: pyanaconda/iw/zipl_gui.py:61
msgid "The z/IPL boot loader will be installed on your system."
msgstr "z/IPL ブートローダーがシステムにインストールされます。"

#: pyanaconda/iw/zipl_gui.py:63
msgid ""
"The z/IPL Boot Loader will now be installed on your system.\n"
"\n"
"The root partition will be the one you selected previously in the partition "
"setup.\n"
"\n"
"The kernel used to start the machine will be the one to be installed by "
"default.\n"
"\n"
"If you wish to make changes later after the installation feel free to change "
"the /etc/zipl.conf configuration file.\n"
"\n"
"You can now enter any additional kernel parameters which your machine or "
"your setup may require."
msgstr ""
"z/IPL ブートローダーがシステムにインストールされます。\n"
"\n"
"root パーティションはパーティションの設定で既に選択したパーティションになりま"
"す。\n"
"\n"
"マシンの起動に使用されるカーネルはデフォルトでインストールされるカーネルにな"
"ります。\n"
"\n"
"インストール後に変更を加える場合は、/etc/zipl.conf の設定ファイルを自由に変更"
"できます。\n"
"\n"
"ここでご使用のマシンまたは設定が必要とする追加のカーネルパラメーターを入力す"
"ることができます。"

#: pyanaconda/iw/zipl_gui.py:90 pyanaconda/textw/zipl_text.py:72
msgid "Kernel Parameters"
msgstr "カーネルパラメーター"

#: pyanaconda/iw/zipl_gui.py:93 pyanaconda/iw/zipl_gui.py:96
msgid "Chandev Parameters"
msgstr "Chandev パラメーター"

#: loader/net.h:27 pyanaconda/textw/netconfig_text.py:164
msgid "Dynamic IP configuration (DHCP)"
msgstr "DHCP (動的 IP 設定)"

#: loader/net.h:28
msgid "Manual configuration"
msgstr "手動による設定"

#: loader/net.h:30
msgid "Dynamic IP configuration (DHCPv6)"
msgstr "DHCPv6 (動的 IP 設定)"

#: loader/net.h:31 pyanaconda/textw/netconfig_text.py:201
msgid "Automatic neighbor discovery"
msgstr "自動近隣接続発見機能"

#: loader/cdinstall.c:186 loader/cdinstall.c:207 loader/mediacheck.c:61
msgid "Media Check"
msgstr "メディアチェック"

#: loader/cdinstall.c:186 loader/cdinstall.c:189 loader/cdinstall.c:207
#: loader/cdinstall.c:215 loader/method.c:333
msgid "Test"
msgstr "テスト"

#: loader/cdinstall.c:186 loader/cdinstall.c:190
msgid "Eject Disc"
msgstr "ディスク取り出し"

#: loader/cdinstall.c:187
#, c-format
msgid ""
"Choose \"%s\" to test the disc currently in the drive, or \"%s\" to eject "
"the disc and insert another for testing."
msgstr ""
"現在ドライブに入っているディスクをテストするには \"%s\" を選び、 ディスクを取"
"り出して別のディスクを挿入してテストをするには。 \"%s\" を選びます。"

#: loader/cdinstall.c:208
#, c-format
msgid ""
"If you would like to test additional media, insert the next disc and press "
"\"%s\". Testing each disc is not strictly required, however it is highly "
"recommended.  Minimally, the discs should be tested prior to using them for "
"the first time. After they have been successfully tested, it is not required "
"to retest each disc prior to using it again."
msgstr ""
"追加のメディアをテストする場合は、次のディスクを挿入してから \"%s\" を押して"
"ください。それぞれのディスクのテストは絶対に必要なわけではありませんが、強く"
"推奨します。最低でも、はじめて使用する前にはテストを行ってください。テストが"
"成功したら、再度使用する前に各ディスクをテストする必要はありません。"

#: loader/cdinstall.c:230
#, c-format
msgid ""
"The %s disc was not found in any of your drives. Please insert the %s disc "
"and press %s to retry."
msgstr ""
"いずれのドライブにも %s ディスク は見つかりませんでした。%s ディスクを挿入し"
"てから、%s を押して再試行してください。"

#: loader/cdinstall.c:249
msgid "Disc Found"
msgstr "ディスク が見つかりました"

#: loader/cdinstall.c:250
#, c-format
msgid ""
"To begin testing the media before installation press %s.\n"
"\n"
"Choose %s to skip the media test and start the installation."
msgstr ""
"インストールの前にメディアのテストを開始するには %s を押します。\n"
"\n"
"メディアテストをスキップするには %s を選択して、インストールを開始します。"

#: loader/cdinstall.c:331
msgid "Scanning"
msgstr "スキャン中"

#: loader/cdinstall.c:331
#, c-format
msgid "Looking for installation images on CD device %s\n"
msgstr "CD デバイス %s 上のインストールイメージを探しています\n"

#: loader/cdinstall.c:333
#, c-format
msgid "Looking for installation images on CD device %s"
msgstr "CD デバイス %s 上のインストールイメージを探しています。"

#: loader/cdinstall.c:425
#, c-format
msgid ""
"The %s disc was not found in any of your CDROM drives. Please insert the %s "
"disc and press %s to retry."
msgstr ""
"いずれの CDROM ドライブにも %s ディスクは見つかりませんでした。%s ディスクを"
"挿入してから、%s を押して再試行してください。"

#: loader/cdinstall.c:431
msgid "Disc Not Found"
msgstr "ディスクが見つかりません"

#: loader/cdinstall.c:432 loader/driverdisk.c:409 loader/driverdisk.c:441
#: loader/driverdisk.c:522 loader/driverselect.c:79 loader/driverselect.c:153
#: loader/driverselect.c:179 loader/hdinstall.c:212 loader/hdinstall.c:266
#: loader/kbd.c:119 loader/loader.c:510 loader/loader.c:527
#: loader/loader.c:1399 loader/loader.c:1432 loader/net.c:621
#: loader/net.c:1001 loader/net.c:1981 loader/net.c:2000
#: loader/nfsinstall.c:116 loader/urls.c:269
#: pyanaconda/storage/__init__.py:123 pyanaconda/storage/__init__.py:169
#: pyanaconda/storage/devicetree.py:90 pyanaconda/textw/constants_text.py:52
msgid "Back"
msgstr "戻る"

#: loader/cdinstall.c:506
msgid "Cannot find kickstart file on CDROM."
msgstr "ディスクROM 上にキックスタートファイルが見つかりません。"

#: loader/copy.c:51 loader/method.c:287
#, c-format
msgid "Failed to read directory %s: %m"
msgstr "%s ディレクトリーの読み込みに失敗: %m"

#: loader/driverdisk.c:274
msgid "Loading"
msgstr "読み込み中"

#: loader/driverdisk.c:274
msgid "Reading driver disk"
msgstr "ドライバーディスクを読み込み中"

#: loader/driverdisk.c:403 loader/driverdisk.c:436
msgid "Driver Disk Source"
msgstr "ドライバーディスクソース"

#: loader/driverdisk.c:404
msgid ""
"You have multiple devices which could serve as sources for a driver disk.  "
"Which would you like to use?"
msgstr ""
"ドライバーディスク用のソースとして使用できるデバイスが複数あります。使用する"
"デバイスを指定してください。"

#: loader/driverdisk.c:437
msgid ""
"There are multiple partitions on this device which could contain the driver "
"disk image.  Which would you like to use?"
msgstr ""
"このデバイスにはドライバーディスクのイメージを格納できるパーティションが複数"
"あります。使用するパーティションを指定してください。"

#: loader/driverdisk.c:472
msgid "Failed to mount partition."
msgstr "パーティションのマウントに失敗しました。"

#: loader/driverdisk.c:477
msgid "Select driver disk image"
msgstr "ドライバーディスクイメージを選択してください"

#: loader/driverdisk.c:478
msgid "Select the file which is your driver disk image."
msgstr "ドライバーディスクイメージのファイルを選択してください。"

#: loader/driverdisk.c:507
msgid "Failed to load driver disk from file."
msgstr "ファイルからのドライバーディスク読み込みに失敗しました。"

#: loader/driverdisk.c:519
#, c-format
msgid "Insert your driver disk into /dev/%s and press \"OK\" to continue."
msgstr "ドライバーディスクを /dev/%s に挿入し、「OK」 を押して続行します。"

#: loader/driverdisk.c:522
msgid "Insert Driver Disk"
msgstr "ドライバーディスクを挿入"

#: loader/driverdisk.c:535
msgid "Failed to mount driver disk."
msgstr "ドライバーディスクのマウントに失敗しました。"

#: loader/driverdisk.c:543
#, c-format
msgid "Driver disk is invalid for this release of %s."
msgstr "この %s のリリースにはドライバーディスクは無効です。"

#: loader/driverdisk.c:609
msgid "Manually choose"
msgstr "手動で選択"

#: loader/driverdisk.c:610
msgid "Load another disk"
msgstr "別のディスクをロード"

#: loader/driverdisk.c:611
msgid ""
"No devices of the appropriate type were found on this driver disk.  Would "
"you like to manually select the driver, continue anyway, or load another "
"driver disk?"
msgstr ""
"このドライバーディスク上では適切なタイプのデバイスが見つかりませんでした。手"
"動でドライバーを選択する、このまま続行する、別のドライバーディスクを読み込"
"む、のいずれかを指定してください。"

#: loader/driverdisk.c:649
msgid "Driver disk"
msgstr "ドライバーディスク"

#: loader/driverdisk.c:650
msgid "Do you have a driver disk?"
msgstr "ドライバーディスクがありますか?"

#: loader/driverdisk.c:659
msgid "More Driver Disks?"
msgstr "他のドライバーディスク?"

#: loader/driverdisk.c:660
msgid "Do you wish to load any more driver disks?"
msgstr "他のドライバーディスクを読み込みますか?"

#: loader/driverdisk.c:709 loader/driverdisk.c:748 loader/hdinstall.c:360
#: loader/kickstart.c:135 loader/kickstart.c:145 loader/kickstart.c:187
#: loader/kickstart.c:192 loader/kickstart.c:339 loader/kickstart.c:355
#: loader/kickstart.c:571 loader/net.c:1654 loader/net.c:1675
#: loader/nfsinstall.c:414 loader/urlinstall.c:374 loader/urlinstall.c:385
#: loader/urlinstall.c:392
msgid "Kickstart Error"
msgstr "キックスタートエラー"

#: loader/driverdisk.c:710
#, c-format
msgid "Unknown driver disk kickstart source: %s"
msgstr "キックスタートの元となるドライバーディスクが不明です: %s"

#: loader/driverdisk.c:749
#, c-format
msgid ""
"The following invalid argument was specified for the kickstart driver disk "
"command: %s"
msgstr ""
"キックスタートのドライバーディスクコマンドに以下のような不正な引数が指定され"
"ました: %s"

#: loader/driverselect.c:68
#, c-format
msgid ""
"Please enter any parameters which you wish to pass to the %s module "
"separated by spaces.  If you don't know what parameters to supply, skip this "
"screen by pressing the \"OK\" button."
msgstr ""
"%s モジュールに渡すパラメーターを空白で区切って入力してください。どのパラメー"
"ターを使用するのかわからない場合、「OK」 ボタンを押してこの画面をスキップして"
"ください。"

#: loader/driverselect.c:89
msgid "Enter Module Parameters"
msgstr "モジュールパラメーターを入力"

#: loader/driverselect.c:152
msgid "No drivers found"
msgstr "ドライバーが見つかりません"

#: loader/driverselect.c:152
msgid "Load driver disk"
msgstr "ドライバーディスクの読み込み"

#: loader/driverselect.c:153
msgid ""
"No drivers were found to manually insert.  Would you like to use a driver "
"disk?"
msgstr ""
"手動で挿入するドライバーが見つかりませんでした。ドライバーディスクを使用しま"
"すか?"

#: loader/driverselect.c:171
msgid ""
"Please select the driver below which you wish to load.  If it does not "
"appear and you have a driver disk, press F2."
msgstr ""
"読み込むドライバーを下記から選択してください。必要なドライバーが表示されてい"
"ないがドライバーディスクがある場合、F2 を押してください。"

#: loader/driverselect.c:180
msgid "Specify optional module arguments"
msgstr "オプションのモジュール引数を指定してください"

#: loader/driverselect.c:205
msgid "Select Device Driver to Load"
msgstr "読み込むデバイスドライバーを選択してください"

#: loader/hdinstall.c:116
msgid ""
"An error occured finding the installation image on your hard drive.  Please "
"check your images and try again."
msgstr ""
"ハードディスクからインストールイメージを読み込み中にエラーが発生しました。 ご"
"使用のイメージを確認してからやり直してください。"

#: loader/hdinstall.c:213
msgid ""
"You don't seem to have any hard drives on your system! Would you like to "
"configure additional devices?"
msgstr ""
"このシステムにはハードディスクがないようです。追加デバイスの設定を行いますか?"

#: loader/hdinstall.c:226
#, c-format
msgid ""
"What partition and directory on that partition holds the installation image "
"for %s?  If you don't see the disk drive you're using listed here, press F2 "
"to configure additional devices."
msgstr ""
"%s 用 インストールイメージを格納しているパーティションとディレクトリーを指定"
"してください。一覧内に、使用しているディスクドライブがなければ、 F2 を押して"
"追加デバイスの設定を行ってください。"

#: loader/hdinstall.c:250
msgid "Directory holding image:"
msgstr "イメージを格納しているディレクトリー:"

#: loader/hdinstall.c:278
msgid "Select Partition"
msgstr "パーティションを選択してください"

#: loader/hdinstall.c:326
#, c-format
msgid "Device %s does not appear to contain an installation image."
msgstr "デバイス %s にはインストールイメージが含まれていないようです。"

#: loader/hdinstall.c:361
#, c-format
msgid "Bad argument to HD kickstart method command: %s"
msgstr "HD キックスタートコマンド に対する引数が不正です: %s"

#: loader/hdinstall.c:441 loader/hdinstall.c:497
msgid "Cannot find kickstart file on hard drive."
msgstr "ハードディスクにキックスタートファイルが見つかりません。"

#: loader/hdinstall.c:484
#, c-format
msgid "Cannot find hard drive for BIOS disk %s"
msgstr "BIOS ディスク %s 用のハードディスクが見つかりません"

#: loader/kbd.c:117
msgid "Keyboard Type"
msgstr "キーボードの種類"

#: loader/kbd.c:118
msgid "What type of keyboard do you have?"
msgstr "ご使用のキーボードの種類を指定してください。"

#: loader/kickstart.c:136
#, c-format
msgid "Error opening kickstart file %s: %m"
msgstr "キックスタートファイル %s を開く際にエラー: %m"

#: loader/kickstart.c:146
#, c-format
msgid "Error reading contents of kickstart file %s: %m"
msgstr "キックスタートファイル %s の読み込み時にエラー: %m"

#: loader/kickstart.c:188
#, c-format
msgid "Error in %s on line %d of kickstart file %s."
msgstr "%s のエラーが %d 行目(キックスタートファイル %s の)で発生しました。"

#: loader/kickstart.c:193
#, c-format
msgid "Missing options on line %d of kickstart file %s."
msgstr "%d 行目のオプションがキックスタートファイル %s にありません。"

#: loader/kickstart.c:300
msgid "Cannot find ks.cfg on removable media."
msgstr "リムーバブルメディアに ks.cfg が見つかりません。"

#: loader/kickstart.c:340
#, c-format
msgid "Bad argument to device kickstart method command: %s"
msgstr "デバイスキックスタートメソッドのコマンドに対する引数が不正です: %s"

#: loader/kickstart.c:356
msgid "A module name must be specified for the kickstart device command."
msgstr "モジュール名がキックスタートデバイスコマンドに指定されていません。"

#: loader/kickstart.c:387
msgid ""
"Unable to download the kickstart file.  Please modify the kickstart "
"parameter below or press Cancel to proceed as an interactive installation."
msgstr ""
"キックスタートファイルをダウンロードすることができません。以下のキックスター"
"トパラメーターを変更するか、対話インストールとして続行するために Cancel を押"
"してください。"

#: loader/kickstart.c:396
msgid "Error downloading kickstart file"
msgstr "キックスタートファイルをダウンロードする際にエラー発生"

#: loader/kickstart.c:572
#, c-format
msgid "Bad argument to shutdown kickstart method command: %s"
msgstr "シャットダウンキックスタートメソッドコマンドに対する引数が不正です: %s"

#: loader/lang.c:63 loader/loader.c:227
#, c-format
msgid "Welcome to %s for %s"
msgstr "%s (%s 用)へようこそ"

#: loader/lang.c:64
#, c-format
msgid "Welcome to %s for %s - Rescue Mode"
msgstr "%s (%s 用)へようこそ - レスキューモード"

#: loader/lang.c:65 loader/loader.c:251
msgid ""
"  <Tab>/<Alt-Tab> between elements  | <Space> selects | <F12> next screen "
msgstr "  <Tab>/<Alt-Tab> 項目間の移動 | <Space> 選択 | <F12> 次の画面 "

#: loader/lang.c:370
msgid "Choose a Language"
msgstr "言語を選択してください"

#: loader/loader.c:131
msgid "Local CD/DVD"
msgstr "ローカル CD/DVD"

#: loader/loader.c:132
msgid "Hard drive"
msgstr "ハードディスク"

#: loader/loader.c:133
msgid "NFS directory"
msgstr "NFS ディレクトリー:"

#: loader/loader.c:464 loader/loader.c:505
msgid "Update Disk Source"
msgstr "ディスクソースの更新"

#: loader/loader.c:465
msgid ""
"You have multiple devices which could serve as sources for an update disk.  "
"Which would you like to use?"
msgstr ""
"更新ディスク用のソースとして使用できるデバイスが複数あります。使用するデバイ"
"スを指定してください。"

#: loader/loader.c:506
msgid ""
"There are multiple partitions on this device which could contain the update "
"disk image.  Which would you like to use?"
msgstr ""
"このデバイスにはアップデートディスクイメージを含んでいるかもしれないパーティ"
"ションが複数あります。使用するパーティションを指定してください。"

#: loader/loader.c:524
#, c-format
msgid "Insert your updates disk into %s and press \"OK\" to continue."
msgstr "更新ディスクを %s に挿入してから 「OK」 を押して続行します。"

#: loader/loader.c:527
msgid "Updates Disk"
msgstr "更新ディスク"

#: loader/loader.c:545
msgid "Failed to mount updates disk"
msgstr "更新ディスクのマウントに失敗しました"

#: loader/loader.c:550
msgid "Updates"
msgstr "更新"

#: loader/loader.c:550
msgid "Reading anaconda updates"
msgstr "anaconda の更新を読み込み中"

#: loader/loader.c:586
msgid ""
"Unable to download the updates image.  Please modify the updates location "
"below or press Cancel to proceed without updates.."
msgstr ""
"アップデートイメージをダウンロードできません。以下のアップデートの場所を編集"
"するか、キャンセルを押してアップデートを中止してください。"

#: loader/loader.c:595
msgid "Error downloading updates image"
msgstr "アップデートイメージのダウンロード中にエラー発生"

#: loader/loader.c:1196
#, c-format
msgid "You do not have enough RAM to install %s on this machine."
msgstr "このマシンには %s のインストールに十分な RAM がありません。"

#: loader/loader.c:1197
#, c-format
msgid ""
"You do not have enough RAM to install %s on this machine using this install "
"method."
msgstr "このマシンには %s のインストールに十分な RAM がありません。"

#: loader/loader.c:1262
msgid "Media Detected"
msgstr "検出されたメディア"

#: loader/loader.c:1263
msgid "Found local installation media"
msgstr "ローカルのインストールメディアが検出されました"

#: loader/loader.c:1391
msgid "Rescue Method"
msgstr "レスキュー方法"

#: loader/loader.c:1392
msgid "Installation Method"
msgstr "インストール方法"

#: loader/loader.c:1394
msgid "What type of media contains the rescue image?"
msgstr "レスキューイメージが格納されているメディアタイプを指定してください。"

#: loader/loader.c:1396
msgid "What type of media contains the installation image?"
msgstr "インストールイメージが格納されているメディアタイプを指定してください。"

#: loader/loader.c:1431
msgid "No driver found"
msgstr "ドライバーが見つかりません"

#: loader/loader.c:1431
msgid "Select driver"
msgstr "ドライバーを選択してください"

#: loader/loader.c:1432
msgid "Use a driver disk"
msgstr "ドライバーディスクを使用する"

#: loader/loader.c:1433
msgid ""
"Unable to find any devices of the type needed for this installation type.  "
"Would you like to manually select your driver or use a driver disk?"
msgstr ""
"このインストールタイプに必要な種類のデバイスを見つけることができません。  手"
"動でドライバーを選択しますか、またはドライバーディスクを使用しますか?"

#: loader/loader.c:1664
msgid "The following devices have been found on your system."
msgstr "システム上で次のデバイスが検出されました。"

#: loader/loader.c:1666
msgid ""
"No device drivers have been loaded for your system.  Would you like to load "
"any now?"
msgstr ""
"デバイスドライバーはシステムにロードされていません。ドライバーをロードします"
"か?"

#: loader/loader.c:1670
msgid "Devices"
msgstr "デバイス"

#: loader/loader.c:1671
msgid "Done"
msgstr "終了"

#: loader/loader.c:1672
msgid "Add Device"
msgstr "デバイスの追加"

#: loader/loader.c:1977
#, c-format
msgid "loader has already been run.  Starting shell.\n"
msgstr "ローダーはすでに実行されています。シェルの起動中です。\n"

#: loader/loader.c:2121
#, c-format
msgid "Driver disc was detected in %s. Do you want to use it?."
msgstr "ドライバーディスクが %s で検出されました。これを使用しますか？"

#: loader/loader.c:2124
msgid "Driver disc detected"
msgstr "ドライバーディスクを検出しました"

#: loader/loader.c:2124
msgid "Use it"
msgstr "それを使用する"

#: loader/loader.c:2124
msgid "Skip it"
msgstr "それをスキップする"

#: loader/loader.c:2459
#, c-format
msgid "Running anaconda %s, the %s rescue mode - please wait.\n"
msgstr ""
"anaconda %s を %s レスキューモードで実行中 - しばらくお待ちください。\n"

#: loader/loader.c:2461
#, c-format
msgid "Running anaconda %s, the %s system installer - please wait.\n"
msgstr ""
"anaconda %s・%s システムインストーラーを実行中 - しばらくお待ちください。\n"

#: loader/mediacheck.c:47
#, c-format
msgid "Unable to find install image %s"
msgstr "インストールイメージ %s を検出できません。"

#: loader/mediacheck.c:53
#, c-format
msgid "Checking \"%s\"."
msgstr "\"%s\" のチェック中。"

#: loader/mediacheck.c:55
#, c-format
msgid "Checking media."
msgstr "メディアをチェック中。"

#: loader/mediacheck.c:87
msgid ""
"Unable to find the checksum in the image.  This probably means the disc was "
"created without adding the checksum."
msgstr ""
"イメージ内でチェックサムを見つけることができません。恐らく、このディスクは"
"チェックサムを 追加しないで作成されています。"

#: loader/mediacheck.c:94
msgid "Unable to open the image."
msgstr "イメージを開けません。"

#: loader/mediacheck.c:98
msgid ""
"The image which was just tested has errors. This could be due to a corrupt "
"download or a bad disc.  If applicable, please clean the disc and try "
"again.  If this test continues to fail you should not continue the install."
msgstr ""
"今テストしたイメージはエラーを含んでいます。欠陥のあるダウンロードまたはディ"
"スク不良が原因の可能性があります。可能ならディスクを清掃してからやり直してく"
"ださい。このテストが失敗を繰り返す場合、インストールは中止すべきです。"

#: loader/mediacheck.c:106
msgid "Success"
msgstr "成功"

#: loader/mediacheck.c:107
msgid ""
"The image which was just tested was successfully verified.  It should be OK "
"to install from this media.  Note that not all media/drive errors can be "
"detected by the media check."
msgstr ""
"テストしたイメージの検証に成功しました。このメディアからのインストールは問題"
"ないでしょう。ただし、すべてのメディア・ドライブのエラーがメディアチェックで"
"発見できるとは限りません。"

#: loader/method.c:330
#, c-format
msgid ""
"Would you like to perform a checksum test of the ISO image:\n"
"\n"
"   %s?"
msgstr ""
"ISO イメージのチェックサムテストを実施しますか: \n"
"\n"
"   %s?"

#: loader/method.c:333
msgid "Checksum Test"
msgstr "チェックサムテスト"

#: loader/net.c:110
msgid "Invalid Prefix"
msgstr "無効なプレフィックス"

#: loader/net.c:111
msgid ""
"Prefix must be between 1 and 32 for IPv4 networks or between 1 and 128 for "
"IPv6 networks"
msgstr ""
"プレフィックスは、IPv4 ネットワークなら 1 から 32 まで、IPv6 ネットワークな"
"ら 1 から 128 までの数値にしなければなりません。"

#: loader/net.c:506 loader/net.c:514 loader/net.c:569
#, c-format
msgid "There was an error configuring your network interface."
msgstr "ネットワークインターフェースの設定中にエラーが発生しました。"

#: loader/net.c:508
#, c-format
msgid ""
"\n"
"This cannot be corrected in cmdline mode.\n"
"Halting.\n"
msgstr ""
"\n"
"これは cmdline モードでは修正できません。\n"
"一時停止します。\n"

#: loader/net.c:513 loader/net.c:568 pyanaconda/textw/netconfig_text.py:403
msgid "Network Error"
msgstr "ネットワークエラー"

#: loader/net.c:599
msgid "Enable IPv4 support"
msgstr "IPv4 サポートを有効にする"

#: loader/net.c:613
msgid "Enable IPv6 support"
msgstr "IPv6 サポートを有効にする"

#: loader/net.c:653
msgid "Configure TCP/IP"
msgstr "TCP/IP の設定"

#: loader/net.c:710
msgid "Missing Protocol"
msgstr "見つからないプロトコル"

#: loader/net.c:711
msgid "You must select at least one protocol (IPv4 or IPv6)."
msgstr "少くともプロトコルを 1 つ選択しなければなりません (IPv4 または IPv6)。"

#: loader/net.c:718
msgid "IPv4 Needed for NFS"
msgstr "NFS には IPv4 が必要です"

#: loader/net.c:719
msgid "NFS installation method requires IPv4 support."
msgstr "NFS インストールを行うには IPv4 のサポートが必要になります。"

#: loader/net.c:827
msgid "IPv4 address:"
msgstr "IPv4 アドレス:"

#: loader/net.c:839 loader/net.c:906 data/ui/netconfig.glade.h:1
msgid "/"
msgstr "/"

#: loader/net.c:894
msgid "IPv6 address:"
msgstr "IPv6 アドレス:"

#: loader/net.c:960 pyanaconda/textw/netconfig_text.py:184
#: pyanaconda/textw/netconfig_text.py:224
msgid "Gateway:"
msgstr "ゲートウェイ:"

#: loader/net.c:968
msgid "Name Server:"
msgstr "ネームサーバー:"

#: loader/net.c:1007
msgid ""
"Enter the IPv4 and/or the IPv6 address and prefix (address / prefix).  For "
"IPv4, the dotted-quad netmask or the CIDR-style prefix are acceptable. The "
"gateway and name server fields must be valid IPv4 or IPv6 addresses."
msgstr ""
"IPv4 および/または IPv6 アドレスとプレフィックス (アドレス / プレフィックス) "
"を入力してください。 IPv4 では 4 つの数字をドットで区切ったネットマスクか "
"CIDR 形式のプレフィックスが可能です。ゲートウェイとネームサーバーのフィールド"
"は、必ず有効な IPv4 または IPv6 アドレスでなければなりません。"

#: loader/net.c:1024
msgid "Manual TCP/IP Configuration"
msgstr "手動による TCP/IP 設定"

#: loader/net.c:1148 loader/net.c:1156
msgid "Missing Information"
msgstr "情報が不足しています"

#: loader/net.c:1149
msgid ""
"You must enter both a valid IPv4 address and a network mask or CIDR prefix."
msgstr ""
"有効な IPv4 アドレスとネットマスクまたは CIDR プレフィックスの両方を入力する"
"必要があります。"

#: loader/net.c:1157
msgid "You must enter both a valid IPv6 address and a CIDR prefix."
msgstr ""
"有効な IPv6 アドレスと CIDR プレフィックスの両方を入力する必要があります。"

#: loader/net.c:1655
#, c-format
msgid "Bad argument to kickstart network command: %s"
msgstr "キックスタートネットワークコマンドに対する引数が不正です: %s"

#: loader/net.c:1676
#, c-format
msgid "Bad bootproto %s specified in network command"
msgstr "ネットワークコマンドで不正な bootproto %s が指定されました"

#: loader/net.c:1781
msgid "Seconds:"
msgstr "2 番目:"

#: loader/net.c:1976
msgid "Networking Device"
msgstr "ネットワーク構築デバイス"

#: loader/net.c:1977
msgid ""
"You have multiple network devices on this system. Which would you like to "
"install through?"
msgstr ""
"このシステムには複数のネットワークデバイスが存在します。インストールの際に使"
"用するデバイスを選択してください。"

#: loader/net.c:1981
msgid "Identify"
msgstr "識別"

#: loader/net.c:1990
msgid "You can identify the physical port for"
msgstr "以下の為の物理ポートを識別できます"

#: loader/net.c:1992
msgid ""
"by flashing the LED lights for a number of seconds.  Enter a number between "
"1 and 30 to set the duration to flash the LED port lights."
msgstr ""
"数秒間だけ LED の光源を点滅することで達成します。１から30までの数字を挿入し"
"て LED ポートの光源を点滅する時間をセットします。"

#: loader/net.c:1999
msgid "Identify NIC"
msgstr "NIC の識別"

#: loader/net.c:2012
msgid "Invalid Duration"
msgstr "無効な期間"

#: loader/net.c:2013
msgid "You must enter the number of seconds as an integer between 1 and 30."
msgstr "１から30までの整数で秒数を入力する必要があります。"

#: loader/net.c:2025
#, c-format
msgid "Flashing %s port lights for %d seconds."
msgstr "%s ポートの光源を %d 秒だけ点滅しています。"

#: loader/net.c:2195 loader/net.c:2199
#, c-format
msgid "Waiting for NetworkManager to configure %s.\n"
msgstr "NetworkManager の %s の設定を待っています。\n"

#: loader/nfsinstall.c:93
msgid "NFS server name:"
msgstr "NFS サーバー名:"

#: loader/nfsinstall.c:97
#, c-format
msgid "%s directory:"
msgstr "%s ディレクトリー:"

#: loader/nfsinstall.c:101
msgid "NFS mount options (optional):"
msgstr "NFS マウントポイント（オプション）"

#: loader/nfsinstall.c:107
#, c-format
msgid ""
"Please enter the server and path to your %s installation image and "
"optionally additional NFS mount options."
msgstr ""
"%s インストールイメージへのパスとサーバー名を入力して、オプションとして 追加"
"の NFS マウントオプションを入力して下さい。"

#: loader/nfsinstall.c:115
msgid "NFS Setup"
msgstr "NFS 設定"

#: loader/nfsinstall.c:310
msgid "That directory could not be mounted from the server."
msgstr "そのディレクトリーはサーバーからマウントできませんでした。"

#: loader/nfsinstall.c:322
#, c-format
msgid "That directory does not seem to contain a %s installation image."
msgstr "そのディレクトリーは %s のインストールイメージを含んでいないようです。"

#: loader/nfsinstall.c:415
#, c-format
msgid "Bad argument to NFS kickstart method command: %s"
msgstr "NFS キックスタートメソッドコマンドに対する引数が不正です: %s"

#: loader/urlinstall.c:138
#, c-format
msgid "Unable to retrieve %s."
msgstr "%s の取り込みが出来ません。"

#: loader/urlinstall.c:222
msgid "Unable to retrieve the install image."
msgstr "インストールイメージを取り込むことができません。"

#: loader/urlinstall.c:375
#, c-format
msgid "Bad argument to URL kickstart method command: %s"
msgstr "URL キックスタートメソッドコマンドに対する引数が不正です: %s"

#: loader/urlinstall.c:386
msgid "Must supply a --url argument to Url kickstart method."
msgstr "Url キックスタート方法には、 --url の引数を使用する必要があります。"

#: loader/urlinstall.c:393
#, c-format
msgid "Unknown Url method %s"
msgstr "%s は不明な Url 方法です"

#: loader/urls.c:178 loader/urls.c:186
msgid "Retrieving"
msgstr "取り込み中"

#: loader/urls.c:272
#, c-format
msgid ""
"Please enter the URL containing the %s installation image on your server."
msgstr ""
"%s のインストールイメージを含んでいるサーバーの URL を入力してください。"

#: loader/urls.c:290
msgid "Enable HTTP proxy"
msgstr "HTTP プロキシを有効にする"

#: loader/urls.c:304
msgid "Proxy URL"
msgstr "プロキシ URL"

#: loader/urls.c:309
msgid "Username"
msgstr "ユーザー名"

#: loader/urls.c:314
msgid "Password"
msgstr "パスワード"

#: loader/urls.c:333
msgid "URL Setup"
msgstr "URLの設定"

#: loader/urls.c:341
msgid "You must enter a URL."
msgstr "URLを入力してください。"

#: loader/urls.c:347
msgid "URL must be either an ftp or http URL"
msgstr "URL は ftp か http のものである必要があります。"

#: loader/urls.c:356
msgid "Proxy must be either an ftp or http URL"
msgstr "Proxy は ftp か http のものである必要があります。"

#: loader/windows.c:66
msgid "Loading SCSI driver"
msgstr "SCSI ドライバーを読み込み中"

#: loader/windows.c:67
#, c-format
msgid "Loading %s driver"
msgstr "%s ドライバーを読み込み中。"

#: pyanaconda/storage/__init__.py:110
msgid "Unknown Device"
msgstr "不明なデバイス"

#: pyanaconda/storage/__init__.py:111
#, python-format
msgid ""
"The installation source given by device %s could not be found.  Please check "
"your parameters and try again."
msgstr ""
"デバイス %s で与えられたインストールソースが見付かりません。パラメータを"
"チェックして もう一度試して下さい。"

#: pyanaconda/storage/__init__.py:120
msgid "No disks found"
msgstr "ディスクが見つかりません"

#: pyanaconda/storage/__init__.py:121
msgid "No usable disks have been found."
msgstr "使用可能なディスクは見付かりません。"

#: pyanaconda/storage/__init__.py:132
msgid "Installation cannot continue."
msgstr "インストールを続行できません。"

#: pyanaconda/storage/__init__.py:133
msgid ""
"The storage configuration you have chosen has already been activated. You "
"can no longer return to the disk editing screen. Would you like to continue "
"with the installation process?"
msgstr ""
"選択されたストレージ設定は既にアクティベートされています。ここからディスク編"
"集画面に戻ることはできません。インストールプロセスを続けますか?"

#: pyanaconda/storage/__init__.py:161
msgid "Encrypt device?"
msgstr "デバイスの暗号化？"

#: pyanaconda/storage/__init__.py:162
msgid ""
"You specified block device encryption should be enabled, but you have not "
"supplied a passphrase. If you do not go back and provide a passphrase, block "
"device encryption will be disabled."
msgstr ""
"暗号化が有効になっているはずのブロックデバイスを指定しています、しかし、パス"
"フレーズが供給されていません。戻ってパスフレーズを記入しないとブロックデバイ"
"スの暗号化は無効になります。"

#: pyanaconda/storage/__init__.py:188 pyanaconda/storage/devicetree.py:99
msgid "Confirm"
msgstr "確認"

#: pyanaconda/storage/__init__.py:189
msgid ""
"The partitioning options you have selected will now be written to disk.  Any "
"data on deleted or reformatted partitions will be lost."
msgstr ""
"選択したディスク分割のオプションを書き込みます。削除及び再フォーマットする "
"パーティションにあるデータはすべて失われます。"

#: pyanaconda/storage/__init__.py:194
msgid "Go _Back"
msgstr "戻る (_B)"

#: pyanaconda/storage/__init__.py:195
msgid "_Write Changes to Disk"
msgstr "変更をディスクに書き込む (_W)"

#: pyanaconda/storage/__init__.py:214
msgid "Running..."
msgstr "実行中..."

#: pyanaconda/storage/__init__.py:215
msgid "Storing encryption keys"
msgstr "暗号化キーを格納"

#: pyanaconda/storage/__init__.py:231
#, python-format
msgid "Error storing an encryption key: %s\n"
msgstr "暗号化キーを格納中にエラー: %s\n"

#: pyanaconda/storage/__init__.py:377
msgid "Examining Devices"
msgstr "デバイスを検査中"

#: pyanaconda/storage/__init__.py:378
msgid "Examining storage devices"
msgstr "ストレージデバイスを検査中"

#: pyanaconda/storage/__init__.py:657
msgid "This partition is holding the data for the hard drive install."
msgstr ""
"このパーティションはハードディスクインストール用のデータを保有しています。"

#: pyanaconda/storage/__init__.py:662
msgid "You cannot delete a partition of a LDL formatted DASD."
msgstr "DASD 形式でフォーマットされた LDL パーティションは削除できません。"

#: pyanaconda/storage/__init__.py:668
#, python-format
msgid "This device is part of the RAID device %s."
msgstr "このデバイスは RAID デバイス %s の一部です。"

#: pyanaconda/storage/__init__.py:671
msgid "This device is part of a RAID device."
msgstr "このデバイスは RAID デバイスの一部です。"

#: pyanaconda/storage/__init__.py:676
#, python-format
msgid "This device is part of the LVM volume group '%s'."
msgstr "このデバイスは LVM ボリュームグループ %s の一部です。"

#: pyanaconda/storage/__init__.py:679
msgid "This device is part of a LVM volume group."
msgstr "このデバイスは LVM ボリュームグループの一部です。"

#: pyanaconda/storage/__init__.py:695
msgid ""
"This device is an extended partition which contains logical partitions that "
"cannot be deleted:\n"
"\n"
msgstr ""
"このデバイスは拡張パーティションです。この中の論理パーティションは先に 削除で"
"きません:\n"
"\n"

#: pyanaconda/storage/__init__.py:970
#, python-format
msgid ""
"You have not defined a root partition (/), which is required for "
"installation of %s to continue."
msgstr ""
"%s のインストールを継続するために必要な root パーティション (/) が定義されて"
"いません。"

#: pyanaconda/storage/__init__.py:975
#, python-format
msgid ""
"Your root partition is less than 250 megabytes which is usually too small to "
"install %s."
msgstr ""
"root パーティションが 250 MB 以下になっています。通常、 %s のインストールには"
"小さすぎます。"

#: pyanaconda/storage/__init__.py:981
#, python-format
msgid ""
"Your / partition is less than %(min)s MB which is lower than recommended for "
"a normal %(productName)s install."
msgstr ""
"/  パーティションは %(min)s MB 以下であり、これは通常の %(productName)s イン"
"ストールに推奨できるサイズに足りません。"

#: pyanaconda/storage/__init__.py:991
#, python-format
msgid ""
"Your / partition does not match the the live image you are installing from.  "
"It must be formatted as %s."
msgstr ""
"あなたの / パーティションはインストールしようとしているライブイメージと一致し"
"ません。%s としてフォーマットされている必要があります。"

#: pyanaconda/storage/__init__.py:998
#, python-format
msgid ""
"Your %(mount)s partition is less than %(size)s megabytes which is lower than "
"recommended for a normal %(productName)s install."
msgstr ""
"%(mount)s パーティションの容量が %(size)s MB以下であり、通常の "
"%(productName)s のインストールでの 推奨容量には不足しています。"

#: pyanaconda/storage/__init__.py:1027
msgid ""
"Installing on a USB device.  This may or may not produce a working system."
msgstr ""
"USB デバイス上にインストールしています。稼動するシステムが作成されることもあ"
"りますが、されないこともあります。"

#: pyanaconda/storage/__init__.py:1030
msgid ""
"Installing on a FireWire device.  This may or may not produce a working "
"system."
msgstr ""
"FireWire デバイス上にインストールしています。稼動するシステムが作成されること"
"もありますが、されないこともあります。"

#: pyanaconda/storage/__init__.py:1037
msgid ""
"You have not specified a swap partition.  Due to the amount of memory "
"present, a swap partition is required to complete installation."
msgstr ""
"swap パーティションが未指定です。現在のメモリー量では、インストールを完了させ"
"るには swap パーティションが必要です。"

#: pyanaconda/storage/__init__.py:1042
msgid ""
"You have not specified a swap partition.  Although not strictly required in "
"all cases, it will significantly improve performance for most installations."
msgstr ""
"swap パーティションが未指定です。すべての場合において必ず必要というわけではあ"
"りませんが、ほとんどのインストールにおいて明らかに性能を向上させます。"

#: pyanaconda/storage/__init__.py:1049
#, python-format
msgid ""
"This mount point is invalid.  The %s directory must be on the / file system."
msgstr ""
"このマウントポイントは正しくありません。%s ディレクトリーは / ファイルシステ"
"ム上になければなりません。"

#: pyanaconda/storage/__init__.py:1053
#, python-format
msgid "The mount point %s must be on a linux file system."
msgstr "マウントポイント %s は linux ファイルシステム上にある必要があります。"

#: pyanaconda/storage/__init__.py:1064
msgid "No Drives Found"
msgstr "ドライブがみつかりませんでした。"

#: pyanaconda/storage/__init__.py:1065
msgid ""
"An error has occurred - no valid devices were found on which to create new "
"file systems. Please check your hardware for the cause of this problem."
msgstr ""
"エラー発生 - 新規ファイルシステム作成のための有効なデバイスが見つかりません。"
"ハードウェアをチェックして、この問題の原因を調査してください。"

#: pyanaconda/storage/__init__.py:1363 pyanaconda/storage/__init__.py:1372
msgid "Dirty File Systems"
msgstr "損傷ファイルシステム"

#: pyanaconda/storage/__init__.py:1364
#, python-format
msgid ""
"The following file systems for your Linux system were not unmounted "
"cleanly.  Please boot your Linux installation, let the file systems be "
"checked and shut down cleanly to upgrade.\n"
"%s"
msgstr ""
"ご使用の Linux システム用の次のファイルシステムは正常にアンマウントされません"
"でした。アップグレードするには、 Linux インストールを起動し、ファイルシステム"
"のチェックをしてから正常なシャットダウンを行ってください。\n"
"%s"

#: pyanaconda/storage/__init__.py:1373
#, python-format
msgid ""
"The following file systems for your Linux system were not unmounted "
"cleanly.  Would you like to mount them anyway?\n"
"%s"
msgstr ""
"ご使用の Linux システム用の次のファイルシステムは正常にアンマウントされません"
"でした。とにかくそれらをマウントしますか?\n"
"%s"

#: pyanaconda/storage/__init__.py:1850
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"is an old-style Linux swap partition.  If you want to use this device for "
"swap space, you must reformat as a new-style Linux swap partition."
msgstr ""
"スワップデバイス:\n"
"\n"
"     %s\n"
"\n"
"は旧式の Linux swap パーティションです。スワップ領域用にこのデバイスを 使用し"
"たい場合は、新スタイルの Linux swap パーティションとして再フォーマットする必"
"要があります。"

#: pyanaconda/storage/__init__.py:1861
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"in your /etc/fstab file is currently in use as a software suspend device, "
"which means your system is hibernating. To perform an upgrade, please shut "
"down your system rather than hibernating it."
msgstr ""
"/etc/fstab ファイル内の swap デバイス:\n"
"\n"
"      %s\n"
"\n"
"は現在、ソフトウェアサスペンドデバイスとして使用されており、これはシステムが"
"ハイバネート状態であることを意味します。アップグレードを実行するには、システ"
"ムをハイバネートするのではなく、シャットダウンしてください。"

#: pyanaconda/storage/__init__.py:1869
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"in your /etc/fstab file is currently in use as a software suspend device, "
"which means your system is hibernating. If you are performing a new install, "
"make sure the installer is set to format all swap devices."
msgstr ""
"/etc/fstab ファイル内の swap デバイス:\n"
"\n"
"     %s\n"
"\n"
"は現在、ソフトウェアサスペンドデバイスとして使用されており、これはシステムが"
"ハイバネート状態であることを意味します。新規のインストールを実行している場合"
"は、インストーラーがすべての swap パーティションをフォーマットするよう設定さ"
"れていることを確認してください。"

#: pyanaconda/storage/__init__.py:1881
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"does not contain a supported swap volume.  In order to continue "
"installation, you will need to format the device or skip it."
msgstr ""
"スワップデバイス:\n"
"\n"
"     %s\n"
"\n"
"はサポートされたスワップボリュームを含みません。インストールを継続するには、 "
"デバイスをフォーマットするか、又はスキップします。"

#: pyanaconda/storage/__init__.py:1892
#, python-format
msgid ""
"Error enabling swap device %(name)s: %(msg)s\n"
"\n"
"The /etc/fstab on your upgrade partition does not reference a valid swap "
"device.\n"
"\n"
"Press OK to exit the installer"
msgstr ""
"スワップデバイス %(name)s を有効にしている際にエラー発生: %(msg)s\n"
"\n"
"アップグレードパーティションの /etc/fstab が有効なスワップデバイスを参照して"
"いません。\n"
"\n"
"OK を押してインストーラを終了してください。"

#: pyanaconda/storage/__init__.py:1899
#, python-format
msgid ""
"Error enabling swap device %(name)s: %(msg)s\n"
"\n"
"This most likely means this swap device has not been initialized.\n"
"\n"
"Press OK to exit the installer."
msgstr ""
"スワップデバイス %(name)s を有効にしている際にエラー発生: %(msg)s\n"
"\n"
"このスワップデバイスが初期化されていない可能性があります。\n"
"\n"
"OK を押してインストーラを終了してください。"

#: pyanaconda/storage/__init__.py:1962 pyanaconda/storage/__init__.py:1974
msgid "Invalid mount point"
msgstr "無効なマウントポイント"

#: pyanaconda/storage/__init__.py:1963
#, python-format
msgid ""
"An error occurred when trying to create %s.  Some element of this path is "
"not a directory. This is a fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"%s を作成中にエラーが発生しました。このパスのどこかがディレクトリーではありま"
"せん。致命的なエラーとなるためインストールを続行できません。\n"
"\n"
"<Enter> を押してインストーラを終了してください。"

#: pyanaconda/storage/__init__.py:1975
#, python-format
msgid ""
"An error occurred when trying to create %(mountpoint)s: %(msg)s.  This is a "
"fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"%(mountpoint)s を作成中にエラーが発生しました: %(msg)s。致命的な エラーとなる"
"ためインストールを続行できません。\n"
"\n"
"<Enter> を押してインストーラを終了してください。"

#: pyanaconda/storage/__init__.py:1991 pyanaconda/storage/__init__.py:2015
msgid "Unable to mount filesystem"
msgstr "ファイルシステムをマウントできません"

#: pyanaconda/storage/__init__.py:1992
#, python-format
msgid ""
"An error occurred mounting device %(path)s as %(mountpoint)s.  You may "
"continue installation, but there may be problems."
msgstr ""
"デバイス %(path)s を %(mountpoint)s としてマウントする際にエラーが発生しまし"
"た。 インストールは続行できますが、問題が生じる場合があります。"

#: pyanaconda/storage/__init__.py:2016
#, python-format
msgid ""
"An error occurred mounting device %(path)s as %(mountpoint)s: %(msg)s. This "
"is a fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"デバイス %(path)s を %(mountpoint)s としてマウント中にエラーが発生しました: "
"%(msg)s。 致命的なエラーとなるためインストールを続行できません。\n"
"\n"
"<Enter> を押してインストーラを終了してください。"

#: pyanaconda/storage/dasd.py:155
msgid "Formatting DASD Device"
msgid_plural "Formatting DASD Devices"
msgstr[0] "DASD デバイスのフォーマット"
msgstr[1] "DASD デバイスのフォーマット"

#: pyanaconda/storage/dasd.py:156
#, python-format
msgid "Preparing %d DASD device for use with Linux..."
msgid_plural "Preparing %d DASD devices for use with Linux..."
msgstr[0] "Linux での使用の為に %d 個の DASD デバイスを準備中..."
msgstr[1] "Linux での使用の為に %d 個の DASD デバイスを準備中..."

#: pyanaconda/storage/devicelibs/lvm.py:312
#, python-format
msgid "vginfo failed for %s"
msgstr "%s 用の vginfo に失敗"

#: pyanaconda/storage/devicelibs/lvm.py:341
#, python-format
msgid "lvs failed for %s"
msgstr "%s 用の lvs に失敗"

#: pyanaconda/storage/devices.py:1300 pyanaconda/storage/devices.py:1998
#: pyanaconda/storage/devices.py:2414 pyanaconda/storage/devices.py:2909
#: pyanaconda/storage/devices.py:3383
msgid "Creating"
msgstr "作成"

#: pyanaconda/storage/devices.py:1301 pyanaconda/storage/devices.py:1999
#: pyanaconda/storage/devices.py:2415 pyanaconda/storage/devices.py:2910
#, python-format
msgid "Creating device %s"
msgstr "デバイス %s の作成 "

#: pyanaconda/storage/devices.py:2508
#, python-format
msgid "A RAID%d set requires at least %d member"
msgid_plural "A RAID%d set requires at least %d members"
msgstr[0] "RAID%d セットには少なくとも %d 個のメンバーが必要です。"
msgstr[1] "RAID%d セットには少なくとも %d 個のメンバーが必要です。"

#: pyanaconda/storage/devices.py:3384
#, python-format
msgid "Creating file %s"
msgstr "ファイル %s の作成"

#: pyanaconda/storage/devicetree.py:100
#, python-format
msgid ""
"Are you sure you want to skip entering a passphrase for device %s?\n"
"\n"
"If you skip this step the device's contents will not be available during "
"installation."
msgstr ""
"本当にデバイス %s のパスフレーズの入力を省略しますか?\n"
"\n"
"このステップをスキップすると、インストール中のデバイス内のコンテンツへのアク"
"セスはできません。"

#: pyanaconda/storage/devicetree.py:1897
msgid "This partition is part of an inconsistent LVM Volume Group."
msgstr "このパーティションは一貫性のない LVM ボリュームグループの一部です。"

#: pyanaconda/storage/fcoe.py:66 pyanaconda/storage/fcoe.py:67
msgid "Connecting to FCoE SAN"
msgstr "FCoE SAN へ接続"

#: pyanaconda/storage/fcoe.py:111
msgid "FCoE not available"
msgstr "FCoE は使用できません"

#: pyanaconda/storage/formats/fs.py:102
msgid "filesystem configuration missing a type"
msgstr "ファイルシステム設定にタイプがありません。"

#: pyanaconda/storage/formats/fs.py:354 pyanaconda/storage/formats/luks.py:194
#: pyanaconda/storage/formats/lvmpv.py:103
#: pyanaconda/storage/formats/swap.py:161
msgid "Formatting"
msgstr "フォーマット中"

#: pyanaconda/storage/formats/fs.py:355
#, python-format
msgid "Creating %s filesystem on %s"
msgstr "%s 上に %s ファイルシステムを作成"

#: pyanaconda/storage/formats/fs.py:463
msgid "Resizing"
msgstr "サイズ変更"

#: pyanaconda/storage/formats/fs.py:464
#, python-format
msgid "Resizing filesystem on %s"
msgstr "%s のファイルシステムのサイズ変更"

#: pyanaconda/storage/formats/fs.py:499
#, python-format
msgid "Unknown return code: %d."
msgstr "不明な戻しコードです: %d"

#: pyanaconda/storage/formats/fs.py:513
msgid "Checking"
msgstr "チェック中"

#: pyanaconda/storage/formats/fs.py:514
#, python-format
msgid "Checking filesystem on %s"
msgstr "%s のファイルシステムを検査中。"

#: pyanaconda/storage/formats/fs.py:531
#, python-format
msgid "%(type)s filesystem check failure on %(device)s: "
msgstr "%(device)s 上で %(type)s ファイルシステムのチェックに失敗: "

#: pyanaconda/storage/formats/fs.py:537
msgid ""
"Errors like this usually mean there is a problem with the filesystem that "
"will require user interaction to repair.  Before restarting installation, "
"reboot to rescue mode or another system that allows you to repair the "
"filesystem interactively.  Restart installation after you have corrected the "
"problems on the filesystem."
msgstr ""
"このようなエラーは通常、ファイルシステムに問題があることを意味しており、 その"
"修正にはユーザーの介入を必要とします。インストールを再開始する前に レスキュー"
"モードで、又はファイルシステムを対話式で修正できる他のシステムで 再起動して下"
"さい。ファイルシステムの問題を修正してからインストールを再開始 して下さい。"

#: pyanaconda/storage/formats/fs.py:545 pyanaconda/storage/partitioning.py:282
msgid "Unrecoverable Error"
msgstr "修復不能なエラー"

#: pyanaconda/storage/formats/fs.py:889
msgid "File system errors left uncorrected."
msgstr "ファイルシステムエラーが未修正のままです。"

#: pyanaconda/storage/formats/fs.py:890
msgid "Operational error."
msgstr "操作上のエラー"

#: pyanaconda/storage/formats/fs.py:891
msgid "Usage or syntax error."
msgstr "ユーザー又は構文のエラー"

#: pyanaconda/storage/formats/fs.py:892
msgid "e2fsck cancelled by user request."
msgstr "ユーザーの指示で e2fsck がキャンセルされました。"

#: pyanaconda/storage/formats/fs.py:893
msgid "Shared library error."
msgstr "共有ライブラリのエラー"

#: pyanaconda/storage/formats/fs.py:1052
msgid ""
"Recoverable errors have been detected or dosfsck has discovered an internal "
"inconsistency."
msgstr ""
"復元可能なエラーは検出されたか、又は dosfsck が内部の整合性問題を発見しまし"
"た。"

#: pyanaconda/storage/formats/fs.py:1054
msgid "Usage error."
msgstr "使用法エラー"

#: pyanaconda/storage/formats/luks.py:48
msgid "Encrypted"
msgstr "暗号化"

#: pyanaconda/storage/formats/luks.py:195
#, python-format
msgid "Encrypting %s"
msgstr "暗号化 %s"

#: pyanaconda/storage/formats/lvmpv.py:104
#: pyanaconda/storage/formats/swap.py:162
#, python-format
msgid "Creating %s on %s"
msgstr "%s 上に %s を作成"

#: pyanaconda/storage/iscsi.py:83 pyanaconda/storage/iscsi.py:84
msgid "Scanning iSCSI nodes"
msgstr "iSCSI ノードをスキャン中"

#: pyanaconda/storage/iscsi.py:135
msgid "Unable to change iSCSI initiator name once set"
msgstr "iSCSI イニシエータ名はセットされた後は変更できません"

#: pyanaconda/storage/iscsi.py:137
msgid "Must provide an iSCSI initiator name"
msgstr "iSCSI イニシエーター名を入力しなければなりません"

#: pyanaconda/storage/iscsi.py:177 pyanaconda/storage/iscsi.py:178
msgid "Initializing iSCSI initiator"
msgstr "iSCSI イニシエーターの初期化中"

#: pyanaconda/storage/iscsi.py:214
msgid "iSCSI not available"
msgstr "iSCSI は使用できません"

#: pyanaconda/storage/iscsi.py:216
msgid "No initiator name set"
msgstr "イニシエーター名がありません"

#: pyanaconda/storage/iscsi.py:230
msgid "No iSCSI nodes discovered"
msgstr "iSCSI ノードが見付かりません"

#: pyanaconda/storage/iscsi.py:233 pyanaconda/storage/iscsi.py:234
msgid "Logging in to iSCSI nodes"
msgstr "iSCSI ノードにログイン中"

#: pyanaconda/storage/iscsi.py:260
msgid "No new iSCSI nodes discovered"
msgstr "新しい iSCSI ノードは見付かりません"

#: pyanaconda/storage/iscsi.py:263
msgid "Could not log in to any of the discovered nodes"
msgstr "見付かったノードのいずれにもログインできませんでした"

#: pyanaconda/storage/partitioning.py:197
msgid ""
"Could not find enough free space for automatic partitioning.  Press 'OK' to "
"exit the installer."
msgstr ""
"自動パーティション設定用に十分な空き領域が見付かりません。インストーラーを抜"
"け出すには'OK'を押してください。"

#: pyanaconda/storage/partitioning.py:200
msgid ""
"Could not find enough free space for automatic partitioning, please use "
"another partitioning method."
msgstr ""
"自動パーティション設定用に十分な空き領域が見付かりません。別の パーティション"
"メソッドを使用して下さい。"

#: pyanaconda/storage/partitioning.py:229
msgid "Warnings During Automatic Partitioning"
msgstr "自動パーティション設定中の警告"

#: pyanaconda/storage/partitioning.py:231
#, python-format
msgid ""
"Following warnings occurred during automatic partitioning:\n"
"\n"
"%s"
msgstr ""
"自動パーティション設定中に次の警告が発生しました:\n"
"\n"
"%s"

#: pyanaconda/storage/partitioning.py:245
#: pyanaconda/storage/partitioning.py:266
msgid ""
"\n"
"\n"
"Press 'OK' to exit the installer."
msgstr ""
"\n"
"\n"
"「OK」を押すとインストーラを終了します。"

#: pyanaconda/storage/partitioning.py:247
#, python-format
msgid ""
"Could not allocate requested partitions: \n"
"\n"
"%(msg)s.%(extra)s"
msgstr ""
"要求されたパーティションを割り当てできませんでした: \n"
"\n"
"%(msg)s.%(extra)s"

#: pyanaconda/storage/partitioning.py:268
msgid ""
"\n"
"\n"
"Press 'OK' to choose a different partitioning option."
msgstr ""
"\n"
"\n"
"「OK」を押して別のパーティション設定オプションを選択してください。"

#: pyanaconda/storage/partitioning.py:270
msgid "Automatic Partitioning Errors"
msgstr "自動パーティション設定のエラーです"

#: pyanaconda/storage/partitioning.py:271
#, python-format
msgid ""
"The following errors occurred with your partitioning:\n"
"\n"
"%(errortxt)s\n"
"\n"
"This can happen if there is not enough space on your hard drive(s) for the "
"installation. %(extra)s"
msgstr ""
"パーティション作成に次のエラーが発生しました:\n"
"\n"
"%(errortxt)s\n"
"\n"
"このエラーは、インストール用に十分な領域がハードディスク上にない場合に発生し"
"ます。%(extra)s"

#: pyanaconda/storage/zfcp.py:51
msgid "You have not specified a device number or the number is invalid"
msgstr "デバイス番号を指定していないか番号が無効です。"

#: pyanaconda/storage/zfcp.py:53
msgid "You have not specified a worldwide port name or the name is invalid."
msgstr "WWPN を指定していないか、そのポート名が無効です。"

#: pyanaconda/storage/zfcp.py:55
msgid "You have not specified a FCP LUN or the number is invalid."
msgstr "FCP FUN を指定していないか、番号が無効です。"

#: pyanaconda/storage/zfcp.py:133
#, python-format
msgid "zFCP device %s not found, not even in device ignore list."
msgstr "zFCP デバイス %s が見つからず、デバイス無理リストにもありません。"

#: pyanaconda/storage/zfcp.py:143
#, python-format
msgid "Could not set zFCP device %(devnum)s online (%(e)s)."
msgstr ""
"zFCP デバイス %(devnum)s を オンライン (%(e)s) にセットできませんでした。"

#: pyanaconda/storage/zfcp.py:154
#, python-format
msgid "Could not add WWPN %(wwpn)s to zFCP device %(devnum)s (%(e)s)."
msgstr "WWPN %(wwpn)s を zFCP デバイス %(devnum)s (%(e)s) に追加できません。"

#: pyanaconda/storage/zfcp.py:161
#, python-format
msgid "WWPN %(wwpn)s not found at zFCP device %(devnum)s."
msgstr "WWPN %(wwpn)s が zFCP デバイス %(devnum)s で見つかりません。"

#: pyanaconda/storage/zfcp.py:176
#, python-format
msgid ""
"Could not add LUN %(fcplun)s to WWPN %(wwpn)s on zFCP device %(devnum)s "
"(%(e)s)."
msgstr ""
"LUN %(fcplun)s を zFCP デバイス %(devnum)s (%(e)s)上で WWPN %(wwpn)s に追加で"
"きません、。"

#: pyanaconda/storage/zfcp.py:182
#, python-format
msgid ""
"LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s already configured."
msgstr ""
"LUN %(fcplun)s は、zFCP デバイス %(devnum)s 上の WWPN %(wwpn)s で既に設定され"
"ています。"

#: pyanaconda/storage/zfcp.py:194
#, python-format
msgid ""
"Could not read failed attribute of LUN %(fcplun)s at WWPN %(wwpn)s on zFCP "
"device %(devnum)s (%(e)s)."
msgstr ""
"zFCP デバイス %(devnum)s (%(e)s) 上の WWPN %(wwpn)s で LUN %(fcplun)s の 失敗"
"属性を読みこむことが できませんでした。"

#: pyanaconda/storage/zfcp.py:203
#, python-format
msgid ""
"Failed LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s removed "
"again."
msgstr ""
"zFCP デバイス %(devnum)s 上の WWPN %(wwpn)s で失敗した LUN %(fcplun)s が 再度"
"削除されました。"

#: pyanaconda/storage/zfcp.py:260
#, python-format
msgid ""
"Could not correctly delete SCSI device of zFCP %(devnum)s %(wwpn)s "
"%(fcplun)s (%(e)s)."
msgstr ""
"zFCP %(devnum)s %(wwpn)s %(fcplun)s (%(e)s) の SCSI デバイスを正しく消すこと"
"ができませんでした。"

#: pyanaconda/storage/zfcp.py:269
#, python-format
msgid ""
"Could not remove LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s "
"(%(e)s)."
msgstr ""
"zFCP デバイス %(devnum)s (%(e)s) 上の WWPN %(wwpn)s で LUN %(fcplun)s を削除"
"できませんでした。"

#: pyanaconda/storage/zfcp.py:287
#, python-format
msgid "Could not remove WWPN %(wwpn)s on zFCP device %(devnum)s (%(e)s)."
msgstr ""
"zFCP デバイス %(devnum)s (%(e)s) 上で WWPN %(wwpn)s を削除できませんでした。"

#: pyanaconda/storage/zfcp.py:313
#, python-format
msgid "Could not set zFCP device %(devnum)s offline (%(e)s)."
msgstr "zFCP デバイス %(devnum)s をオフライン (%(e)s) に設定できませんでした。"

#: pyanaconda/textw/complete_text.py:32
msgid "Reboot"
msgstr "再起動する"

#: pyanaconda/textw/complete_text.py:34
msgid "<Enter> to exit"
msgstr "<Enter> を押して終了します"

#: pyanaconda/textw/complete_text.py:62
msgid "Complete"
msgstr "完了"

#: pyanaconda/textw/keyboard_text.py:48
msgid "Keyboard Selection"
msgstr "キーボードの選択"

#: pyanaconda/textw/keyboard_text.py:49
msgid "Which model keyboard is attached to this computer?"
msgstr "このコンピューターに接続されるキーボードのモデルを指定してください。"

#: pyanaconda/textw/netconfig_text.py:43
#, python-format
msgid "A value is required for the field %s"
msgstr "フィールド %s 用に値が必要です。"

#: pyanaconda/textw/netconfig_text.py:126
#: pyanaconda/textw/netconfig_text.py:152 data/ui/netconfig.glade.h:9
msgid "Enable network interface"
msgstr "ネットワークインターフェースを有効にする"

#: pyanaconda/textw/netconfig_text.py:129
msgid ""
"This requires that you have an active network connection during the "
"installation process.  Please select network interface to configure."
msgstr ""
"この操作を行うにはインストール中に有効なネットワーク接続が必要になります。"
"ネットワークインターフェースを設定してください。"

#: pyanaconda/textw/netconfig_text.py:155
#, python-format
msgid "Configure interface %s to be used during installation process."
msgstr ""
"インストール時に使用するネットワークインタフェース(%s)を設定してください。"

#: pyanaconda/textw/netconfig_text.py:160
msgid "Enable IPv4 Support"
msgstr "IPv4 サポートを有効にする"

#: pyanaconda/textw/netconfig_text.py:167
#: pyanaconda/textw/netconfig_text.py:207
msgid "Manual Configuration"
msgstr "手動による設定"

#: pyanaconda/textw/netconfig_text.py:175
msgid "IPv4 Address:"
msgstr "IPv4 アドレス:"

#: pyanaconda/textw/netconfig_text.py:189
#: pyanaconda/textw/netconfig_text.py:229
msgid "Nameserver:"
msgstr "ネームサーバー:"

#: pyanaconda/textw/netconfig_text.py:197
msgid "Enable IPv6 Support"
msgstr "IPv6 サポートを有効にする"

#: pyanaconda/textw/netconfig_text.py:204
msgid "Dynamic IP Configuration (DHCPv6)"
msgstr "動的 IP 設定 (DHCPv6)"

#: pyanaconda/textw/netconfig_text.py:215
msgid "IPv6 Address:"
msgstr "IPv6 アドレス:"

#: pyanaconda/textw/netconfig_text.py:270
msgid "Missing protocol"
msgstr "見つからないプロトコル"

#: pyanaconda/textw/netconfig_text.py:271
msgid "You must select at least one protocol version"
msgstr "最低でもプロトコルを1つ選択する必要があります (IPv4 または IPv6)"

#: pyanaconda/textw/netconfig_text.py:279
#: pyanaconda/textw/netconfig_text.py:282
msgid "IPv4 Address"
msgstr "IPv4 アドレス"

#: pyanaconda/textw/netconfig_text.py:286
#: pyanaconda/textw/netconfig_text.py:291
msgid "IPv4 Prefix"
msgstr "IPv4 無効なプレフィックス"

#: pyanaconda/textw/netconfig_text.py:298
msgid "IPv4 Gateway"
msgstr "IPv4 ゲートウェイ"

#: pyanaconda/textw/netconfig_text.py:307
msgid "IPv4 Nameserver"
msgstr "IPv4 ネームサーバー"

#: pyanaconda/textw/netconfig_text.py:315
#: pyanaconda/textw/netconfig_text.py:318
msgid "IPv6 Address"
msgstr "IPv6 アドレス"

#: pyanaconda/textw/netconfig_text.py:322
#: pyanaconda/textw/netconfig_text.py:327
msgid "IPv6 Prefix"
msgstr "IPv6 無効なプレフィックス"

#: pyanaconda/textw/netconfig_text.py:326
msgid "IPv6 CIDR prefix must be between 0 and 128."
msgstr "IPv6 CIDR のプレフィックスは 0 から 128 の間にしてください。"

#: pyanaconda/textw/netconfig_text.py:334
msgid "IPv6 Gateway"
msgstr "IPv6 ゲートウェイ"

#: pyanaconda/textw/netconfig_text.py:342
msgid "IPv6 Nameserver"
msgstr "IPv6 ネームサーバー"

#: pyanaconda/textw/netconfig_text.py:399
msgid "Configuring Network Interfaces"
msgstr "ネットワークインターフェースを設定"

#: pyanaconda/textw/netconfig_text.py:404
#, python-format
msgid "There was an error configuring network device %s"
msgstr "ネットワークインターフェース(%s)の設定中にエラーが発生しました。"

#: pyanaconda/textw/partition_text.py:59
msgid "Partitioning Type"
msgstr "パーティションタイプ"

#: pyanaconda/textw/partition_text.py:61
msgid ""
"Installation requires partitioning of your hard drive.  The default layout "
"is suitable for most users.  Select what space to use and which drives to "
"use as the install target."
msgstr ""
"インストールにはハードディスクのパーティション設定が必要です。デフォルトのレ"
"イアウトはほとんどのユーザーに適しています。使用する領域と使用するドライブを "
"インストールのターゲットとして選択します。"

#: pyanaconda/textw/partition_text.py:64
msgid "Use entire drive"
msgstr "ドライブ全域を使用"

#: pyanaconda/textw/partition_text.py:65
msgid "Replace existing Linux system"
msgstr "既存の Linux システムを入れ替え"

#: pyanaconda/textw/partition_text.py:66
msgid "Use free space"
msgstr "空き領域を使用"

#: pyanaconda/textw/partition_text.py:81
msgid "Which drive(s) do you want to use for this installation?"
msgstr "このインストールに使用するドライブを指定してください。"

#: pyanaconda/textw/partition_text.py:96
msgid "<Space>,<+>,<-> selection   |   <F2> Add drive   |   <F12> next screen"
msgstr "<Space>,<+>,<-> 選択   |   <F2> ドライブの追加   |   <F12> 次の画面"

#: pyanaconda/textw/progress_text.py:46
msgid "Package Installation"
msgstr "パッケージのインストール"

#: pyanaconda/textw/timezone_text.py:74
msgid "In which time zone are you located?"
msgstr "どのタイムゾーンに位置しますか?"

#: pyanaconda/textw/timezone_text.py:92
msgid "System clock uses UTC"
msgstr "このコンピュータはシステムクロックに世界標準時間(UTC)を使用します。"

#: pyanaconda/textw/upgrade_bootloader_text.py:111
#: pyanaconda/textw/upgrade_bootloader_text.py:121
msgid "Update boot loader configuration"
msgstr "ブートローダー設定の更新"

#: pyanaconda/textw/upgrade_bootloader_text.py:124
msgid "Skip boot loader updating"
msgstr "ブートローダー更新のスキップ"

#: pyanaconda/textw/upgrade_text.py:125
msgid "Free Space"
msgstr "空き領域"

#: pyanaconda/textw/upgrade_text.py:143
msgid "RAM detected (MB):"
msgstr "検出された RAM 容量 (MB):"

#: pyanaconda/textw/upgrade_text.py:146
msgid "Suggested size (MB):"
msgstr "推奨容量 (MB):"

#: pyanaconda/textw/upgrade_text.py:149
msgid "Swap file size (MB):"
msgstr "swap ファイル容量 (MB):"

#: pyanaconda/textw/upgrade_text.py:157
msgid "Add Swap"
msgstr "swap の追加"

#: pyanaconda/textw/upgrade_text.py:182
msgid "The value you entered is not a valid number."
msgstr "入力した値は無効な数です。"

#: pyanaconda/textw/upgrade_text.py:214
msgid "Reinstall System"
msgstr "システムの再インストール"

#: pyanaconda/textw/upgrade_text.py:226
msgid "System to Upgrade"
msgstr "アップグレード対象システム"

#: pyanaconda/textw/upgrade_text.py:227
msgid ""
"There seem to be one or more existing Linux installations on your system.\n"
"\n"
"Please choose one to upgrade, or select 'Reinstall System' to freshly "
"install your system."
msgstr ""
"システム上に 既存の Linux インストールがひとつ以上あるようです。\n"
"\n"
"アップグレードするにはひとつを選び、新規にシステムをインストールするには、"
"「システムの再インストール」を選んでください。"

#: pyanaconda/textw/userauth_text.py:30
msgid "Root Password"
msgstr "root パスワード"

#: pyanaconda/textw/userauth_text.py:33
msgid ""
"Pick a root password. You must type it twice to ensure you know it and do "
"not make a typing mistake. "
msgstr ""
"root パスワードを設定してください。パスワードを2回入力することで、パスワード"
"を覚えていて、タイプミスがないことを確認します。"

#: pyanaconda/textw/userauth_text.py:67
msgid "The root password must be at least 6 characters long."
msgstr "root パスワードは 6 文字以上にしてください。"

#: pyanaconda/textw/userauth_text.py:84
#, python-format
msgid ""
"You have provided a weak password: %s\n"
"\n"
"Would you like to continue with this password?"
msgstr ""
"弱いパスワードが与えられました: %s\n"
"\n"
"このパスワードで続けますか?"

#: pyanaconda/textw/welcome_text.py:29
#, python-format
msgid "%s"
msgstr "%s"

#: pyanaconda/textw/welcome_text.py:30
#, python-format
msgid ""
"Welcome to %s!\n"
"\n"
msgstr ""
"%s へようこそ!\n"
"\n"

#: pyanaconda/textw/zipl_text.py:36
msgid ""
"The z/IPL Boot Loader will be installed on your system after installation is "
"complete. You can now enter any additional kernel and chandev parameters "
"which your machine or your setup require."
msgstr ""
"z/IPL ブートローダーはインストールが完了してからシステム上にインストールされ"
"ます。ここで、ご使用のマシンまたは設定が必要とする追加のカーネル及び chandev "
"パラメーターを入力することができます。"

#: pyanaconda/textw/zipl_text.py:68
msgid "z/IPL Configuration"
msgstr "z/IPL の設定"

#: pyanaconda/textw/zipl_text.py:76 pyanaconda/textw/zipl_text.py:80
msgid "Chandev line "
msgstr "Chandev 行"

#: data/liveinst/liveinst.desktop.in.h:1
msgid "Install"
msgstr "インストール"

#: data/liveinst/liveinst.desktop.in.h:2
msgid "Install the live CD to your hard disk"
msgstr "ライブ ディスク をハードディスクにインストール"

#: data/liveinst/liveinst.desktop.in.h:3
msgid "Install to Hard Drive"
msgstr "ハードディスクにインストール"

#: liveinst:5
msgid "Starting Install to Hard Drive"
msgstr "ハードディスクへのインストールを開始します"

#: data/ui/GroupSelector.glade.h:1
msgid ""
"Some packages associated with this group are not required to be installed "
"but may provide additional functionality.  Please choose the packages which "
"you would like to have installed."
msgstr ""
"このグループに関連付けられるいくつかのパッケージは、インストールする必要があ"
"りません。しかし、インストールすることによって追加機能を提供します。どのパッ"
"ケージをインストールするか選択してください。"

#: data/ui/GroupSelector.glade.h:2
msgid "_Deselect"
msgstr "選択解除 (_D)"

#: data/ui/GroupSelector.glade.h:3
msgid "_Deselect all optional packages"
msgstr "すべての追加パッケージの選択を解除 (_D)"

#: data/ui/GroupSelector.glade.h:4
msgid "_Optional packages"
msgstr "追加パッケージ (_O)"

#: data/ui/GroupSelector.glade.h:5
msgid "_Select"
msgstr "選択 (_S)"

#: data/ui/GroupSelector.glade.h:6
msgid "_Select all optional packages"
msgstr "すべての追加パッケージを選択 (_S)"

#: data/ui/GroupSelector.glade.h:7
msgid "dialog1"
msgstr "ダイアログ1"

#: data/ui/account.glade.h:1
msgid "Confirm:"
msgstr "確認:"

#: data/ui/account.glade.h:2
msgid "Root Password:"
msgstr "root パスワード:"

#: data/ui/account.glade.h:3
msgid ""
"The root account is used for administering the system.  Enter a password for "
"the root user."
msgstr ""
"root ユーザーはシステムの管理用に使用します。 root ユーザーのパスワードを入力"
"してください。"

#: data/ui/adddrive.glade.h:1
msgid "Add _FCoE SAN"
msgstr "FCoE SAN を追加(_F)"

#: data/ui/adddrive.glade.h:2
msgid "Add _ZFCP LUN"
msgstr "_ZFCP LUN を追加 (_Z)"

#: data/ui/adddrive.glade.h:3
msgid "Add _iSCSI target"
msgstr "iSCSI ターゲットを追加 (_I)"

#: data/ui/adddrive.glade.h:4
msgid "Advanced Storage Options"
msgstr "高度なストレージオプション"

#: data/ui/adddrive.glade.h:5
msgid "How would you like to modify your drive configuration?"
msgstr "どのように使用中のドライブ設定を変更したいですか？"

#: data/ui/adddrive.glade.h:6
msgid "_Add drive"
msgstr "ドライブ追加 (_A)"

#: data/ui/addrepo.glade.h:1
msgid "<b>Repository _name:</b>"
msgstr "<b>リポジトリー名(_N):</b>"

#: data/ui/addrepo.glade.h:2
msgid "<b>Repository _type:</b>"
msgstr "<b>リポジトリータイプ(_T):</b>"

#: data/ui/addrepo.glade.h:4
msgid "Configure _proxy"
msgstr "プロキシーの設定 (_P) "

#: data/ui/addrepo.glade.h:5
msgid ""
"HTTP/FTP\n"
"CD/DVD\n"
"NFS\n"
"Hard Drive"
msgstr ""
"HTTP/FTP\n"
"CD/DVD\n"
"NFS\n"
"Hard Drive"

#: data/ui/addrepo.glade.h:9
msgid ""
"Please provide the configuration information for this software repository."
msgstr "このソフトウェアリポジトリーの設定情報を入力してください。"

#: data/ui/addrepo.glade.h:10
msgid "Proxy U_RL (host:port)"
msgstr "プロキシー U_RL (ホスト:ポート)"

#: data/ui/addrepo.glade.h:11
msgid "Proxy pass_word"
msgstr "プロキシーのパスワード (_W)"

#: data/ui/addrepo.glade.h:12
msgid "Proxy u_sername"
msgstr "プロキシーのユーザー名 (_S)"

#: data/ui/addrepo.glade.h:13
msgid "Repository _URL"
msgstr "リポジトリーの URL (_U)"

#: data/ui/addrepo.glade.h:14
msgid "Select A Directory"
msgstr "ディレクトリーを選択してください"

#: data/ui/addrepo.glade.h:15
msgid "URL is a _mirror list"
msgstr "URL は _mirror list です。"

#: data/ui/addrepo.glade.h:16
msgid "_Directory"
msgstr "ディレクトリー(_D)"

#: data/ui/addrepo.glade.h:17
msgid "_Options"
msgstr "オプション(_O)"

#: data/ui/addrepo.glade.h:18
msgid "_Partition"
msgstr "パーティション(_P)"

#: data/ui/addrepo.glade.h:19
msgid "_Path"
msgstr "パス(_P)"

#: data/ui/addrepo.glade.h:20
msgid "_Server"
msgstr "サーバー(_S)"

#: data/ui/anaconda.glade.h:1
msgid "Reboo_t"
msgstr "再起動(_T)"

#: data/ui/anaconda.glade.h:4
msgid "_Next"
msgstr "次(_N)"

#: data/ui/autopart.glade.h:1
msgid "<b>Shrink partition _to size (in MB):</b>"
msgstr "<b>このサイズ(MB)までパーティションを縮小(_T):</b>"

#: data/ui/autopart.glade.h:2
msgid "Re_view and modify partitioning layout"
msgstr "パーティションのレイアウトをレビューまたは修正(_V)"

#: data/ui/autopart.glade.h:3
msgid "Volume to Shrink"
msgstr "縮小する量"

#: data/ui/autopart.glade.h:4
msgid ""
"Which partition would you like to shrink to make room for your installation?"
msgstr ""
"インストールするための空きを作るために、どのパーティションを縮小しますか?"

#: data/ui/autopart.glade.h:5
msgid "Which type of installation would you like?"
msgstr "どのタイプのインストールをしますか ?"

#: data/ui/autopart.glade.h:6
msgid "_Encrypt system"
msgstr "システムを暗号化する (_E)"

#: data/ui/autopart.glade.h:7
msgid "_Shrink"
msgstr "縮小"

#: data/ui/blwhere.glade.h:1
msgid "/boot"
msgstr "/boot"

#: data/ui/blwhere.glade.h:2
msgid "BIOS Drive Order"
msgstr "BIOS ドライブ順"

#: data/ui/blwhere.glade.h:3
msgid "Boot loader device"
msgstr "ブートローダーデバイス"

#: data/ui/blwhere.glade.h:4
msgid "First BIOS drive:"
msgstr "第一 BIOS ドライブ:"

#: data/ui/blwhere.glade.h:5
msgid "Fourth BIOS drive:"
msgstr "第四 BIOS ドライブ:"

#: data/ui/blwhere.glade.h:6
msgid "MBR"
msgstr "MBR"

#: data/ui/blwhere.glade.h:7
msgid "Second BIOS drive:"
msgstr "第二 BIOS ドライブ:"

#: data/ui/blwhere.glade.h:8
msgid "Third BIOS drive:"
msgstr "第三 BIOS ドライブ:"

#: data/ui/blwhere.glade.h:9
msgid "Where would you like to install the boot loader for your system?"
msgstr "ブートローダーのインストール場所を指定してください。"

#: data/ui/cleardisks.glade.h:1
msgid "<b>Data Storage Devices</b> (to be mounted only)"
msgstr "<b>データストレージデバイス</b> (マウントのみ)"

#: data/ui/cleardisks.glade.h:2
msgid "<b>Install Target Devices</b>"
msgstr "<b>インストール先のデバイス</b>"

#: data/ui/cleardisks.glade.h:3
msgid ""
"<b>Tip:</b> Install target devices will be reformatted and wiped of any "
"data.  Make sure you have backups."
msgstr ""
"<b>ヒント:</b> インストール先のデバイスは再フォーマットされてデータは抹消され"
"ます。 バックアップがあることを確認して下さい。"

#: data/ui/cleardisks.glade.h:4
msgid ""
"Below are the storage devices you've selected to be a part of this "
"installation.  Please indicate using the arrows below which devices you'd "
"like to use as data devices (these will not be formatted, only mounted) and "
"which devices you'd like to use as installation target devices (these may be "
"formatted).  Please also indicate which system drive will have the "
"bootloader installed."
msgstr ""
"このインストールの一部として選択したストレージデバイスを以下に示します。 以下"
"の矢印を使用してデータデバイスとして使用したいデバイス（これらはフォーマット"
"されずにマウントされるだけ）と インストール先デバイスとして使用したいデバイス"
"（これらはフォーマットできます）を示して下さい。また、ブートローダをインス"
"トールするシステムドライブも示して下さい。"

#: data/ui/create-storage.glade.h:1
msgid ""
"<span size=\"small\" color=\"gray\">Create a RAID formatted partition</span>"
msgstr ""
"<span size=\"small\" color=\"gray\">RAID フォーマットをしたパーティションを作"
"成</span>"

#: data/ui/create-storage.glade.h:2
msgid ""
"<span size=\"small\" color=\"gray\">Create a logical volume on selected "
"volume group</span>"
msgstr ""
"<span size=\"small\" color=\"gray\">選択したボリュームグループ上に論理ボ"
"リュームを作成 </span>"

#: data/ui/create-storage.glade.h:3
msgid ""
"<span size=\"small\" color=\"gray\">Create an LVM formatted partition</span>"
msgstr ""
"<span size=\"small\" color=\"gray\">LVM フォーマットしたパーティションを作成"
"</span>"

#: data/ui/create-storage.glade.h:4
msgid ""
"<span size=\"small\" color=\"gray\">General purpose partition creation</span>"
msgstr ""
"<span size=\"small\" color=\"gray\">汎用目的のパーティションを作成</span>"

#: data/ui/create-storage.glade.h:5
msgid ""
"<span size=\"small\" color=\"gray\">Requires at least 1 free LVM formatted "
"partition</span>"
msgstr ""
"<span size=\"small\" color=\"gray\">最低でも１つの LVM フォーマットの空きパー"
"ティションが必要</span>"

#: data/ui/create-storage.glade.h:6
msgid ""
"<span size=\"small\" color=\"gray\">Requires at least 2 free RAID formatted "
"partitions</span>"
msgstr ""
"<span size=\"small\" color=\"gray\">最低でも２つの RAID フォーマットの空き"
"パーティションが必要</span>"

#: data/ui/create-storage.glade.h:7
msgid "C_reate"
msgstr "作成する (_R)"

#: data/ui/create-storage.glade.h:8
msgid "Create LVM"
msgstr "LVM を作成"

#: data/ui/create-storage.glade.h:9
msgid "Create Partition"
msgstr "パーティションを作成"

#: data/ui/create-storage.glade.h:10
msgid "Create Software RAID"
msgstr "ソフトウェア RAID を作成"

#: data/ui/create-storage.glade.h:11
msgid "Create Storage"
msgstr "ストレージを作成"

#: data/ui/create-storage.glade.h:12
msgid "LVM Logical Volume"
msgstr "LVM 論理ボリューム"

#: data/ui/create-storage.glade.h:13
msgid "LVM Physical Volume"
msgstr "LVM 物理ボリューム"

#: data/ui/create-storage.glade.h:14
msgid "LVM Volume Group"
msgstr "LVM ボリュームグループ"

#: data/ui/create-storage.glade.h:16
msgid "RAID Partition"
msgstr "RAID パーティション"

#: data/ui/create-storage.glade.h:17
msgid "Standard Partition"
msgstr "標準パーティション"

#: data/ui/detailed-dialog.glade.h:1
msgid "Info"
msgstr "情報"

#: data/ui/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "詳細 (_D)"

#: data/ui/fcoe-config.glade.h:1
msgid "Configure FCoE Parameters"
msgstr "FCoE パラメータの設定"

#: data/ui/fcoe-config.glade.h:2
msgid "NIC:"
msgstr "NIC:"

#: data/ui/fcoe-config.glade.h:3
msgid ""
"Please select the network interface which is connected to\n"
"your FCoE switch."
msgstr ""
"使用する FCoE スイッチに接続されているネットワークインターフェイス \n"
"を選択して下さい。"

#: data/ui/fcoe-config.glade.h:5
msgid "Use DCB"
msgstr "DCB の使用"

#: data/ui/fcoe-config.glade.h:6
msgid "_Add FCoE Disk(s)"
msgstr "FCoE ディスクの追加(_A)"

#: data/ui/filter.glade.h:1
msgid ""
"<b>Tip:</b> Selected drives will not be formatted unless you choose to do so "
"later during installation.  Also, note that post-installation you may mount "
"drives you did not select here by modifying your /etc/fstab file."
msgstr ""
"<b>ヒント:</b> 選択したドライブは、インストール中にフォーマットを選択していな"
"い 限りはフォーマットされません。また、ここで選択していなかったドライブを、イ"
"ンストール後に /etc/fstab の修正によりマウントできることに注意して下さい。"

#: data/ui/filter.glade.h:2
msgid "Add Advanced Target"
msgstr "高度なターゲットの追加"

#: data/ui/filter.glade.h:3
msgid "Basic Devices"
msgstr "基本デバイス"

#: data/ui/filter.glade.h:4
msgid "Filter By:"
msgstr "フィルター項目:"

#: data/ui/filter.glade.h:5
msgid "Firmware RAID"
msgstr "ファームウェア RAID"

#: data/ui/filter.glade.h:6
msgid "Identifier:"
msgstr "識別子:"

#: data/ui/filter.glade.h:7
msgid ""
"Interconnect\n"
"Vendor\n"
"Identifier"
msgstr ""
"相互接続\n"
"ベンダー\n"
"識別子"

#: data/ui/filter.glade.h:10
msgid "LUN:"
msgstr "LUN:"

#: data/ui/filter.glade.h:11
msgid "Multipath Devices"
msgstr "マルチパスデバイス"

#: data/ui/filter.glade.h:12
msgid "Other SAN Devices"
msgstr "他の SAN デバイス"

#: data/ui/filter.glade.h:13
msgid ""
"Please select the drives you'd like to install the operating system on, as "
"well as any drives you'd like to automatically mount on your system:"
msgstr ""
"オペレーティングシステムのインストール先となるデバイスを選択して下さい。更に"
"は システムに自動的にマウントするいずれかのドライブも選択してください:"

#: data/ui/filter.glade.h:14
msgid ""
"Port / Target / LUN\n"
"Target Identifier"
msgstr ""
"ポート / ターゲット / LUN\n"
"ターゲット識別子"

#: data/ui/filter.glade.h:16
msgid "Port:"
msgstr "ポート:"

#: data/ui/filter.glade.h:17
msgid "Search"
msgstr "検索"

#: data/ui/filter.glade.h:18
msgid "Search By:"
msgstr "検索項目:"

#: data/ui/filter.glade.h:19
msgid "Search Results:"
msgstr "検索結果:"

#: data/ui/filter.glade.h:21
#, no-c-format
msgid "Selected devices: %s (%s) out of %s (%s)."
msgstr "選択したデバイス: %s (%s) の内の %s (%s)"

#: data/ui/filter.glade.h:22
msgid "Show Identifiers that Include:"
msgstr "以下を含む識別子を表示します:"

#: data/ui/filter.glade.h:23
msgid "Show Only Devices From:"
msgstr "以下からのデバイスのみを表示します:"

#: data/ui/filter.glade.h:24
msgid "Show Only Devices Using:"
msgstr "以下を使用したデバイスのみを表示します:"

#: data/ui/filter.glade.h:25
msgid "Target:"
msgstr "ターゲット:"

#: data/ui/iscsi-config.glade.h:1
msgid "<b>CHAP _Password:</b>"
msgstr "<b>CHAP パスワード (_P):</b>"

#: data/ui/iscsi-config.glade.h:2
msgid "<b>CHAP _Username:</b>"
msgstr "<b>CHAP ユーザー名 (_U):</b>"

#: data/ui/iscsi-config.glade.h:3
msgid "<b>Reverse CHAP P_assword:</b>"
msgstr "<b>逆順 CHAP パスワード (_A):</b>"

#: data/ui/iscsi-config.glade.h:4
msgid "<b>Reverse CHAP U_sername:</b>"
msgstr "<b>逆順 CHAP ユーザー名 (_S):</b>"

#: data/ui/iscsi-config.glade.h:5
msgid "<b>_Target IP Address:</b>"
msgstr "<b>ターゲット IP アドレス(_T):</b>"

#: data/ui/iscsi-config.glade.h:6
msgid "<b>iSCSI Initiator _Name:</b>"
msgstr "<b>iSCSI イニシエーター名(_N):</b>"

#: data/ui/iscsi-config.glade.h:7
msgid "Configure iSCSI Parameters"
msgstr "iSCSI パラメーターの設定"

#: data/ui/iscsi-config.glade.h:8
msgid ""
"To use iSCSI disks, you must provide the address of your iSCSI target and "
"the iSCSI initiator name you've configured for your host."
msgstr ""
"iSCSI ディスクを使用するには、ホスト用に設定している iSCSI イニシエーター名及"
"びiSCSI ターゲットのアドレスを入力してください。"

#: data/ui/iscsi-config.glade.h:9
msgid "_Add target"
msgstr "ターゲットの追加 (_A)"

#: data/ui/lukspassphrase.glade.h:1
msgid ""
"Also add this passphrase to all existing encrypted devices to streamline the "
"boot process"
msgstr ""
"暗号化済みの全ての既存デバイスにこのパスフレーズを追加して、ブートプロセスを"
"スムーズにします。"

#: data/ui/lukspassphrase.glade.h:2
msgid ""
"Choose a passphrase for this encrypted partition. You will be prompted for "
"the passphrase during system boot."
msgstr ""
"暗号化されたデバイス用のパスフレーズを選択してください。システムのブート中に"
"選択したパスフレーズの入力を求められます。"

#: data/ui/lukspassphrase.glade.h:3
msgid "Confirm passphrase:"
msgstr "パスフレーズの確認:"

#: data/ui/lukspassphrase.glade.h:4
msgid "Enter passphrase for encrypted partition"
msgstr "暗号化されたパーティション用のパスフレーズを入力してください。"

#: data/ui/lukspassphrase.glade.h:5
msgid "Enter passphrase:"
msgstr "パスフレーズ:"

#: data/ui/netconfig.glade.h:2
msgid "<b>Gateway:</b>"
msgstr "<b>ゲートウェイ:</b>"

#: data/ui/netconfig.glade.h:3
msgid "<b>IPv4 Address:</b>"
msgstr "<b>IPv4 アドレス:</b>"

#: data/ui/netconfig.glade.h:4
msgid "<b>IPv6 Address:</b>"
msgstr "<b>IPv6 アドレス:</b>"

#: data/ui/netconfig.glade.h:5
msgid "<b>Nameserver:</b>"
msgstr "<b>ネームサーバー:</b>"

#: data/ui/netconfig.glade.h:6
msgid "<b>_Interface:</b>"
msgstr "<b>インターフェイス (_I):</b>"

#: data/ui/netconfig.glade.h:7
msgid "Enable IPv_4 support"
msgstr "IPv4 サポートを有効にする (_4)"

#: data/ui/netconfig.glade.h:8
msgid "Enable IPv_6 support"
msgstr "IPv6 サポートを有効にする (_6)"

#: data/ui/netconfig.glade.h:11
msgid "Use _dynamic IP configuration (DHCP)"
msgstr "DHCP (動的 IP 設定) を使用 (_D)"

#: data/ui/network.glade.h:1
msgid "Configure Network"
msgstr "ネットワークの設定"

#: data/ui/network.glade.h:2
msgid "Hostname:"
msgstr "ホスト名:"

#: data/ui/network.glade.h:3
msgid ""
"Please name this computer.  The hostname identifies the computer on a "
"network."
msgstr ""
"このコンピュータのホスト名を指定してください。ホスト名はネットワーク上でこの"
"コンピュータを識別するために必要です。"

#: data/ui/tasksel.glade.h:1
msgid "Customize _later"
msgstr "後でカスタマイズ (_L)"

#: data/ui/tasksel.glade.h:2
msgid ""
"Please select any additional repositories that you want to use for software "
"installation."
msgstr "ソフトウェアのインストールに必要な追加リポジトリーを選択してください。"

#: data/ui/tasksel.glade.h:4
#, no-c-format
msgid ""
"The default installation of %s includes a set of software applicable for "
"general internet usage.  What additional tasks would you like your system to "
"support?"
msgstr ""
"%s のデフォルトインストールには一般的なネットワーク環境での利用できるソフト"
"ウェアのセットが含まれています。システムに追加で対応させたいタスクは何です"
"か？"

#: data/ui/tasksel.glade.h:5
msgid ""
"You can further customize the software selection now, or after install via "
"the software management application."
msgstr ""
"次のステップでソフトウェアの選択を詳細にカスタマイズすることができます。 また"
"はインストール後にソフトウェア管理アプリケーションでカスタマイズを行うことも"
"できます。"

#: data/ui/tasksel.glade.h:6
msgid "_Add additional software repositories"
msgstr "他のソフトウェアリポジトリーの追加(_A)"

#: data/ui/tasksel.glade.h:7
msgid "_Customize now"
msgstr "今すぐカスタマイズ(_C)"

#: data/ui/tasksel.glade.h:8
msgid "_Modify repository"
msgstr "リポジトリーの編集 (_M)"

#: data/ui/zfcp-config.glade.h:1
msgid "<b>Device number:</b>"
msgstr "<b>デバイス番号:</b>"

#: data/ui/zfcp-config.glade.h:2
msgid "<b>FCP LUN:</b>"
msgstr "<b>FCP LUN:</b>"

#: data/ui/zfcp-config.glade.h:3
msgid "<b>WWPN:</b>"
msgstr "<b>WWPN:</b>"

#: data/ui/zfcp-config.glade.h:4
msgid "Add FCP device"
msgstr "FCP デバイスの追加"

#: data/ui/zfcp-config.glade.h:5
msgid ""
"zSeries machines can access industry-standard SCSI devices via Fibre Channel "
"(FCP). You need to provide a 16 bit device number, a 64 bit World Wide Port "
"Name (WWPN), and a 64 bit FCP LUN for each device."
msgstr ""
"zSeries マシンはファイバーチャネル (FCP) 経由で業界基準の SCSI デバイスにアク"
"セスすることができます。それぞれのデバイスに 16 ビットのデバイス番号、64 ビッ"
"トの World Wide Port Name (WWPN) および 64 ビットの FCP LUN を指定する必要が"
"あります。"

#: data/lang-table.h:1
msgid "Afrikaans"
msgstr "アフリカーンス語"

#: data/lang-table.h:2
msgid "Arabic"
msgstr "アラビア語"

#: data/lang-table.h:3
msgid "Assamese"
msgstr "アッサム語"

#: data/lang-table.h:4
msgid "Bengali"
msgstr "ベンガル語"

#: data/lang-table.h:5
msgid "Bengali(India)"
msgstr "ベンガル語 (インド)"

#: data/lang-table.h:6
msgid "Bulgarian"
msgstr "ブルガリア語"

#: data/lang-table.h:7
msgid "Catalan"
msgstr "カタロニア語"

#: data/lang-table.h:8
msgid "Chinese(Simplified)"
msgstr "中国語 (簡体)"

#: data/lang-table.h:9
msgid "Chinese(Traditional)"
msgstr "中国語 (繁体)"

#: data/lang-table.h:10
msgid "Croatian"
msgstr "クロアチア語"

#: data/lang-table.h:11
msgid "Czech"
msgstr "チェコ語"

#: data/lang-table.h:12
msgid "Danish"
msgstr "デンマーク語"

#: data/lang-table.h:13
msgid "Dutch"
msgstr "オランダ語"

#: data/lang-table.h:14
msgid "English"
msgstr "英語"

#: data/lang-table.h:15
msgid "Estonian"
msgstr "エストニア語"

#: data/lang-table.h:16
msgid "Finnish"
msgstr "フィンランド語"

#: data/lang-table.h:17
msgid "French"
msgstr "フランス語"

#: data/lang-table.h:18
msgid "German"
msgstr "ドイツ語"

#: data/lang-table.h:19
msgid "Greek"
msgstr "ギリシャ語"

#: data/lang-table.h:20
msgid "Gujarati"
msgstr "グジャラート語"

#: data/lang-table.h:21
msgid "Hebrew"
msgstr "ヘブライ語"

#: data/lang-table.h:22
msgid "Hindi"
msgstr "ヒンディー語"

#: data/lang-table.h:23
msgid "Hungarian"
msgstr "ハンガリー語"

#: data/lang-table.h:24
msgid "Icelandic"
msgstr "アイスランド語"

#: data/lang-table.h:25
msgid "Iloko"
msgstr "イロコ語"

#: data/lang-table.h:26
msgid "Indonesian"
msgstr "インドネシア語"

#: data/lang-table.h:27
msgid "Italian"
msgstr "イタリア語"

#: data/lang-table.h:28
msgid "Japanese"
msgstr "日本語"

#: data/lang-table.h:29
msgid "Kannada"
msgstr "カンナダ語"

#: data/lang-table.h:30
msgid "Korean"
msgstr "韓国語"

#: data/lang-table.h:31
msgid "Macedonian"
msgstr "マケドニア語"

#: data/lang-table.h:32
msgid "Maithili"
msgstr "マイティリー語"

#: data/lang-table.h:33
msgid "Malay"
msgstr "マレー語"

#: data/lang-table.h:34
msgid "Malayalam"
msgstr "マラヤーラム語"

#: data/lang-table.h:35
msgid "Marathi"
msgstr "マラーティー語"

#: data/lang-table.h:36
msgid "Nepali"
msgstr "ネパール語"

#: data/lang-table.h:37
msgid "Norwegian(Bokmål)"
msgstr "ノルウェー語 (ブークモール)"

#: data/lang-table.h:38
msgid "Northern Sotho"
msgstr "北ソト語"

#: data/lang-table.h:39
msgid "Oriya"
msgstr "オリヤー語"

#: data/lang-table.h:40
msgid "Persian"
msgstr "ペルシア語"

#: data/lang-table.h:41
msgid "Polish"
msgstr "ポーランド語"

#: data/lang-table.h:42
msgid "Portuguese"
msgstr "ポルトガル語"

#: data/lang-table.h:43
msgid "Portuguese(Brazilian)"
msgstr "ポルトガル語 (ブラジル系)"

#: data/lang-table.h:44
msgid "Punjabi"
msgstr "パンジャブ語"

#: data/lang-table.h:45
msgid "Romanian"
msgstr "ルーマニア語"

#: data/lang-table.h:46
msgid "Russian"
msgstr "ロシア語"

#: data/lang-table.h:47
msgid "Serbian"
msgstr "セルビア語"

#: data/lang-table.h:48
msgid "Serbian(Latin)"
msgstr "セルビア語(ラテン系)"

#: data/lang-table.h:49
msgid "Sinhala"
msgstr "シンハラ語"

#: data/lang-table.h:50
msgid "Slovak"
msgstr "スロバキア語"

#: data/lang-table.h:51
msgid "Slovenian"
msgstr "スロヴェニア語"

#: data/lang-table.h:52
msgid "Spanish"
msgstr "スペイン語"

#: data/lang-table.h:53
msgid "Swedish"
msgstr "スウェーデン語"

#: data/lang-table.h:54
msgid "Tajik"
msgstr "タジク語"

#: data/lang-table.h:55
msgid "Tamil"
msgstr "タミル語"

#: data/lang-table.h:56
msgid "Telugu"
msgstr "テルグ語"

#: data/lang-table.h:57
msgid "Turkish"
msgstr "トルコ語"

#: data/lang-table.h:58
msgid "Ukrainian"
msgstr "ウクライナ語"

#: data/lang-table.h:59
msgid "Vietnamese"
msgstr "ベトナム語"

#: data/lang-table.h:60
msgid "Welsh"
msgstr "ウェールズ語"

#: data/lang-table.h:61
msgid "Zulu"
msgstr "ズールー語"

#~ msgid "You do not have enough RAM to use the graphical installer."
#~ msgstr "グラフィカルインストーラーを使用するには RAM が足りません。"

#~ msgid "Telnet"
#~ msgstr "Telnet"

#~ msgid "Waiting for telnet connection."
#~ msgstr "telnet 接続の待機中。"

#~ msgid "Running anaconda via telnet."
#~ msgstr "telnet 経由で anaconda を実行中。"

#~ msgid "Use dynamic IP configuration (DHCP)"
#~ msgstr "動的 IP 設定 (DHCP) を使用"

#~ msgid "Missing Device"
#~ msgstr "欠如パッケージ"

#~ msgid "You must select a network device"
#~ msgstr "ネットワークデバイスを選択する必要があります"

#~ msgid "IPv4 Network Mask "
#~ msgstr "IPv4 ネットワークマスク"

#~ msgid "Error configuring network device"
#~ msgstr "ネットワークデバイス設定中にエラー発生"

#~ msgid "Error configuring network device %s"
#~ msgstr "ネットワークデバイス %s の設定中にエラー発生"
